---@meta

---@class MacrolineEdit: LineEdit
local MacrolineEdit = {}
---@return "MacrolineEdit"
function MacrolineEdit:GetClass() end
---@return "UIObject"
function MacrolineEdit:GetChildClass() end
---@generic T : MacrolineEdit
---@param class `T`
---@return boolean
function MacrolineEdit:IsClass(class) end
---@generic T : SampleTableView|Toolbar|GrandMasterFader|HardwareFader|ShaperPovFader|ColorInterfaceFader|DeskLightsFader|ProgressBar|DCRemoteInfo|TimelineCell|ScrollBar|ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|ExecutorBarXKeys|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|CommandLineWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|BaseItemButtons|UIGridInternals|AudioPreview|XlrModeButton|SpecialExecConfigInput|OSCActivityButton|TitlebuttonControl|ColorPropertyInput|ExecConfigInput|TCTimeButton|CalculatorChannelSetControl|EncoderControl|DialogButton|StateButton|ValueControl|ToggleButtonList|ObjectSelector|UserEncoderPageSelector|ExecConfigSwipe|EnableMasterFaderButton|EncoderLinkButton|EditTitlebarButton|ValueFadeControl|SelectionIndicatorButton|MatricksToggleButton|ExecConfigRowButton|AtFilterControl|MainDlgGridToggleButton|ExecConfigColButton|SpecialExecutorKey|MatricksIndicatorButton|UIToggleButton|RotationButton|KeyboardShortcutControl|BatteryControl|AtFilterPreview|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|DeleteWindowButton|VirtualKeyboardButton|KBShortcutButton|ExpandableButton|TimerButton|MainDlgButtonBase|MainDlgLoginButton|TimecodeSlotButton|DisplayButton|MainDlgUndoButton|BlinkingFadeButton|WarningInfoButton|EjectButton|DimmerWheelButton|MouseButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|RevertButton|EncoderOverlayPlaceholder|ModalPlaceholder|EncoderBarPlaceHolder|PopupPlaceholder|LineEditExt|KeybSCEdit|NumInputEdit|CmdlineEdit|ColorView|SensorView|DialogContainer|PopupList|DBObjectTab|RadioButtonList|FixturetypeItemList|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|TimecodeSlotInfo|TextView|TouchConfigurator|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|CommandLineOutput|SoundLevelView|PerformanceView|ColorTestView|InfoNotesGridScroller|TouchTarget|EditorBase|OutputTest|ColorPickBase|SignalView|ShaperTestView
---@param index integer
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(index: integer, class: "UIObject", undo: Undo?): UIObject
---@overload fun(index: integer, class: "UiFader", undo: Undo?): UiFader
---@overload fun(index: integer, class: "UIGridCellBase", undo: Undo?): UIGridCellBase
---@overload fun(index: integer, class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(index: integer, class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(index: integer, class: "Drawable", undo: Undo?): Drawable
---@overload fun(index: integer, class: "Overlay", undo: Undo?): Overlay
---@overload fun(index: integer, class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(index: integer, class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(index: integer, class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(index: integer, class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(index: integer, class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(index: integer, class: "Bar", undo: Undo?): Bar
---@overload fun(index: integer, class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(index: integer, class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(index: integer, class: "Window", undo: Undo?): Window
---@overload fun(index: integer, class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(index: integer, class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(index: integer, class: "UIObjectFake", undo: Undo?): UIObjectFake
---@overload fun(index: integer, class: "Button", undo: Undo?): Button
---@overload fun(index: integer, class: "PropertyControl", undo: Undo?): PropertyControl
---@overload fun(index: integer, class: "IndicatorControl", undo: Undo?): IndicatorControl
---@overload fun(index: integer, class: "PropertyInput", undo: Undo?): PropertyInput
---@overload fun(index: integer, class: "AppearanceInput", undo: Undo?): AppearanceInput
---@overload fun(index: integer, class: "ScribbleInput", undo: Undo?): ScribbleInput
---@overload fun(index: integer, class: "BaseStateButton", undo: Undo?): BaseStateButton
---@overload fun(index: integer, class: "ToggleButton", undo: Undo?): ToggleButton
---@overload fun(index: integer, class: "SwipeButton", undo: Undo?): SwipeButton
---@overload fun(index: integer, class: "LogoButton", undo: Undo?): LogoButton
---@overload fun(index: integer, class: "ContextButton", undo: Undo?): ContextButton
---@overload fun(index: integer, class: "IndicatorButton", undo: Undo?): IndicatorButton
---@overload fun(index: integer, class: "TitleButton", undo: Undo?): TitleButton
---@overload fun(index: integer, class: "PlaceHolderBase", undo: Undo?): PlaceHolderBase
---@overload fun(index: integer, class: "PlaceHolder", undo: Undo?): PlaceHolder
---@overload fun(index: integer, class: "LineEdit", undo: Undo?): LineEdit
---@overload fun(index: integer, class: "ScrollableItemList", undo: Undo?): ScrollableItemList
---@overload fun(index: integer, class: "UITab", undo: Undo?): UITab
---@overload fun(index: integer, class: nil, undo: Undo?): UIObject
function MacrolineEdit:Create(index, class, undo) end
---@generic T : SampleTableView|Toolbar|GrandMasterFader|HardwareFader|ShaperPovFader|ColorInterfaceFader|DeskLightsFader|ProgressBar|DCRemoteInfo|TimelineCell|ScrollBar|ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|ExecutorBarXKeys|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|CommandLineWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|BaseItemButtons|UIGridInternals|AudioPreview|XlrModeButton|SpecialExecConfigInput|OSCActivityButton|TitlebuttonControl|ColorPropertyInput|ExecConfigInput|TCTimeButton|CalculatorChannelSetControl|EncoderControl|DialogButton|StateButton|ValueControl|ToggleButtonList|ObjectSelector|UserEncoderPageSelector|ExecConfigSwipe|EnableMasterFaderButton|EncoderLinkButton|EditTitlebarButton|ValueFadeControl|SelectionIndicatorButton|MatricksToggleButton|ExecConfigRowButton|AtFilterControl|MainDlgGridToggleButton|ExecConfigColButton|SpecialExecutorKey|MatricksIndicatorButton|UIToggleButton|RotationButton|KeyboardShortcutControl|BatteryControl|AtFilterPreview|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|DeleteWindowButton|VirtualKeyboardButton|KBShortcutButton|ExpandableButton|TimerButton|MainDlgButtonBase|MainDlgLoginButton|TimecodeSlotButton|DisplayButton|MainDlgUndoButton|BlinkingFadeButton|WarningInfoButton|EjectButton|DimmerWheelButton|MouseButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|RevertButton|EncoderOverlayPlaceholder|ModalPlaceholder|EncoderBarPlaceHolder|PopupPlaceholder|LineEditExt|KeybSCEdit|NumInputEdit|CmdlineEdit|ColorView|SensorView|DialogContainer|PopupList|DBObjectTab|RadioButtonList|FixturetypeItemList|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|TimecodeSlotInfo|TextView|TouchConfigurator|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|CommandLineOutput|SoundLevelView|PerformanceView|ColorTestView|InfoNotesGridScroller|TouchTarget|EditorBase|OutputTest|ColorPickBase|SignalView|ShaperTestView
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(class: "UIObject", undo: Undo?, count: integer?): UIObject
---@overload fun(class: "UiFader", undo: Undo?, count: integer?): UiFader
---@overload fun(class: "UIGridCellBase", undo: Undo?, count: integer?): UIGridCellBase
---@overload fun(class: "UILayoutGrid", undo: Undo?, count: integer?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?, count: integer?): AutoLayout
---@overload fun(class: "Drawable", undo: Undo?, count: integer?): Drawable
---@overload fun(class: "Overlay", undo: Undo?, count: integer?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?, count: integer?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?, count: integer?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?, count: integer?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?, count: integer?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?, count: integer?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?, count: integer?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?, count: integer?): ExecutorBar
---@overload fun(class: "GlWindowBase", undo: Undo?, count: integer?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?, count: integer?): Window
---@overload fun(class: "PoolLayoutGrid", undo: Undo?, count: integer?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?, count: integer?): UiScreen
---@overload fun(class: "UIObjectFake", undo: Undo?, count: integer?): UIObjectFake
---@overload fun(class: "Button", undo: Undo?, count: integer?): Button
---@overload fun(class: "PropertyControl", undo: Undo?, count: integer?): PropertyControl
---@overload fun(class: "IndicatorControl", undo: Undo?, count: integer?): IndicatorControl
---@overload fun(class: "PropertyInput", undo: Undo?, count: integer?): PropertyInput
---@overload fun(class: "AppearanceInput", undo: Undo?, count: integer?): AppearanceInput
---@overload fun(class: "ScribbleInput", undo: Undo?, count: integer?): ScribbleInput
---@overload fun(class: "BaseStateButton", undo: Undo?, count: integer?): BaseStateButton
---@overload fun(class: "ToggleButton", undo: Undo?, count: integer?): ToggleButton
---@overload fun(class: "SwipeButton", undo: Undo?, count: integer?): SwipeButton
---@overload fun(class: "LogoButton", undo: Undo?, count: integer?): LogoButton
---@overload fun(class: "ContextButton", undo: Undo?, count: integer?): ContextButton
---@overload fun(class: "IndicatorButton", undo: Undo?, count: integer?): IndicatorButton
---@overload fun(class: "TitleButton", undo: Undo?, count: integer?): TitleButton
---@overload fun(class: "PlaceHolderBase", undo: Undo?, count: integer?): PlaceHolderBase
---@overload fun(class: "PlaceHolder", undo: Undo?, count: integer?): PlaceHolder
---@overload fun(class: "LineEdit", undo: Undo?, count: integer?): LineEdit
---@overload fun(class: "ScrollableItemList", undo: Undo?, count: integer?): ScrollableItemList
---@overload fun(class: "UITab", undo: Undo?, count: integer?): UITab
---@overload fun(class: nil, undo: Undo?, count: integer?): UIObject
function MacrolineEdit:Append(class, undo, count) end
---@generic T : SampleTableView|Toolbar|GrandMasterFader|HardwareFader|ShaperPovFader|ColorInterfaceFader|DeskLightsFader|ProgressBar|DCRemoteInfo|TimelineCell|ScrollBar|ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|ExecutorBarXKeys|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|CommandLineWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|BaseItemButtons|UIGridInternals|AudioPreview|XlrModeButton|SpecialExecConfigInput|OSCActivityButton|TitlebuttonControl|ColorPropertyInput|ExecConfigInput|TCTimeButton|CalculatorChannelSetControl|EncoderControl|DialogButton|StateButton|ValueControl|ToggleButtonList|ObjectSelector|UserEncoderPageSelector|ExecConfigSwipe|EnableMasterFaderButton|EncoderLinkButton|EditTitlebarButton|ValueFadeControl|SelectionIndicatorButton|MatricksToggleButton|ExecConfigRowButton|AtFilterControl|MainDlgGridToggleButton|ExecConfigColButton|SpecialExecutorKey|MatricksIndicatorButton|UIToggleButton|RotationButton|KeyboardShortcutControl|BatteryControl|AtFilterPreview|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|DeleteWindowButton|VirtualKeyboardButton|KBShortcutButton|ExpandableButton|TimerButton|MainDlgButtonBase|MainDlgLoginButton|TimecodeSlotButton|DisplayButton|MainDlgUndoButton|BlinkingFadeButton|WarningInfoButton|EjectButton|DimmerWheelButton|MouseButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|RevertButton|EncoderOverlayPlaceholder|ModalPlaceholder|EncoderBarPlaceHolder|PopupPlaceholder|LineEditExt|KeybSCEdit|NumInputEdit|CmdlineEdit|ColorView|SensorView|DialogContainer|PopupList|DBObjectTab|RadioButtonList|FixturetypeItemList|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|TimecodeSlotInfo|TextView|TouchConfigurator|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|CommandLineOutput|SoundLevelView|PerformanceView|ColorTestView|InfoNotesGridScroller|TouchTarget|EditorBase|OutputTest|ColorPickBase|SignalView|ShaperTestView
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "UIObject", undo: Undo?): UIObject
---@overload fun(class: "UiFader", undo: Undo?): UiFader
---@overload fun(class: "UIGridCellBase", undo: Undo?): UIGridCellBase
---@overload fun(class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(class: "Drawable", undo: Undo?): Drawable
---@overload fun(class: "Overlay", undo: Undo?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?): Window
---@overload fun(class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(class: "UIObjectFake", undo: Undo?): UIObjectFake
---@overload fun(class: "Button", undo: Undo?): Button
---@overload fun(class: "PropertyControl", undo: Undo?): PropertyControl
---@overload fun(class: "IndicatorControl", undo: Undo?): IndicatorControl
---@overload fun(class: "PropertyInput", undo: Undo?): PropertyInput
---@overload fun(class: "AppearanceInput", undo: Undo?): AppearanceInput
---@overload fun(class: "ScribbleInput", undo: Undo?): ScribbleInput
---@overload fun(class: "BaseStateButton", undo: Undo?): BaseStateButton
---@overload fun(class: "ToggleButton", undo: Undo?): ToggleButton
---@overload fun(class: "SwipeButton", undo: Undo?): SwipeButton
---@overload fun(class: "LogoButton", undo: Undo?): LogoButton
---@overload fun(class: "ContextButton", undo: Undo?): ContextButton
---@overload fun(class: "IndicatorButton", undo: Undo?): IndicatorButton
---@overload fun(class: "TitleButton", undo: Undo?): TitleButton
---@overload fun(class: "PlaceHolderBase", undo: Undo?): PlaceHolderBase
---@overload fun(class: "PlaceHolder", undo: Undo?): PlaceHolder
---@overload fun(class: "LineEdit", undo: Undo?): LineEdit
---@overload fun(class: "ScrollableItemList", undo: Undo?): ScrollableItemList
---@overload fun(class: "UITab", undo: Undo?): UITab
---@overload fun(class: nil, undo: Undo?): UIObject
function MacrolineEdit:Acquire(class, undo) end
---@generic T : SampleTableView|Toolbar|GrandMasterFader|HardwareFader|ShaperPovFader|ColorInterfaceFader|DeskLightsFader|ProgressBar|DCRemoteInfo|TimelineCell|ScrollBar|ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|ExecutorBarXKeys|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|CommandLineWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|BaseItemButtons|UIGridInternals|AudioPreview|XlrModeButton|SpecialExecConfigInput|OSCActivityButton|TitlebuttonControl|ColorPropertyInput|ExecConfigInput|TCTimeButton|CalculatorChannelSetControl|EncoderControl|DialogButton|StateButton|ValueControl|ToggleButtonList|ObjectSelector|UserEncoderPageSelector|ExecConfigSwipe|EnableMasterFaderButton|EncoderLinkButton|EditTitlebarButton|ValueFadeControl|SelectionIndicatorButton|MatricksToggleButton|ExecConfigRowButton|AtFilterControl|MainDlgGridToggleButton|ExecConfigColButton|SpecialExecutorKey|MatricksIndicatorButton|UIToggleButton|RotationButton|KeyboardShortcutControl|BatteryControl|AtFilterPreview|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|DeleteWindowButton|VirtualKeyboardButton|KBShortcutButton|ExpandableButton|TimerButton|MainDlgButtonBase|MainDlgLoginButton|TimecodeSlotButton|DisplayButton|MainDlgUndoButton|BlinkingFadeButton|WarningInfoButton|EjectButton|DimmerWheelButton|MouseButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|RevertButton|EncoderOverlayPlaceholder|ModalPlaceholder|EncoderBarPlaceHolder|PopupPlaceholder|LineEditExt|KeybSCEdit|NumInputEdit|CmdlineEdit|ColorView|SensorView|DialogContainer|PopupList|DBObjectTab|RadioButtonList|FixturetypeItemList|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|TimecodeSlotInfo|TextView|TouchConfigurator|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|CommandLineOutput|SoundLevelView|PerformanceView|ColorTestView|InfoNotesGridScroller|TouchTarget|EditorBase|OutputTest|ColorPickBase|SignalView|ShaperTestView
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "UIObject", undo: Undo?): UIObject
---@overload fun(class: "UiFader", undo: Undo?): UiFader
---@overload fun(class: "UIGridCellBase", undo: Undo?): UIGridCellBase
---@overload fun(class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(class: "Drawable", undo: Undo?): Drawable
---@overload fun(class: "Overlay", undo: Undo?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?): Window
---@overload fun(class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(class: "UIObjectFake", undo: Undo?): UIObjectFake
---@overload fun(class: "Button", undo: Undo?): Button
---@overload fun(class: "PropertyControl", undo: Undo?): PropertyControl
---@overload fun(class: "IndicatorControl", undo: Undo?): IndicatorControl
---@overload fun(class: "PropertyInput", undo: Undo?): PropertyInput
---@overload fun(class: "AppearanceInput", undo: Undo?): AppearanceInput
---@overload fun(class: "ScribbleInput", undo: Undo?): ScribbleInput
---@overload fun(class: "BaseStateButton", undo: Undo?): BaseStateButton
---@overload fun(class: "ToggleButton", undo: Undo?): ToggleButton
---@overload fun(class: "SwipeButton", undo: Undo?): SwipeButton
---@overload fun(class: "LogoButton", undo: Undo?): LogoButton
---@overload fun(class: "ContextButton", undo: Undo?): ContextButton
---@overload fun(class: "IndicatorButton", undo: Undo?): IndicatorButton
---@overload fun(class: "TitleButton", undo: Undo?): TitleButton
---@overload fun(class: "PlaceHolderBase", undo: Undo?): PlaceHolderBase
---@overload fun(class: "PlaceHolder", undo: Undo?): PlaceHolder
---@overload fun(class: "LineEdit", undo: Undo?): LineEdit
---@overload fun(class: "ScrollableItemList", undo: Undo?): ScrollableItemList
---@overload fun(class: "UITab", undo: Undo?): UITab
---@overload fun(class: nil, undo: Undo?): UIObject
---@deprecated use "Acquire" instead
function MacrolineEdit:Aquire(class, undo) end
---@generic T : SampleTableView|Toolbar|GrandMasterFader|HardwareFader|ShaperPovFader|ColorInterfaceFader|DeskLightsFader|ProgressBar|DCRemoteInfo|TimelineCell|ScrollBar|ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|ExecutorBarXKeys|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|CommandLineWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|BaseItemButtons|UIGridInternals|AudioPreview|XlrModeButton|SpecialExecConfigInput|OSCActivityButton|TitlebuttonControl|ColorPropertyInput|ExecConfigInput|TCTimeButton|CalculatorChannelSetControl|EncoderControl|DialogButton|StateButton|ValueControl|ToggleButtonList|ObjectSelector|UserEncoderPageSelector|ExecConfigSwipe|EnableMasterFaderButton|EncoderLinkButton|EditTitlebarButton|ValueFadeControl|SelectionIndicatorButton|MatricksToggleButton|ExecConfigRowButton|AtFilterControl|MainDlgGridToggleButton|ExecConfigColButton|SpecialExecutorKey|MatricksIndicatorButton|UIToggleButton|RotationButton|KeyboardShortcutControl|BatteryControl|AtFilterPreview|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|DeleteWindowButton|VirtualKeyboardButton|KBShortcutButton|ExpandableButton|TimerButton|MainDlgButtonBase|MainDlgLoginButton|TimecodeSlotButton|DisplayButton|MainDlgUndoButton|BlinkingFadeButton|WarningInfoButton|EjectButton|DimmerWheelButton|MouseButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|RevertButton|EncoderOverlayPlaceholder|ModalPlaceholder|EncoderBarPlaceHolder|PopupPlaceholder|LineEditExt|KeybSCEdit|NumInputEdit|CmdlineEdit|ColorView|SensorView|DialogContainer|PopupList|DBObjectTab|RadioButtonList|FixturetypeItemList|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|TimecodeSlotInfo|TextView|TouchConfigurator|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|CommandLineOutput|SoundLevelView|PerformanceView|ColorTestView|InfoNotesGridScroller|TouchTarget|EditorBase|OutputTest|ColorPickBase|SignalView|ShaperTestView
---@param index integer
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(index: integer, class: "UIObject", undo: Undo?, count: integer?): UIObject
---@overload fun(index: integer, class: "UiFader", undo: Undo?, count: integer?): UiFader
---@overload fun(index: integer, class: "UIGridCellBase", undo: Undo?, count: integer?): UIGridCellBase
---@overload fun(index: integer, class: "UILayoutGrid", undo: Undo?, count: integer?): UILayoutGrid
---@overload fun(index: integer, class: "AutoLayout", undo: Undo?, count: integer?): AutoLayout
---@overload fun(index: integer, class: "Drawable", undo: Undo?, count: integer?): Drawable
---@overload fun(index: integer, class: "Overlay", undo: Undo?, count: integer?): Overlay
---@overload fun(index: integer, class: "ShadedOverlay", undo: Undo?, count: integer?): ShadedOverlay
---@overload fun(index: integer, class: "BaseInput", undo: Undo?, count: integer?): BaseInput
---@overload fun(index: integer, class: "GenericImport", undo: Undo?, count: integer?): GenericImport
---@overload fun(index: integer, class: "TextEdit", undo: Undo?, count: integer?): TextEdit
---@overload fun(index: integer, class: "NoteTextEdit", undo: Undo?, count: integer?): NoteTextEdit
---@overload fun(index: integer, class: "Bar", undo: Undo?, count: integer?): Bar
---@overload fun(index: integer, class: "ExecutorBar", undo: Undo?, count: integer?): ExecutorBar
---@overload fun(index: integer, class: "GlWindowBase", undo: Undo?, count: integer?): GlWindowBase
---@overload fun(index: integer, class: "Window", undo: Undo?, count: integer?): Window
---@overload fun(index: integer, class: "PoolLayoutGrid", undo: Undo?, count: integer?): PoolLayoutGrid
---@overload fun(index: integer, class: "UiScreen", undo: Undo?, count: integer?): UiScreen
---@overload fun(index: integer, class: "UIObjectFake", undo: Undo?, count: integer?): UIObjectFake
---@overload fun(index: integer, class: "Button", undo: Undo?, count: integer?): Button
---@overload fun(index: integer, class: "PropertyControl", undo: Undo?, count: integer?): PropertyControl
---@overload fun(index: integer, class: "IndicatorControl", undo: Undo?, count: integer?): IndicatorControl
---@overload fun(index: integer, class: "PropertyInput", undo: Undo?, count: integer?): PropertyInput
---@overload fun(index: integer, class: "AppearanceInput", undo: Undo?, count: integer?): AppearanceInput
---@overload fun(index: integer, class: "ScribbleInput", undo: Undo?, count: integer?): ScribbleInput
---@overload fun(index: integer, class: "BaseStateButton", undo: Undo?, count: integer?): BaseStateButton
---@overload fun(index: integer, class: "ToggleButton", undo: Undo?, count: integer?): ToggleButton
---@overload fun(index: integer, class: "SwipeButton", undo: Undo?, count: integer?): SwipeButton
---@overload fun(index: integer, class: "LogoButton", undo: Undo?, count: integer?): LogoButton
---@overload fun(index: integer, class: "ContextButton", undo: Undo?, count: integer?): ContextButton
---@overload fun(index: integer, class: "IndicatorButton", undo: Undo?, count: integer?): IndicatorButton
---@overload fun(index: integer, class: "TitleButton", undo: Undo?, count: integer?): TitleButton
---@overload fun(index: integer, class: "PlaceHolderBase", undo: Undo?, count: integer?): PlaceHolderBase
---@overload fun(index: integer, class: "PlaceHolder", undo: Undo?, count: integer?): PlaceHolder
---@overload fun(index: integer, class: "LineEdit", undo: Undo?, count: integer?): LineEdit
---@overload fun(index: integer, class: "ScrollableItemList", undo: Undo?, count: integer?): ScrollableItemList
---@overload fun(index: integer, class: "UITab", undo: Undo?, count: integer?): UITab
---@overload fun(index: integer, class: nil, undo: Undo?, count: integer?): UIObject
function MacrolineEdit:Insert(index, class, undo, count) end
---@generic T : SampleTableView|Toolbar|GrandMasterFader|HardwareFader|ShaperPovFader|ColorInterfaceFader|DeskLightsFader|ProgressBar|DCRemoteInfo|TimelineCell|ScrollBar|ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|ExecutorBarXKeys|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|CommandLineWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|BaseItemButtons|UIGridInternals|AudioPreview|XlrModeButton|SpecialExecConfigInput|OSCActivityButton|TitlebuttonControl|ColorPropertyInput|ExecConfigInput|TCTimeButton|CalculatorChannelSetControl|EncoderControl|DialogButton|StateButton|ValueControl|ToggleButtonList|ObjectSelector|UserEncoderPageSelector|ExecConfigSwipe|EnableMasterFaderButton|EncoderLinkButton|EditTitlebarButton|ValueFadeControl|SelectionIndicatorButton|MatricksToggleButton|ExecConfigRowButton|AtFilterControl|MainDlgGridToggleButton|ExecConfigColButton|SpecialExecutorKey|MatricksIndicatorButton|UIToggleButton|RotationButton|KeyboardShortcutControl|BatteryControl|AtFilterPreview|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|DeleteWindowButton|VirtualKeyboardButton|KBShortcutButton|ExpandableButton|TimerButton|MainDlgButtonBase|MainDlgLoginButton|TimecodeSlotButton|DisplayButton|MainDlgUndoButton|BlinkingFadeButton|WarningInfoButton|EjectButton|DimmerWheelButton|MouseButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|RevertButton|EncoderOverlayPlaceholder|ModalPlaceholder|EncoderBarPlaceHolder|PopupPlaceholder|LineEditExt|KeybSCEdit|NumInputEdit|CmdlineEdit|ColorView|SensorView|DialogContainer|PopupList|DBObjectTab|RadioButtonList|FixturetypeItemList|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|TimecodeSlotInfo|TextView|TouchConfigurator|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|CommandLineOutput|SoundLevelView|PerformanceView|ColorTestView|InfoNotesGridScroller|TouchTarget|EditorBase|OutputTest|ColorPickBase|SignalView|ShaperTestView
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "UIObject", undo: Undo?): UIObject
---@overload fun(class: "UiFader", undo: Undo?): UiFader
---@overload fun(class: "UIGridCellBase", undo: Undo?): UIGridCellBase
---@overload fun(class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(class: "Drawable", undo: Undo?): Drawable
---@overload fun(class: "Overlay", undo: Undo?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?): Window
---@overload fun(class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(class: "UIObjectFake", undo: Undo?): UIObjectFake
---@overload fun(class: "Button", undo: Undo?): Button
---@overload fun(class: "PropertyControl", undo: Undo?): PropertyControl
---@overload fun(class: "IndicatorControl", undo: Undo?): IndicatorControl
---@overload fun(class: "PropertyInput", undo: Undo?): PropertyInput
---@overload fun(class: "AppearanceInput", undo: Undo?): AppearanceInput
---@overload fun(class: "ScribbleInput", undo: Undo?): ScribbleInput
---@overload fun(class: "BaseStateButton", undo: Undo?): BaseStateButton
---@overload fun(class: "ToggleButton", undo: Undo?): ToggleButton
---@overload fun(class: "SwipeButton", undo: Undo?): SwipeButton
---@overload fun(class: "LogoButton", undo: Undo?): LogoButton
---@overload fun(class: "ContextButton", undo: Undo?): ContextButton
---@overload fun(class: "IndicatorButton", undo: Undo?): IndicatorButton
---@overload fun(class: "TitleButton", undo: Undo?): TitleButton
---@overload fun(class: "PlaceHolderBase", undo: Undo?): PlaceHolderBase
---@overload fun(class: "PlaceHolder", undo: Undo?): PlaceHolder
---@overload fun(class: "LineEdit", undo: Undo?): LineEdit
---@overload fun(class: "ScrollableItemList", undo: Undo?): ScrollableItemList
---@overload fun(class: "UITab", undo: Undo?): UITab
---@overload fun(class: nil, undo: Undo?): UIObject
function MacrolineEdit:Find(class, undo) end
---@overload fun(property_name: "Source", property_value: TimeCodeSource)
---@overload fun(property_name: "Mode", property_value: DatumMode|GridModeAgenda|ShowfileSelectorMode|BlinkingButtonMode|CalculatorMode)
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "HotKey", property_value: HotKey)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "EncoderFunction", property_value: PhaserEncoderFunction|TimecodeEncoderFunction|EncoderFunction)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "Focus", property_value: FocusPriority)
---@overload fun(property_name: "Settings", property_value: PSRPatchSheetSettings|CloningWindowSettings|ShowCreatorSettings)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "UserRights", property_value: UserRights)
---@overload fun(property_name: "TargetSound", property_value: Sound)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "InternalRole", property_value: Roles)
---@overload fun(property_name: "MouseButtonType", property_value: MouseButtonTypes)
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Appearance", property_value: Appearance)
---@overload fun(property_name: "Direction", property_value: ToolbarScrollType|AutoLayoutScrollType)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "ChangeText", property_value: fun(newTextStr: string) : boolean)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "KeyCode", property_value: KeyboardCodes)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FocusSearchPolicy", property_value: FocusSearchPolicy)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "EncoderType", property_value: EncoderType)
---@overload fun(property_name: "EncoderRing", property_value: EncoderRing)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "Changed", property_value: fun(str: string, value: integer))
---@overload fun(property_name: "Set", property_value: fun(str: string, value: integer) : boolean)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "ChangeActive", property_value: fun(childName: string) : boolean)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "UIToControl", property_value: SplitterV_TopBottom|SplitterH_LeftRight)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "BackOffset", property_value: ItemGroupPosition)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "CharInput", property_value: fun(str: string, utf32Char: integer))
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "Drive", property_value: Drive)
---@overload fun(property_name: "TabChanged", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "ValueRole", property_value: ValueRole)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "Band", property_value: SoundValues)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "PolicyOnEnter", property_value: PolicyOnEnter)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "Property", property_value: EncoderGroupType)
---@overload fun(property_name: "Icons", property_value: Texture[])
---@overload fun(property_name: "IconsGrid", property_value: Gma3UI.IconsGrid)
---@overload fun(property_name: "IconsGridAnchors", property_value: Gma3UI.IconsGridAnchors[])
---@overload fun(property_name: "SetType", property_value: PropertyRadioButtonListSetType)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "EnabledItems", property_value: PropertyRadioButtonListEnabledItems)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "Clear", property_value: fun(dummyString: string) : boolean)
---@overload fun(property_name: "SetPrompt", property_value: fun(prompt: string) : boolean)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "ValueAlignmentH"|"AlignmentH"|"IconAlignmentH"|"IconAlignmentH"|"TextAlignmentH"|"KeyboardIconAlignmentH"|"LogoIconAlignmentH", property_value: AlignmentH)
---@overload fun(property_name: "ValueAlignmentV"|"AlignmentV"|"IconAlignmentV"|"IconAlignmentV"|"TextAlignmentV"|"LogoIconAlignmentV"|"KeyboardIconAlignmentV", property_value: AlignmentV)
---@overload fun(property_name: "Appearance", property_value: Appearance)
---@overload fun(property_name: "Direction", property_value: AutoLayoutScrollType)
---@overload fun(property_name: "Mode", property_value: BlinkingButtonMode)
---@overload fun(property_name: "Mode", property_value: CalculatorMode)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "TriggerIndirectInitLevel"|"BlockLevel", property_value: ChangeLevel)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "CloneDestinationGrid"|"ScrollBuddy"|"CloneSourceGrid", property_value: CloneGrid)
---@overload fun(property_name: "Settings", property_value: CloningWindowSettings)
---@overload fun(property_name: "PoolColor"|"ActiveBackColor"|"ActiveTextColor"|"ActiveIconColor"|"BackColor"|"SelectedOptionTextColor"|"TextColor"|"TextShadowColor"|"SelectedOptionBackColor"|"MixInBackColor"|"HighlightedColor"|"IconColor"|"SelectionColor"|"ColorLineNumberBackground"|"ColorLineNumberNormal"|"ProgIndicatorBackColor"|"ColorLineNumberSelected"|"ColorSelectedLineRect"|"SelectedBackColor"|"OnColor"|"KnobColorFlashedUp"|"OffColor"|"AlwaysOnColor"|"DisabledColor"|"HeadlineColor"|"SelectedIconColor"|"KnobColor"|"KnobColorFlashedDown"|"SlotColor"|"UpperColor"|"PreviewMixInColor"|"LowerColor"|"OnColor"|"OffColor"|"AlwaysOnColor"|"DisabledColor"|"EditMixInColor"|"BorderColor"|"EditMixInNotOwnerColor"|"IndicatorColor"|"RotateIconColor"|"DbgValueBackColor"|"DbgValueTextColor"|"ResizeLineColor"|"PreviewMixInColor"|"BackColorFlashedDown"|"EditMixInColor"|"DelimiterColor"|"EditMixInNotOwnerColor"|"ActiveDelimiterColor"|"BackColor2"|"IndicatorBack"|"BackColorFlashedUp"|"BlockerColor"|"NonEmptyIndicatorColor"|"OnColor"|"OffColor"|"IndicatorIconBackColor"|"GridColor"|"OverridesIndicatorBackColor"|"XYZTextColor"|"ValueTextColor"|"ValueActiveTextColor"|"PoolColor"|"SelectedTextColor"|"SelectionColor"|"SelectedBackColor"|"FixedBackColor"|"ProgressColor"|"AdditionalInfoTextColor"|"DividerColor"|"BlinkBackColor"|"SelectionColor"|"LevelColor"|"MessageColor"|"PeakColor"|"ScrollCellFrameColor"|"PoolColor"|"SelectedRowBorder"|"LevelColor"|"TriggerColor"|"KnobColor"|"UpperColor"|"LowerColor"|"LassoColor"|"FaderLocked"|"GridColor"|"LowerPressedColor"|"OverridesIndicatorBackColor"|"SampleColor"|"UpperSampleColor"|"MatricksAreaActiveBackColor"|"RecipeEditColor"|"GridColor"|"IconColor"|"TimeCursorColor"|"IconHoverColor"|"SelectedIconColor"|"SensorColor"|"DeselectedIconColor"|"GridColor1"|"WarningColor"|"GridColor2"|"UpperColor"|"PeekColor"|"SignalColor"|"LowerColor", property_value: Color)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "DMXMode"|"DmxMode", property_value: DMXMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "Mode", property_value: DatumMode)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "Drive", property_value: Drive)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FixtureFID"|"FixtureCID", property_value: EmptyAsZeroFID)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "EncoderFunction", property_value: EncoderFunction)
---@overload fun(property_name: "Property", property_value: EncoderGroupType)
---@overload fun(property_name: "EncoderRing", property_value: EncoderRing)
---@overload fun(property_name: "EncoderType", property_value: EncoderType)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "Focus", property_value: FocusPriority)
---@overload fun(property_name: "FocusSearchPolicy", property_value: FocusSearchPolicy)
---@overload fun(property_name: "LowDpiFont"|"Font"|"TcFont", property_value: Font)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "IconsGrid", property_value: Gma3UI.IconsGrid)
---@overload fun(property_name: "IconsGridAnchors", property_value: Gma3UI.IconsGridAnchors[])
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "X"|"Y"|"TextOffsetH"|"W"|"H"|"TextOffsetV"|"IconOffsetV"|"IconOffsetH"|"ScrollBarHeight", property_value: Graphics.SizeDescriptor)
---@overload fun(property_name: "MaxSize"|"MinSize", property_value: Graphics.SizeDimension)
---@overload fun(property_name: "FixedHeaders"|"NormalHeaders"|"FixedCells"|"NormalCells", property_value: Graphics.UIGrid.GridArea)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "Mode", property_value: GridModeAgenda)
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "HotKey", property_value: HotKey)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "ArrayIndex"|"ArrayIndex", property_value: Index)
---@overload fun(property_name: "BackOffset", property_value: ItemGroupPosition)
---@overload fun(property_name: "KeyCode", property_value: KeyboardCodes)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "Target"|"Target", property_value: Mesh)
---@overload fun(property_name: "EscModalResult"|"CloseAction", property_value: ModalResult)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "MouseButtonType", property_value: MouseButtonTypes)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "Target"|"Target"|"TargetObject"|"Target"|"Target"|"ScrollTarget"|"Target"|"Target"|"EditTarget"|"Target"|"Target"|"ExternScrollPos"|"Target"|"Target"|"AppearanceTarget"|"Target"|"CurrentUpdateObject"|"Target"|"MainBuddy"|"ScrollTarget"|"ScribbleTarget"|"Target"|"WorkingDestination"|"EditTarget"|"Target"|"Target"|"Target"|"Target"|"Target"|"Target"|"TargetObject"|"HistoryProvider"|"TextViewProvider"|"Context"|"Target"|"Target"|"EditTarget"|"Target", property_value: Object)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Settings", property_value: PSRPatchSheetSettings)
---@overload fun(property_name: "EncoderFunction", property_value: PhaserEncoderFunction)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "PolicyOnEnter", property_value: PolicyOnEnter)
---@overload fun(property_name: "PoolSettings"|"PoolSettings", property_value: PoolSettings)
---@overload fun(property_name: "SizeY"|"SizeX"|"SizeX"|"SizeY", property_value: PoolSizeFactor)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "EnabledItems", property_value: PropertyRadioButtonListEnabledItems)
---@overload fun(property_name: "SetType", property_value: PropertyRadioButtonListSetType)
---@overload fun(property_name: "RowReductionPolicy"|"ColReductionPolicy", property_value: ReductionPolicy)
---@overload fun(property_name: "ViewW"|"ViewH", property_value: RequestedSize)
---@overload fun(property_name: "InternalRole", property_value: Roles)
---@overload fun(property_name: "ItemPlacementTypeV"|"ItemPlacementTypeH", property_value: ScrollItemPlacementType)
---@overload fun(property_name: "ScrollEntity"|"ScrollEntity", property_value: ScrollParamEntity)
---@overload fun(property_name: "Direction"|"Type"|"Direction"|"ScrollType"|"AutoNextCellDirection"|"Type"|"Direction", property_value: ScrollType)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "Settings", property_value: ShowCreatorSettings)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "Mode", property_value: ShowfileSelectorMode)
---@overload fun(property_name: "TargetSound", property_value: Sound)
---@overload fun(property_name: "Band", property_value: SoundValues)
---@overload fun(property_name: "SpecialExecIndex"|"SpecialExecIndex"|"SpecialExecIndex", property_value: SpecialExecutor)
---@overload fun(property_name: "UIToControl", property_value: SplitterH_LeftRight)
---@overload fun(property_name: "UIToControl", property_value: SplitterV_TopBottom)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "CursorTexture"|"BorderTexture"|"ArrowRight"|"ArrowLeft"|"CountDownIcon"|"CollapsedIcon"|"OnOffTexture"|"SelectionFrame"|"StopwatchIcon"|"Texture"|"HeadLineTexture"|"IndicatorIcon"|"SelectionBackgroundTexture"|"SortAsc"|"TitleButtonIcon"|"SortDesc"|"Icon"|"KnobTexture"|"TriggerTexture"|"SignalTexture"|"SelectionFrame"|"Lasso"|"LockTexture"|"TitleButtonIcon"|"CursorTexture"|"GearTexture"|"SelectionBackgroundTexture"|"OverridesIndicator"|"TextureNormal"|"TextureHover"|"ProgIndicator"|"IndicatorBackTexture"|"SampleTexture"|"IndicatorTexture"|"SelectionTexture"|"ExpandedTexture"|"ContractedTexture"|"DelimiterTexture"|"Icon"|"KnobTexture"|"BrushTexture"|"SelectionTexture"|"SelectedIcon"|"SlotTexture"|"ExpandedIcon"|"DeselectedIcon"|"UpperTexture"|"SensorTexture"|"SelectionFrame"|"LowerTexture"|"IconActive"|"UpperTexture"|"SelectionTexture"|"OnOffTexture"|"IconInactive"|"LowerTexture"|"LogoIcon"|"BlockerTexture"|"SelectedIcon"|"DeselectedIcon", property_value: Texture)
---@overload fun(property_name: "Icons", property_value: Texture[])
---@overload fun(property_name: "Source", property_value: TimeCodeSource)
---@overload fun(property_name: "Position"|"Duration", property_value: TimePropertyValue)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "EncoderFunction", property_value: TimecodeEncoderFunction)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "Direction", property_value: ToolbarScrollType)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "Target"|"LabelLinkHandle"|"LinkedObject"|"TargetObject", property_value: UIObject)
---@overload fun(property_name: "UserRights", property_value: UserRights)
---@overload fun(property_name: "ValueRole", property_value: ValueRole)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "Settings"|"WindowSettings"|"SubWindowSettings"|"WindowSettings"|"WindowSettings"|"WindowSettings", property_value: WindowSettings)
---@overload fun(property_name: "DrawContent"|"BackgroundButtonStyle"|"ShowTcSlotAndTcMode"|"ContentStyle"|"ShowFileSegmentShowData"|"ShowFileSegmentLocalSettings"|"ReadOnly"|"IgnoreIconForTextAlign"|"KeyRepeatEnabled"|"ShowFileSegmentOutputStations"|"AutoNextCell"|"TextVertical"|"DependsOnLinkedObject"|"ShowFileSegmentDmxProtocols"|"TextAutoAdjust"|"SelectionOnFocusOnly"|"TextUniform"|"TargetIsAppearance"|"ShowNumber"|"DirectCommand"|"AvoidScroll"|"DirectQuotation"|"ShowKeyboardButton"|"Rounded"|"InteractWithCommandline"|"Secret"|"IndicatorBarEnabled"|"Visible"|"TargetIsScribble"|"SetPropertyOnlyOnTextChange"|"ShowLeftIcon"|"CanCoExistWithModal"|"CanBeEmbedded"|"ShowRightIcon"|"UserVisible"|"CalledFromCmdline"|"ShowAdditionalInfo"|"Enabled"|"EditTitlebar"|"ShowLeftScribble"|"Interactive"|"ShowRightScribble"|"Transparent"|"AllowBlocks"|"BlockClickThru"|"SkipTextIfIconExists"|"UserInteracted"|"IsMidiOut"|"ForceSmallMode"|"ItemIndividualCorners"|"State"|"HasHover"|"ShowVisibleDay"|"Separator"|"AutoCloseOnInput"|"HasPressedAnimation"|"ContentDriven"|"WantsModal"|"ReadOnly"|"ContentWidth"|"ContentHeight"|"ShowLineNumbers"|"AutoClose"|"ForceContentMin"|"ShowWhiteSpace"|"AutoCloseOnOverlay"|"HighlightCurrentLine"|"WantsNumericRedirect"|"IndirectEdit"|"CloseOnEscape"|"NewlineWithSpaces"|"ScrollChangesSelection"|"ForceCursor"|"IncludeTarget"|"InitialSaveEditTarget"|"EditTargetHasChanged"|"IgnoreBackdropPadding"|"MixInBackColorFromParent"|"FilterByManufacturer"|"ReactToPreview"|"PanScrollArea"|"StayAlwaysVisible"|"VisualisableScrollV"|"FilterByName"|"ScrollCellAutomatic"|"PanScroll"|"RelativeToDisplay"|"VisualisableScrollH"|"ScrollCellAutomaticWithOffset"|"ResetChildrenSize"|"EnterToExecute"|"IgnoreRequestedSize"|"ForceEncoderBar"|"SuppressOverlayAutoClose"|"FilterByDescription"|"FilterByUsedOnly"|"AdjustInitialPosition"|"IsClosing"|"TextShadow"|"IsMainBuddy"|"UpdateSettingsVisibility"|"FilterByMode"|"UseSimplifiedResize"|"InitialSaveEditTarget"|"BigMode"|"DriveReset"|"EditTargetHasChanged"|"AutoCreateFromProperties"|"OverrideKeybSC"|"UseEditorTarget"|"SuppressModeSwitch"|"ReactToPreview"|"ForceHideCategories"|"ScreenEncoder"|"ReactToEdit"|"UseDynamicIndicatorColor"|"OnlyVisible"|"IsWorldCoordinateSystemActive"|"ResetIfUntargeted"|"TryFitIntoSecondary"|"HasFocus"|"IsCameraFocusOnSelectedItem"|"EditAllowedDelete"|"Inverted"|"HideFocusFrame"|"ReactToEdit"|"StealFocusAfterSelect"|"Content"|"CmdlineInteraction"|"DrawShortcutInfo"|"TryAvoidZeroes"|"TitleButtonBool"|"TargetCmdlineInteraction"|"TryFitMainIfContentDriven"|"VisibleOnlyInAlpha"|"VisibleOnlyInBeta"|"EditAllowedAdd"|"SeparatorSupport"|"VisibleOnlyInRelease"|"ModifyTextureLayout"|"CreateAndEdit"|"ClickNearest"|"AutoClose"|"AddTargets"|"VisibleInAlpha"|"ProvideEmpty"|"Features"|"ObserveSelectionChange"|"MixPercentAndHexDecModesAllowed"|"VisibleInBeta"|"FeatureGroups"|"AllChannelSets"|"VisibleInRelease"|"FeatureGroupsOnly"|"ShowFullSettings"|"Toggle"|"ForceFocusOnChange"|"ShowLabel"|"ShowCSHelp"|"DrawInbetweenValues"|"ValueAutoAdjust"|"ShowValue"|"DataAsIs"|"AutoHide"|"WorkWithGrid"|"IndirectEdit"|"IsScribbleNew"|"DirectProperty"|"IsAppearanceNew"|"DefaultAction"|"CharAction"|"Undo"|"ChangeDestination"|"SmallResizeArea"|"ValueTextShadow"|"HiglightActiveCue"|"WorkWithGrid"|"IgnoreActiveForEnums"|"DimmerCueOnly"|"Auto"|"ShowOldVersions"|"UseCommandlineClick"|"SetIconAsActiveInactive"|"EditNewObject"|"ExclusivePropertyChange"|"UseTabRegistry"|"NoEmptyNames"|"UseGridColor"|"PositionBeneathFinger"|"MixInBackColorFromParentRecursive"|"DefaultAction"|"TrackEdit"|"ExpandContent"|"DefaultMarginOnBorders"|"TrackWorld"|"EncoderUseDisplay"|"SmallMode"|"ShowSelectionCount"|"UseDefaultValue"|"UseComposedText"|"ShowAdditionalInfo"|"ForceFastFade"|"TextChangeOnEnter"|"AutoScrollToEnd"|"AutoEnabled"|"NoEmptyNames"|"CloseProhibited"|"AllowAddContent"|"DisplayLevel"|"AllowAddNewline"|"ReactToRecipeEdit"|"ShowUnpatchedOnly"|"ScrollOpposite"|"AllowedInvisible"|"AllowMergeChildren"|"ShowManualCueSelection"|"ForceCursor"|"AllowEdit"|"ContentChanged"|"PrintCurrentValue"|"DirectQuotation"|"ReactToRecipeEdit"|"LongPressVK"|"CanProvideUiGridSelection"|"AllowFilterContent"|"AutoCloseAllowed"|"PrintMaxValue"|"FilterBlockUIEnabled"|"GapsForExpanded"|"UseUserProfileSettings"|"CloseOnClick"|"ScrollOutEnabled"|"VScrollOnHeader"|"PrimaryHasFocus"|"ConvertCursorToTabAtBoundaries"|"IsInExport", property_value: YesNo|boolean)
---@overload fun(property_name: "DrawGradient"|"AllIndexesCollected"|"AutoSetWindowSettings"|"IsScribbleAvailable"|"IsAppearanceAvailable"|"FadeEncoder"|"CheckForScreenEncoders"|"UseSpecialTimezone"|"IsNoteAvailable"|"Expanded"|"ChangeDestination"|"IsPlaying"|"AllowSorting"|"ScribbleIsEmpty"|"Blink"|"IsCloneDestination", property_value: boolean)
---@overload fun(property_name: "ChangeActive", property_value: fun(childName: string) : boolean)
---@overload fun(property_name: "Solve"|"CallP1"|"OnTitleClick"|"StoreP2"|"Close"|"CallP2"|"StoreP1"|"OnTitleClick"|"OnTitleClick"|"CloseConfirm"|"StoreP3"|"CloseCancel"|"CallP3"|"StoreP4"|"CallP4", property_value: fun(dummyStr: string) : boolean)
---@overload fun(property_name: "OnPatchToClicked"|"OnUniverseUpClicked"|"OnUnpatchClicked"|"OnUniverseDownClicked", property_value: fun(dummyStr: string, button: MouseButtonTypes, X: integer, Y: integer) : boolean)
---@overload fun(property_name: "OnBreakSelected"|"OnBreakPatched"|"OnDBObjectSelected"|"OnAddressSelected", property_value: fun(dummyStr: string, column: integer, row: integer) : boolean)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "Clear", property_value: fun(dummyString: string) : boolean)
---@overload fun(property_name: "ShowMessage"|"HideMessage", property_value: fun(message: string) : boolean)
---@overload fun(property_name: "ChangeText", property_value: fun(newTextStr: string) : boolean)
---@overload fun(property_name: "SetPrompt", property_value: fun(prompt: string) : boolean)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "MoveStart"|"OnListRefDone"|"UrlChanged"|"Scrolled"|"ProgressChanged"|"StatusChanged"|"TooltipChanged"|"OnCreateNewAppearance"|"MoveStart"|"ResizeEnd"|"ScrolledToEndV"|"PathChanged"|"OnUserProfileChanged"|"FilterChanged"|"Execute"|"ResizeStart"|"Execute"|"TextChanged"|"DescriptionChanged"|"LassoFinished"|"OnWrongChar"|"OnScreenPushed"|"ScribbleTargetChanged"|"OnCreateNewAppearance"|"OnCreateNewScribble"|"AppearanceTargetChanged", property_value: fun(str: string))
---@overload fun(property_name: "TimecodeForward"|"OpenVK"|"TimecodeStop"|"SelectAll"|"TimecodePlay"|"TimecodePrevMarker"|"OnFunction"|"DeSelect"|"TimecodeNextMarker"|"SetCursorToEnd"|"SelectionCopy"|"SelectionCut"|"SelectionPaste"|"TimecodeAddEvent"|"OnFixtureSourceChanged"|"TimecodeAddMultiEvents"|"TimecodeAddTimeRange"|"SetUrlA"|"TimecodeAddTimeMarker"|"GoBack"|"OnCreateNewAppearance"|"GoFwd"|"CheckAutoClose"|"Reload"|"OnNavigate"|"RequestMemUsage"|"OnCheckSubPoolSelector"|"OnInput"|"ApplyScribble"|"SetDateToday"|"OnState"|"RevertScribble"|"SetTimeNow"|"OnSelectDataPool"|"OnCommand"|"OnCreateNewScribble"|"DeleteFilterItem"|"OnTitle"|"ResetMouse"|"AddFilterItem"|"OnCollectAllIndexes"|"SetToTop"|"DeleteClicked"|"ScrollPageDown"|"Play"|"OnFocusLost"|"Undo"|"AutoScroll"|"TBDeleteAll"|"ClearScribble"|"Redo"|"TBLoadDefaults"|"Pause"|"ClearSelection"|"OnApplyColorToCurves"|"SetText"|"Stop"|"InsertText"|"ClearText"|"DeleteOld"|"OnToolOperate"|"SelectAllRows"|"SaveEditTarget"|"ScrollAction"|"ClearFilter"|"OnClearCmdline"|"RevertEditTarget"|"MoveStart"|"ToggleListRef"|"ExpandAll"|"ResizeEnd"|"ScrollToEnd"|"SetCursorToEnd"|"OnSelectedTreeItem"|"SaveToDefault"|"OnScrolledTreeItem"|"LoadFromDefault"|"KeyPress"|"SelectedFixture"|"SaveEditTarget"|"ResizeStart"|"MoveStart"|"SelectedManufacturer"|"Context"|"RememberSelection"|"RevertEditTarget"|"MapClicked"|"InitGrids"|"Context"|"UpdateEncoderBar"|"TabChanged"|"OnSpecialButtonClicked"|"OnExpandAll"|"EnumClicked"|"OnCollapseAll"|"OnExpandSelected"|"Search"|"OnClearSelection"|"OnStageChanged"|"SelectAll"|"SelectNothing"|"OnDataPoolChanged"|"OnSetSelectorVisibility"|"SwitchExpansion"|"OnCollapseAll"|"OnZoomToFit"|"OnSetRecalcCenterOfGravity"|"FunctionSelectorChanged"|"EncoderReadoutSelectorChanged"|"OnEditCurrentLayout"|"SetPath"|"DeleteSelectedFiles"|"SetFilter"|"GoUp"|"SelectFirstFile"|"ScrollToFirstFile"|"ProgressChanged"|"OnPatchToNextFree"|"OnSwipeMenu"|"OnMoveToUniverse"|"SGResizeStart"|"SGResizeEnd"|"OpenAtFilter"|"OnSwipeMenu"|"ToggleAtFilter"|"OnPatchToClicked"|"OnShowUnpatchedClicked"|"SGResizeStart"|"SGResizeEnd"|"SetPlus"|"MeasureColor"|"SetMinus"|"DarkCalibrate"|"FindDevice"|"ShowAnimation"|"ResetView"|"ZoomIn"|"ZoomOut"|"ChangedActiveTab"|"TimecodePause"|"TimecodeBackward"|"TimecodeRecord", property_value: fun(str: string) : boolean)
---@overload fun(property_name: "MouseUp"|"Clicked"|"MouseDown"|"DoubleClicked"|"MouseDownHold", property_value: fun(str: string, Button: MouseButtonTypes, X: integer, Y: integer))
---@overload fun(property_name: "ResizeMove"|"Move"|"Move", property_value: fun(str: string, DeltaX: integer, DeltaY: integer))
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "MouseOverHold"|"MouseEnter"|"MouseUpLeft"|"MouseUpRight"|"ClickedLeft"|"ClickedRight"|"MouseDownLeft"|"MouseDownRight"|"MouseLeave", property_value: fun(str: string, X: integer, Y: integer))
---@overload fun(property_name: "MoveEnd"|"MoveEnd"|"OnVisible", property_value: fun(str: string, bool: boolean))
---@overload fun(property_name: "MoveEnd"|"ResizeEnd", property_value: fun(str: string, bool: boolean) : boolean)
---@overload fun(property_name: "OnBeforeEdit"|"OnAfterEdit"|"OnSelectionAfterCmd"|"SelectionChanged"|"UndoRedoChanged", property_value: fun(str: string, int1: integer, int2: integer))
---@overload fun(property_name: "SGResizeMove"|"ResizeStart"|"Move"|"SGResizeMove"|"SelectCell"|"SelectRange"|"Resize"|"ResizeMove"|"Move", property_value: fun(str: string, int1: integer, int2: integer) : boolean)
---@overload fun(property_name: "TabChanged", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean))
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "TabClickedOnCurrent"|"OnSelectedItem", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean))
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "OnClick"|"ActionSetPriority"|"HardkeyMouseUp"|"HardkeyMouseDown"|"ReloadCamera"|"OnClick"|"FactoryDefaults"|"RotateToCircleCenter"|"Rotate90ToLine"|"ResetUnusedAxis"|"OnClick"|"ReloadRenderQuality"|"ResetRotation"|"Oops"|"ReloadCamera"|"ResetPosition"|"OnShow3dSettings"|"Show3DSettings"|"ResetCamera"|"CenterPosition"|"AnalyzeMeshPool"|"ArrangePosition"|"SelectionToGrid", property_value: fun(str: string, int1: integer, int2: integer, int3: integer) : boolean)
---@overload fun(property_name: "GestureClick"|"GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer))
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "OnCellMouseDoubleClicked"|"OnCellMouseDown"|"OnCellMouseDownHold"|"OnCellMouseUp"|"OnCellMouseClicked", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer, int5: integer))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "OnSelectedColumn"|"OnSelectedRow"|"MemUsageUpdated"|"OnTargetChanged"|"OnTargetChanged"|"OnSelectedItem", property_value: fun(str: string, int: integer))
---@overload fun(property_name: "SortByColumn"|"AddSelectedLines"|"OnChar"|"ScrollVertical"|"ScrollHorizontal"|"ReTriggerInit"|"ChangeTarget"|"SetFPSLimit"|"OnChar"|"ReTriggerInit"|"AddSelectedFixtures"|"ScrollToRow"|"ClearGrid"|"GridMoveUp"|"GridMoveDown"|"GridCut"|"ChangeTarget"|"GridCopy"|"GridPaste"|"GridAdd"|"GridDelete"|"SelectRow"|"GridFillUp"|"JumpToNextLine"|"AddRow"|"SelectionChanged"|"GridUnify"|"JumpToPreviousLine"|"AddMissingLines"|"SelectColumn", property_value: fun(str: string, int: integer) : boolean)
---@overload fun(property_name: "KeyDown"|"KeyUp", property_value: fun(str: string, keyCode: VirtualKeyCode, bool1: boolean, bool2: boolean, bool3: boolean))
---@overload fun(property_name: "ForceScale"|"Seek", property_value: fun(str: string, num: number) : boolean)
---@overload fun(property_name: "FocusLost"|"FocusGet", property_value: fun(str: string, obj1: Object, obj2: Object))
---@overload fun(property_name: "OnSetEditTarget"|"OnSetEditTarget"|"OnSetEditTarget"|"LinkedObjectChanged"|"OnLoad", property_value: fun(str: string, obj: Object))
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "TouchUpdate"|"TouchStart"|"TouchEnd", property_value: fun(str: string, pointID: integer, X: integer, Y: integer))
---@overload fun(property_name: "OnUpdateTitle"|"OnUpdateTitle", property_value: fun(str: string, str: string))
---@overload fun(property_name: "CharInput", property_value: fun(str: string, utf32Char: integer))
---@overload fun(property_name: "Changed", property_value: fun(str: string, value: integer))
---@overload fun(property_name: "Set", property_value: fun(str: string, value: integer) : boolean)
---@overload fun(property_name: "OpenSequenceFilter"|"FlipLeftRight"|"OpenGroupFilter"|"OpenPresetFilter"|"SetText"|"ObtainCurrentCue"|"DoReset"|"AddText"|"InitTargetList"|"InitFirst"|"DoClone"|"InsertText"|"OpenWorldFilter"|"SelectFirst"|"OpenLayoutFilter"|"ChangeCloningViewMode"|"AllItemsToAll"|"AllItemsToNone", property_value: fun(text: string) : boolean)
---@overload fun(property_name: "ShowFileSegmentsMask"|"OptionHeight"|"State"|"SelectedRow"|"SelectedColumn"|"Distance"|"ItemSize"|"Hour"|"VisibleItemCount"|"Minute"|"AutoFitColumn"|"FrameWidth"|"Second"|"SlotIndex"|"Day"|"GridVersion"|"MaxTextLength"|"Priority"|"Direction"|"Year"|"Selector"|"AutoCloseValue"|"UiGroupId"|"UndoCount"|"RedoCount"|"PatchOffset"|"FilterMask"|"VisibleFixturesCount"|"SubDestination"|"HeadLineDimension"|"ButtonDimension"|"SlotDimension"|"ColorIndicatorHeight"|"MaxValue"|"MinValue"|"MinCellSize"|"LineHeightAdd"|"IgnoreChildren"|"BigModeColumns"|"LineSpacing"|"TitleButtonUInt64"|"MaxValue"|"BigModeRows"|"DelimiterSize"|"ActiveSource"|"TitleButtonInt64"|"TitleButtonPopup"|"GridDelta"|"LabelAreaHeight"|"ExecFrom"|"ForceIntensity"|"FixtureCount"|"ExecBarToDraw"|"FirstRow"|"DefaultMargin"|"LastRow"|"Columns"|"ExecutorIndex"|"Rows"|"BreakIdx"|"CellWidth"|"CellHeight"|"PatchOffset"|"ExecutorIndex"|"BlockWidth"|"BlockHeight"|"ExecutorIndex"|"RasterHeight"|"FrameThickness"|"RasterWidth"|"ScrollCellFrameThickness"|"SpecialExecOffset"|"LevelDistance"|"IncrementFactor"|"ColumnResizeMaxDeviation"|"Mask"|"LevelLimit"|"Mask"|"Page"|"Border", property_value: integer)
---@overload fun(property_name: "Value"|"EncoderResolution"|"IconScale"|"CurrentFps"|"Progress"|"ItemPlacementOffsetFactorH"|"ScaleAll"|"RatioAll"|"ItemPlacementOffsetFactorV", property_value: number)
---@overload fun(property_name: "DataType"|"SelectionType"|"CellType"|"ToolTip"|"SettingsType"|"HelpTopic"|"ReferencedTitleButton"|"ItemType"|"DirectPrefix"|"Cursor"|"TargetPath"|"InitialTab"|"System"|"InitialSubTab"|"ItemFilter"|"DefaultTitle"|"EditEncoderBar"|"Content"|"ControlEncoderBar"|"FixtureName"|"Property"|"EditEncoderBar"|"ControlEncoderBar"|"ForcedInitialTab"|"BuddyGroupId"|"Filter"|"Property"|"System"|"SignalValue"|"SignalValueHold"|"PrivacyPolicyUrl"|"Property"|"FilterComposed"|"Value"|"System"|"TrademarksUrl"|"Value"|"ReleaseNotesUrl"|"AppearanceSourceClassName"|"Destination"|"TargetPropertyName"|"TextLeftCorner"|"EmptyName"|"System"|"InsertType"|"LedToken"|"ActiveChild"|"Property"|"System"|"CurrentSelectedShowFile"|"Property"|"Property"|"FuzzyFilter"|"FuzzyFilterExcludeEnd"|"EditEncoderBar"|"BaseFilter"|"ImportOptions"|"WarningTooltip"|"Value"|"SelectedFile"|"SwipeMenu"|"StrContext"|"BarText"|"AuxProperty"|"Property"|"VKTitleHint"|"AdditionalInfo"|"Property"|"DummyComposedText"|"VKPluginName"|"SwipeMenu"|"Destination"|"Prompt"|"Filter"|"EmptyText"|"Message"|"Property"|"FixtureToMeasure"|"DirectPrefix"|"Text", property_value: string)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "OptionAreaMargin"|"Margin"|"ContentAreaMargin"|"LabelAreaMargins"|"ValueAreaMargins"|"Anchors"|"Padding", property_value: {left: integer, right: integer, top: integer, bottom: integer})
---@overload fun(property_name: "WindowRect"|"AbsRect"|"AbsClientRect", property_value: {left: number, right: number, top: number, bottom: number})
function MacrolineEdit:SetPrompt(property_name, property_value) end