---@meta

---@class ColorThemeContent: NamedObj Base class for all elements within the ColorTheme
---@field AutoGenerated integer
---@field Unmatched integer
local ColorThemeContent = {
    AutoGenerated="No",
    Unmatched="No"
}
---@return "ColorThemeContent"
function ColorThemeContent:GetClass() end
---@return "Object"
function ColorThemeContent:GetChildClass() end
---@overload fun(name: "IgnoreNetwork"|"StructureLocked"|"SystemLocked"|"Lock"|"Index"|"Count"|"No", role: nil): integer
---@overload fun(name: "Name"|"Note", role: nil): string
---@overload fun(name: "UserExpanded", role: nil): integer
---@overload fun(name: "FaderEnabled"|"Owned", role: nil): boolean
---@overload fun(name: "Hidden", role: nil): integer
---@overload fun(name: "DependencyExport", role: nil): string
---@overload fun(name: "MemoryFootprint"|"AutoGenerated"|"Unmatched", role: nil): integer
---@overload fun(name: "IgnoreNetwork"|"StructureLocked"|"SystemLocked"|"Lock"|"Index"|"Count"|"No"|"Name"|"Note"|"UserExpanded"|"FaderEnabled"|"Owned"|"Hidden"|"DependencyExport"|"MemoryFootprint"|"AutoGenerated"|"Unmatched", role: Enums.Roles): string
---@overload fun(name: integer, role: nil): Object
function ColorThemeContent:Get(name, role) end
