---@meta

---@class XKeysViewExecutorBar: ExecutorBarXKeys
local XKeysViewExecutorBar = {}
---@return "XKeysViewExecutorBar"
function XKeysViewExecutorBar:GetClass() end
---@return "UILayoutGrid"
function XKeysViewExecutorBar:GetChildClass() end
---@generic T : XKeysViewExecutorBar
---@param class `T`
---@return boolean
function XKeysViewExecutorBar:IsClass(class) end
---@generic T : ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|PlaybackViewExecutorBar|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|ResultPoolWindow|RunningPlaybacksWindow|CommandLineWindow|AllPoolWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid
---@param index integer
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(index: integer, class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(index: integer, class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(index: integer, class: "SplitView", undo: Undo?): SplitView
---@overload fun(index: integer, class: "Drawable", undo: Undo?): Drawable
---@overload fun(index: integer, class: "Overlay", undo: Undo?): Overlay
---@overload fun(index: integer, class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(index: integer, class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(index: integer, class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(index: integer, class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(index: integer, class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(index: integer, class: "Bar", undo: Undo?): Bar
---@overload fun(index: integer, class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(index: integer, class: "ExecutorBarXKeys", undo: Undo?): ExecutorBarXKeys
---@overload fun(index: integer, class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(index: integer, class: "Window", undo: Undo?): Window
---@overload fun(index: integer, class: "PoolWindow", undo: Undo?): PoolWindow
---@overload fun(index: integer, class: "AllExecDisplay", undo: Undo?): AllExecDisplay
---@overload fun(index: integer, class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(index: integer, class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(index: integer, class: nil, undo: Undo?): UILayoutGrid
function XKeysViewExecutorBar:Create(index, class, undo) end
---@generic T : ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|PlaybackViewExecutorBar|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|ResultPoolWindow|RunningPlaybacksWindow|CommandLineWindow|AllPoolWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(class: "UILayoutGrid", undo: Undo?, count: integer?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?, count: integer?): AutoLayout
---@overload fun(class: "SplitView", undo: Undo?, count: integer?): SplitView
---@overload fun(class: "Drawable", undo: Undo?, count: integer?): Drawable
---@overload fun(class: "Overlay", undo: Undo?, count: integer?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?, count: integer?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?, count: integer?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?, count: integer?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?, count: integer?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?, count: integer?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?, count: integer?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?, count: integer?): ExecutorBar
---@overload fun(class: "ExecutorBarXKeys", undo: Undo?, count: integer?): ExecutorBarXKeys
---@overload fun(class: "GlWindowBase", undo: Undo?, count: integer?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?, count: integer?): Window
---@overload fun(class: "PoolWindow", undo: Undo?, count: integer?): PoolWindow
---@overload fun(class: "AllExecDisplay", undo: Undo?, count: integer?): AllExecDisplay
---@overload fun(class: "PoolLayoutGrid", undo: Undo?, count: integer?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?, count: integer?): UiScreen
---@overload fun(class: nil, undo: Undo?, count: integer?): UILayoutGrid
function XKeysViewExecutorBar:Append(class, undo, count) end
---@generic T : ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|PlaybackViewExecutorBar|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|ResultPoolWindow|RunningPlaybacksWindow|CommandLineWindow|AllPoolWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(class: "SplitView", undo: Undo?): SplitView
---@overload fun(class: "Drawable", undo: Undo?): Drawable
---@overload fun(class: "Overlay", undo: Undo?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(class: "ExecutorBarXKeys", undo: Undo?): ExecutorBarXKeys
---@overload fun(class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?): Window
---@overload fun(class: "PoolWindow", undo: Undo?): PoolWindow
---@overload fun(class: "AllExecDisplay", undo: Undo?): AllExecDisplay
---@overload fun(class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(class: nil, undo: Undo?): UILayoutGrid
function XKeysViewExecutorBar:Acquire(class, undo) end
---@generic T : ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|PlaybackViewExecutorBar|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|ResultPoolWindow|RunningPlaybacksWindow|CommandLineWindow|AllPoolWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(class: "SplitView", undo: Undo?): SplitView
---@overload fun(class: "Drawable", undo: Undo?): Drawable
---@overload fun(class: "Overlay", undo: Undo?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(class: "ExecutorBarXKeys", undo: Undo?): ExecutorBarXKeys
---@overload fun(class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?): Window
---@overload fun(class: "PoolWindow", undo: Undo?): PoolWindow
---@overload fun(class: "AllExecDisplay", undo: Undo?): AllExecDisplay
---@overload fun(class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(class: nil, undo: Undo?): UILayoutGrid
---@deprecated use "Acquire" instead
function XKeysViewExecutorBar:Aquire(class, undo) end
---@generic T : ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|PlaybackViewExecutorBar|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|ResultPoolWindow|RunningPlaybacksWindow|CommandLineWindow|AllPoolWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid
---@param index integer
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(index: integer, class: "UILayoutGrid", undo: Undo?, count: integer?): UILayoutGrid
---@overload fun(index: integer, class: "AutoLayout", undo: Undo?, count: integer?): AutoLayout
---@overload fun(index: integer, class: "SplitView", undo: Undo?, count: integer?): SplitView
---@overload fun(index: integer, class: "Drawable", undo: Undo?, count: integer?): Drawable
---@overload fun(index: integer, class: "Overlay", undo: Undo?, count: integer?): Overlay
---@overload fun(index: integer, class: "ShadedOverlay", undo: Undo?, count: integer?): ShadedOverlay
---@overload fun(index: integer, class: "BaseInput", undo: Undo?, count: integer?): BaseInput
---@overload fun(index: integer, class: "GenericImport", undo: Undo?, count: integer?): GenericImport
---@overload fun(index: integer, class: "TextEdit", undo: Undo?, count: integer?): TextEdit
---@overload fun(index: integer, class: "NoteTextEdit", undo: Undo?, count: integer?): NoteTextEdit
---@overload fun(index: integer, class: "Bar", undo: Undo?, count: integer?): Bar
---@overload fun(index: integer, class: "ExecutorBar", undo: Undo?, count: integer?): ExecutorBar
---@overload fun(index: integer, class: "ExecutorBarXKeys", undo: Undo?, count: integer?): ExecutorBarXKeys
---@overload fun(index: integer, class: "GlWindowBase", undo: Undo?, count: integer?): GlWindowBase
---@overload fun(index: integer, class: "Window", undo: Undo?, count: integer?): Window
---@overload fun(index: integer, class: "PoolWindow", undo: Undo?, count: integer?): PoolWindow
---@overload fun(index: integer, class: "AllExecDisplay", undo: Undo?, count: integer?): AllExecDisplay
---@overload fun(index: integer, class: "PoolLayoutGrid", undo: Undo?, count: integer?): PoolLayoutGrid
---@overload fun(index: integer, class: "UiScreen", undo: Undo?, count: integer?): UiScreen
---@overload fun(index: integer, class: nil, undo: Undo?, count: integer?): UILayoutGrid
function XKeysViewExecutorBar:Insert(index, class, undo, count) end
---@generic T : ScrollContainer|Dialog|UIGridConfigLayout|TitleAutoLayout|StepControl|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|SwipeMenuOverlay|RecurringOverlay|NotificationArea|ColorInput|Popup|TextInput|NumericInput|ImageInput|ViewInput|UIDMXPatch|InsertFixturesWizard|CopyStoreCueMessageBoxBase|GenericAssignmentInput|FixtureTypeImport|CloneAtFilterSelector|OSMidiSelect|DatumInput|TimezoneInput|XlrPortInput|MessageBox|EncoderOverlay|PatchToOverlay|GenericContext|GenericEditorOverlay|HelpPopup|NetworkSpeedTestOverlay|ColorMeasurementOverlay|ContentOverlay|OffMenuOverlay|MainDialog|CommandLineHistory|PoolOverlay|MeshLineEdit|ObjectProperties|VirtualKeyboard|GraphicsEncoderBar|PlaybackViewExecutorBar|RecipeWindow|ContentWindow|StatusWindow|PhaserViewWindow|WindowTrackpad|WindowAgenda|SystemMonitorWindow|PlaybackViewWindow|ClockWindow|SequenceWindow|TimecodeWindow|CommandWingBarWindow|WindowInfo|LayoutView|WindowHelpViewer|SelectionViewWindow|ResultPoolWindow|RunningPlaybacksWindow|CommandLineWindow|AllPoolWindow|WindowEncoderBar|SpecialWindow|XKeysViewWindow|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|DialogTrackpad|UserPoolLayoutGrid|ScribblePoolLayoutGrid|GroupPoolLayoutGrid|ConfigurationPoolLayoutGrid|FilterPoolLayoutGrid|LayoutPoolLayoutGrid|ImagePoolLayoutGrid|RenderQualityPoolLayoutGrid|SmartViewPoolLayoutGrid|WorldPoolLayoutGrid|UniversePoolLayoutGrid|DataPoolLayoutGrid|SymbolPoolLayoutGrid|EncoderBarPoolLayoutGrid|GeneratorBitmapPoolLayoutGrid|GoboPoolLayoutGrid|GelPoolLayoutGrid|CameraPoolLayoutGrid|ViewPoolLayoutGrid|TimecodeSlotLayoutGrid|RunningPlaybacksPoolLayoutGrid|PresetPoolLayoutGrid|TimecodePoolLayoutGrid|PagePoolLayoutGrid|SequencePoolLayoutGrid|PluginPoolLayoutGrid|MeshPoolLayoutGrid|ViewBar|AppearancePoolLayoutGrid|MatricksPoolLayoutGrid|TagPoolLayoutGrid|QuickeyPoolLayoutGrid|MenuPoolLayoutGrid|SoundPoolLayoutGrid|VideoPoolLayoutGrid|GeneratorRandomPoolLayoutGrid|TimePoolLayoutGrid|MaterialPoolLayoutGrid|MacroPoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|BladeView|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "UILayoutGrid", undo: Undo?): UILayoutGrid
---@overload fun(class: "AutoLayout", undo: Undo?): AutoLayout
---@overload fun(class: "SplitView", undo: Undo?): SplitView
---@overload fun(class: "Drawable", undo: Undo?): Drawable
---@overload fun(class: "Overlay", undo: Undo?): Overlay
---@overload fun(class: "ShadedOverlay", undo: Undo?): ShadedOverlay
---@overload fun(class: "BaseInput", undo: Undo?): BaseInput
---@overload fun(class: "GenericImport", undo: Undo?): GenericImport
---@overload fun(class: "TextEdit", undo: Undo?): TextEdit
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: "Bar", undo: Undo?): Bar
---@overload fun(class: "ExecutorBar", undo: Undo?): ExecutorBar
---@overload fun(class: "ExecutorBarXKeys", undo: Undo?): ExecutorBarXKeys
---@overload fun(class: "GlWindowBase", undo: Undo?): GlWindowBase
---@overload fun(class: "Window", undo: Undo?): Window
---@overload fun(class: "PoolWindow", undo: Undo?): PoolWindow
---@overload fun(class: "AllExecDisplay", undo: Undo?): AllExecDisplay
---@overload fun(class: "PoolLayoutGrid", undo: Undo?): PoolLayoutGrid
---@overload fun(class: "UiScreen", undo: Undo?): UiScreen
---@overload fun(class: nil, undo: Undo?): UILayoutGrid
function XKeysViewExecutorBar:Find(class, undo) end
---@overload fun(property_name: "EncoderFunction", property_value: TimecodeEncoderFunction|EncoderFunction|PhaserEncoderFunction)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "Mode", property_value: ShowfileSelectorMode|GridModeAgenda|DatumMode|CalculatorMode)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "ForceScale", property_value: fun(str: string, num: number) : boolean)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "Settings", property_value: CloningWindowSettings|PSRPatchSheetSettings|ShowCreatorSettings)
---@overload fun(property_name: "OnSelectedItem", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean))
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "Direction", property_value: AutoLayoutScrollType)
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "ScrollEntity", property_value: ScrollParamEntity)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "WindowRect", property_value: {left: number, right: number, top: number, bottom: number})
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "EscModalResult", property_value: ModalResult)
---@overload fun(property_name: "RunningPlaybacks", property_value: integer[])
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "Direction", property_value: AutoLayoutScrollType)
---@overload fun(property_name: "Mode", property_value: CalculatorMode)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "CloneDestinationGrid"|"ScrollBuddy"|"CloneSourceGrid", property_value: CloneGrid)
---@overload fun(property_name: "Settings", property_value: CloningWindowSettings)
---@overload fun(property_name: "EditMixInColor"|"EditMixInNotOwnerColor"|"PoolColor"|"GridColor"|"LassoColor"|"SelectionColor"|"ColorLineNumberBackground"|"ColorLineNumberNormal"|"ResizeLineColor"|"ColorLineNumberSelected"|"ColorSelectedLineRect"|"PreviewMixInColor"|"DelimiterColor"|"EditMixInColor"|"EditMixInNotOwnerColor"|"TimeCursorColor"|"ActiveDelimiterColor"|"PoolColor"|"BlockerColor"|"PoolColor"|"PreviewMixInColor"|"IndicatorIconBackColor"|"ScrollCellFrameColor"|"SelectedRowBorder", property_value: Color)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "DMXMode"|"DmxMode", property_value: DMXMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "Mode", property_value: DatumMode)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FixtureFID"|"FixtureCID", property_value: EmptyAsZeroFID)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "EncoderFunction", property_value: EncoderFunction)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "FixedHeaders"|"NormalHeaders"|"FixedCells"|"NormalCells", property_value: Graphics.UIGrid.GridArea)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "Mode", property_value: GridModeAgenda)
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "Target"|"Target", property_value: Mesh)
---@overload fun(property_name: "EscModalResult", property_value: ModalResult)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "Target"|"EditTarget"|"Target"|"AppearanceTarget"|"CurrentUpdateObject"|"MainBuddy"|"ScribbleTarget"|"WorkingDestination"|"EditTarget"|"Target"|"Target"|"TargetObject"|"Context"|"Target"|"EditTarget"|"Target"|"Target"|"ScrollTarget"|"Target", property_value: Object)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Settings", property_value: PSRPatchSheetSettings)
---@overload fun(property_name: "EncoderFunction", property_value: PhaserEncoderFunction)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "PoolSettings"|"PoolSettings", property_value: PoolSettings)
---@overload fun(property_name: "SizeY"|"SizeY"|"SizeX"|"SizeX", property_value: PoolSizeFactor)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "RowReductionPolicy"|"ColReductionPolicy", property_value: ReductionPolicy)
---@overload fun(property_name: "ViewW"|"ViewH", property_value: RequestedSize)
---@overload fun(property_name: "ItemPlacementTypeV"|"ItemPlacementTypeH", property_value: ScrollItemPlacementType)
---@overload fun(property_name: "ScrollEntity", property_value: ScrollParamEntity)
---@overload fun(property_name: "AutoNextCellDirection"|"Type", property_value: ScrollType)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "Settings", property_value: ShowCreatorSettings)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "Mode", property_value: ShowfileSelectorMode)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "SelectionFrame"|"LockTexture"|"Lasso"|"TitleButtonIcon"|"GearTexture"|"CursorTexture"|"SelectionBackgroundTexture"|"ExpandedTexture"|"ContractedTexture"|"DelimiterTexture"|"SelectionFrame"|"BlockerTexture"|"ExpandedIcon"|"CollapsedIcon"|"TitleButtonIcon"|"SelectionFrame"|"SortAsc"|"IndicatorIcon"|"SortDesc", property_value: Texture)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "EncoderFunction", property_value: TimecodeEncoderFunction)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "Target"|"LinkedObject"|"TargetObject", property_value: UIObject)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "WindowSettings"|"SubWindowSettings"|"WindowSettings"|"WindowSettings"|"WindowSettings", property_value: WindowSettings)
---@overload fun(property_name: "AutoNextCell"|"ShowFileSegmentDmxProtocols"|"DependsOnLinkedObject"|"TargetIsAppearance"|"SelectionOnFocusOnly"|"TargetIsScribble"|"CanBeEmbedded"|"CalledFromCmdline"|"EditTitlebar"|"SearchFocusTestParent"|"IsMidiOut"|"ForceSmallMode"|"State"|"ShowVisibleDay"|"AutoCloseOnInput"|"WantsModal"|"ReadOnly"|"ShowLineNumbers"|"AutoClose"|"ShowWhiteSpace"|"AutoCloseOnOverlay"|"HighlightCurrentLine"|"CloseOnEscape"|"NewlineWithSpaces"|"ForceCursor"|"InitialSaveEditTarget"|"EditTargetHasChanged"|"ReactToPreview"|"FilterByManufacturer"|"FilterByName"|"ReactToEdit"|"VisualisableScrollV"|"StayAlwaysVisible"|"ScrollCellAutomatic"|"RelativeToDisplay"|"VisualisableScrollH"|"FilterByMode"|"ScrollCellAutomaticWithOffset"|"EnterToExecute"|"FilterByDescription"|"SmallResizeArea"|"FilterByUsedOnly"|"AdjustInitialPosition"|"IsMainBuddy"|"UpdateSettingsVisibility"|"UseSimplifiedResize"|"InitialSaveEditTarget"|"BigMode"|"DriveReset"|"EditTargetHasChanged"|"AutoCreateFromProperties"|"OverrideKeybSC"|"UseEditorTarget"|"SuppressModeSwitch"|"ReactToPreview"|"ForceHideCategories"|"ScreenEncoder"|"ReactToEdit"|"OnlyVisible"|"IsWorldCoordinateSystemActive"|"TryFitIntoSecondary"|"IsCameraFocusOnSelectedItem"|"EditAllowedDelete"|"Inverted"|"StealFocusAfterSelect"|"Content"|"CmdlineInteraction"|"TryAvoidZeroes"|"TitleButtonBool"|"TargetCmdlineInteraction"|"TryFitMainIfContentDriven"|"EditAllowedAdd"|"SeparatorSupport"|"CreateAndEdit"|"ModifyTextureLayout"|"AutoClose"|"AddTargets"|"ProvideEmpty"|"Features"|"ObserveSelectionChange"|"MixPercentAndHexDecModesAllowed"|"FeatureGroups"|"AllChannelSets"|"FeatureGroupsOnly"|"ShowFullSettings"|"IsScribbleNew"|"IsAppearanceNew"|"SearchFocusTestParent"|"HiglightActiveCue"|"DimmerCueOnly"|"ExclusivePropertyChange"|"NoEmptyNames"|"PositionBeneathFinger"|"MixInBackColorFromParentRecursive"|"ExpandContent"|"DefaultMarginOnBorders"|"EncoderUseDisplay"|"AutoScrollToEnd"|"NoEmptyNames"|"CloseProhibited"|"AllowAddContent"|"AllowAddNewline"|"ReactToRecipeEdit"|"ShowUnpatchedOnly"|"AllowMergeChildren"|"ShowManualCueSelection"|"AllowEdit"|"ContentChanged"|"CanProvideUiGridSelection"|"AllowFilterContent"|"FilterBlockUIEnabled"|"GapsForExpanded"|"UseUserProfileSettings"|"ScrollOutEnabled"|"VScrollOnHeader"|"PrimaryHasFocus"|"ConvertCursorToTabAtBoundaries"|"IsInExport"|"ShowFileSegmentShowData"|"ShowFileSegmentLocalSettings"|"ShowFileSegmentOutputStations", property_value: YesNo|boolean)
---@overload fun(property_name: "AutoSetWindowSettings"|"AllIndexesCollected"|"IsScribbleAvailable"|"IsAppearanceAvailable"|"UseSpecialTimezone"|"FadeEncoder"|"IsNoteAvailable"|"ChangeDestination"|"AllowSorting"|"IsCloneDestination"|"ScribbleIsEmpty", property_value: boolean)
---@overload fun(property_name: "OnTitleClick"|"CallP1"|"Solve"|"StoreP2"|"Close"|"CallP2"|"StoreP1"|"OnTitleClick"|"CloseConfirm"|"OnTitleClick"|"StoreP3"|"CloseCancel"|"CallP3"|"StoreP4"|"CallP4", property_value: fun(dummyStr: string) : boolean)
---@overload fun(property_name: "OnPatchToClicked"|"OnUniverseUpClicked"|"OnUnpatchClicked"|"OnUniverseDownClicked", property_value: fun(dummyStr: string, button: MouseButtonTypes, X: integer, Y: integer) : boolean)
---@overload fun(property_name: "OnAddressSelected"|"OnBreakPatched"|"OnDBObjectSelected"|"OnBreakSelected", property_value: fun(dummyStr: string, column: integer, row: integer) : boolean)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "LassoFinished"|"StatusChanged"|"ProgressChanged"|"OnScreenPushed"|"TooltipChanged"|"ScrolledToEndV"|"OnListRefDone"|"PathChanged"|"OnUserProfileChanged"|"FilterChanged"|"UrlChanged"|"Scrolled"|"Execute", property_value: fun(str: string))
---@overload fun(property_name: "TimecodeAddEvent"|"OnFixtureSourceChanged"|"TimecodeAddMultiEvents"|"TimecodeAddTimeRange"|"SetUrlA"|"TimecodeAddTimeMarker"|"GoBack"|"OnCreateNewAppearance"|"GoFwd"|"CheckAutoClose"|"OnNavigate"|"Reload"|"RequestMemUsage"|"OnCheckSubPoolSelector"|"OnInput"|"ApplyScribble"|"SetDateToday"|"OnState"|"RevertScribble"|"SetTimeNow"|"OnSelectDataPool"|"OnCommand"|"OnCreateNewScribble"|"DeleteFilterItem"|"OnTitle"|"AddFilterItem"|"OnCollectAllIndexes"|"SetToTop"|"DeleteClicked"|"ScrollPageDown"|"OnFocusLost"|"Undo"|"TBDeleteAll"|"Redo"|"TBLoadDefaults"|"ClearSelection"|"SetText"|"InsertText"|"ClearText"|"DeleteOld"|"OnToolOperate"|"SelectAllRows"|"SaveEditTarget"|"ScrollAction"|"ClearFilter"|"OnClearCmdline"|"RevertEditTarget"|"MoveStart"|"ToggleListRef"|"ExpandAll"|"ResizeEnd"|"ScrollToEnd"|"SetCursorToEnd"|"OnSelectedTreeItem"|"SaveToDefault"|"OnScrolledTreeItem"|"LoadFromDefault"|"KeyPress"|"SelectedFixture"|"SaveEditTarget"|"ResizeStart"|"ResizeStart"|"MoveStart"|"SelectedManufacturer"|"Context"|"ResizeEnd"|"RememberSelection"|"RevertEditTarget"|"MapClicked"|"InitGrids"|"Context"|"UpdateEncoderBar"|"TabChanged"|"OnSpecialButtonClicked"|"OnExpandAll"|"EnumClicked"|"OnCollapseAll"|"OnExpandSelected"|"Search"|"OnClearSelection"|"OnStageChanged"|"SelectAll"|"SelectNothing"|"OnDataPoolChanged"|"OnSetSelectorVisibility"|"SwitchExpansion"|"OnCollapseAll"|"OnZoomToFit"|"OnSetRecalcCenterOfGravity"|"FunctionSelectorChanged"|"EncoderReadoutSelectorChanged"|"OnEditCurrentLayout"|"SetPath"|"DeleteSelectedFiles"|"SetFilter"|"GoUp"|"SelectFirstFile"|"ScrollToFirstFile"|"OnPatchToNextFree"|"OnSwipeMenu"|"OnMoveToUniverse"|"SGResizeStart"|"SGResizeEnd"|"OpenAtFilter"|"OnSwipeMenu"|"ToggleAtFilter"|"OnPatchToClicked"|"OnShowUnpatchedClicked"|"SGResizeStart"|"SGResizeEnd"|"MeasureColor"|"DarkCalibrate"|"FindDevice"|"ResetView"|"ZoomIn"|"ZoomOut"|"ChangedActiveTab"|"TimecodePause"|"TimecodeBackward"|"TimecodeRecord"|"TimecodeForward"|"TimecodeStop"|"TimecodePlay"|"TimecodePrevMarker"|"TimecodeNextMarker"|"SelectionCopy"|"SelectionCut"|"SelectionPaste", property_value: fun(str: string) : boolean)
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "MoveEnd"|"ResizeEnd", property_value: fun(str: string, bool: boolean) : boolean)
---@overload fun(property_name: "OnSelectionAfterCmd"|"OnAfterEdit"|"UndoRedoChanged"|"OnBeforeEdit", property_value: fun(str: string, int1: integer, int2: integer))
---@overload fun(property_name: "ResizeStart"|"SGResizeMove"|"ResizeMove"|"Move"|"SGResizeMove"|"SelectCell"|"Resize"|"ResizeMove"|"Move", property_value: fun(str: string, int1: integer, int2: integer) : boolean)
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "OnSelectedItem", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean))
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "FactoryDefaults"|"RotateToCircleCenter"|"Rotate90ToLine"|"ResetUnusedAxis"|"OnClick"|"ReloadRenderQuality"|"ResetRotation"|"Oops"|"ReloadCamera"|"ResetPosition"|"OnShow3dSettings"|"Show3DSettings"|"ResetCamera"|"CenterPosition"|"AnalyzeMeshPool"|"ArrangePosition"|"SelectionToGrid"|"OnClick"|"ActionSetPriority"|"HardkeyMouseUp"|"HardkeyMouseDown"|"ReloadCamera"|"OnClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer) : boolean)
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "OnCellMouseDoubleClicked"|"OnCellMouseDown"|"OnCellMouseDownHold"|"OnCellMouseUp"|"OnCellMouseClicked", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer, int5: integer))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "MemUsageUpdated"|"OnTargetChanged"|"OnSelectedRow"|"OnSelectedColumn", property_value: fun(str: string, int: integer))
---@overload fun(property_name: "ReTriggerInit"|"ChangeTarget"|"SetFPSLimit"|"OnChar"|"ReTriggerInit"|"AddSelectedFixtures"|"ClearGrid"|"GridMoveUp"|"GridMoveDown"|"GridCut"|"ChangeTarget"|"GridCopy"|"GridPaste"|"GridAdd"|"GridDelete"|"SelectRow"|"GridFillUp"|"JumpToNextLine"|"AddRow"|"SelectionChanged"|"GridUnify"|"JumpToPreviousLine"|"AddMissingLines"|"ScrollToRow"|"SelectColumn"|"SortByColumn"|"AddSelectedLines"|"OnChar"|"ScrollVertical"|"ScrollHorizontal", property_value: fun(str: string, int: integer) : boolean)
---@overload fun(property_name: "ForceScale", property_value: fun(str: string, num: number) : boolean)
---@overload fun(property_name: "LinkedObjectChanged"|"OnSetEditTarget"|"OnSetEditTarget"|"OnSetEditTarget", property_value: fun(str: string, obj: Object))
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "OnUpdateTitle"|"OnUpdateTitle", property_value: fun(str: string, str: string))
---@overload fun(property_name: "OpenSequenceFilter"|"FlipLeftRight"|"OpenGroupFilter"|"DoReset"|"OpenPresetFilter"|"DoClone"|"InitTargetList"|"InitFirst"|"OpenWorldFilter"|"OpenLayoutFilter"|"ChangeCloningViewMode"|"AllItemsToAll"|"AllItemsToNone", property_value: fun(text: string) : boolean)
---@overload fun(property_name: "FrameThickness"|"RasterWidth"|"RasterHeight"|"ScrollCellFrameThickness"|"SelectedColumn"|"LevelDistance"|"UndoCount"|"RasterWidth"|"RedoCount"|"Hour"|"ColumnResizeMaxDeviation"|"PatchOffset"|"Minute"|"SelectedRow"|"AutoFitColumn"|"Second"|"FilterMask"|"Day"|"GridDelta"|"GridVersion"|"VisibleFixturesCount"|"LevelLimit"|"SubDestination"|"Priority"|"Year"|"MinCellSize"|"LineHeightAdd"|"IgnoreChildren"|"BigModeColumns"|"LineSpacing"|"ExecFrom"|"TitleButtonUInt64"|"BigModeRows"|"DelimiterSize"|"Selector"|"FixtureCount"|"ActiveSource"|"ExecBarToDraw"|"TitleButtonInt64"|"FirstRow"|"DefaultMargin"|"TitleButtonPopup"|"LastRow"|"Columns"|"Rows"|"BreakIdx"|"CellWidth"|"CellHeight"|"PatchOffset"|"ExecRowCount"|"BlockWidth"|"ExecColCount"|"BlockHeight"|"ShowFileSegmentsMask"|"RasterHeight", property_value: integer)
---@overload fun(property_name: "RunningPlaybacks", property_value: integer[])
---@overload fun(property_name: "CurrentFps"|"RatioAll"|"ScaleAll"|"ItemPlacementOffsetFactorV"|"ItemPlacementOffsetFactorH", property_value: number)
---@overload fun(property_name: "EditEncoderBar"|"SwipeMenu"|"CurrentSelectedShowFile"|"ControlEncoderBar"|"ForcedInitialTab"|"Destination"|"BuddyGroupId"|"Filter"|"FuzzyFilter"|"FuzzyFilterExcludeEnd"|"BaseFilter"|"PrivacyPolicyUrl"|"InitialTab"|"FixtureToMeasure"|"FilterComposed"|"InitialSubTab"|"TrademarksUrl"|"ReleaseNotesUrl"|"Value"|"SelectedFile"|"Destination"|"SwipeMenu"|"StrContext"|"TargetPropertyName"|"DefaultTitle"|"DataType"|"SelectionType"|"EmptyName"|"InsertType"|"CellType"|"EditEncoderBar"|"SettingsType"|"Content"|"ControlEncoderBar"|"FixtureName"|"Property", property_value: string)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "WindowRect", property_value: {left: number, right: number, top: number, bottom: number})
function XKeysViewExecutorBar:SetChildren(property_name, property_value) end