---@meta

---@class ColorDef: ColorThemeContent A definition of a RGBA color
---@field Name string
---@field RGBA UColor
---@field Used integer
local ColorDef = {
    RGBA="FFFFFFFF"
}
---@return "ColorDef"
function ColorDef:GetClass() end
---@return "Object"
function ColorDef:GetChildClass() end
---@return ColorDefGroup
function ColorDef:Parent() end
---@overload fun(name: "IgnoreNetwork"|"StructureLocked"|"SystemLocked"|"Lock"|"Index"|"Count"|"No", role: nil): integer
---@overload fun(name: "Name"|"Note", role: nil): string
---@overload fun(name: "UserExpanded", role: nil): integer
---@overload fun(name: "FaderEnabled"|"Owned", role: nil): boolean
---@overload fun(name: "Hidden", role: nil): integer
---@overload fun(name: "DependencyExport", role: nil): string
---@overload fun(name: "MemoryFootprint"|"AutoGenerated"|"Unmatched", role: nil): integer
---@overload fun(name: "Name", role: nil): string
---@overload fun(name: "RGBA", role: nil): UColor
---@overload fun(name: "Used", role: nil): integer
---@overload fun(name: "IgnoreNetwork"|"StructureLocked"|"SystemLocked"|"Lock"|"Index"|"Count"|"No"|"Name"|"Note"|"UserExpanded"|"FaderEnabled"|"Owned"|"Hidden"|"DependencyExport"|"MemoryFootprint"|"AutoGenerated"|"Unmatched"|"Name"|"RGBA"|"Used", role: Enums.Roles): string
---@overload fun(name: integer, role: nil): Object
function ColorDef:Get(name, role) end
