---@meta

---@class ItemCollect: GraphicsObject A container of UILayoutGrid configuration items (for rows or columns)
local ItemCollect = {}
---@return "ItemCollect"
function ItemCollect:GetClass() end
---@return "Item"
function ItemCollect:GetChildClass() end
---@generic T : ItemCollect
---@param class `T`
---@return boolean
function ItemCollect:IsClass(class) end
---@return UILayoutGrid
function ItemCollect:Parent() end
---@param index integer
---@return Item
function ItemCollect:Ptr(index) end
---@return Item[]
function ItemCollect:Children() end
---@return Item?
function ItemCollect:CurrentChild() end
---@overload fun(name: integer, role: nil): Item
function ItemCollect:Get(name, role) end
---@generic T : Item
---@param index integer
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(index: integer, class: nil, undo: Undo?): Item
function ItemCollect:Create(index, class, undo) end
---@generic T : Item
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(class: nil, undo: Undo?, count: integer?): Item
function ItemCollect:Append(class, undo, count) end
---@generic T : Item
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: nil, undo: Undo?): Item
function ItemCollect:Acquire(class, undo) end
---@generic T : Item
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: nil, undo: Undo?): Item
---@deprecated use "Acquire" instead
function ItemCollect:Aquire(class, undo) end
---@generic T : Item
---@param index integer
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(index: integer, class: nil, undo: Undo?, count: integer?): Item
function ItemCollect:Insert(index, class, undo, count) end
---@generic T : Item
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: nil, undo: Undo?): Item
function ItemCollect:Find(class, undo) end
---@generic T : Item|SampleTableView|Toolbar|UiFader|NotificationTitle|ProgressBar|DCRemoteInfo|UIGridCellBase|ScrollBar|UIGridFilterBlock|ScrollContainer|NotificationsWrapper|NotificationsGridScroller|Dialog|AutoLayout|SplitView|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|Overlay|TextEdit|ObjectProperties|VirtualKeyboard|Bar|GlWindowBase|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|AllExecDisplay|DialogTrackpad|PoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|UiScreen|BladeView|MainDialogContent|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|InfoNotesWrapper|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|LinearResizer|UIObjectFake|PropertyControl|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|LogoButton|UIGridButton|DeleteWindowButton|IndicatorButton|WarningInfoButton|EjectButton|DimmerWheelButton|CloseButton|SoundPoolTitleButton|FilterPoolTitleButton|TimecodePoolTitleButton|TimerPoolTitleButton|VideoPoolTitleButton|PluginPoolTitleButton|GelPoolTitleButton|TimecodeSlotPoolTitleButton|SequencePoolTitleButton|MacroPoolTitleButton|AllPoolTitleButton|ShowMoreButton|MouseButton|MessageCenterButton|TreeExpandButton|AgendaDayButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|SelectButton|RevertButton|PlaceHolderBase|LineEdit|ColorView|NotificationIcon|SensorView|DialogContainer|ScrollableItemList|ResizeCorner|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|NotificationText|TimecodeSlotInfo|TextView|TouchConfigurator|InfoNotesLabel|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|MainDialogDummy|EditorSubCategoryButton|CommandLineOutput|InfoNotesLevel|AllExecContent|TreeViewRows|SoundLevelView|PerformanceView|ColorTestView|EditorCategoryButton|InfoNotesGridScroller|TouchTarget|EditorBase|BladeViewButton|OutputTest|BaseSymbol|ColorPickBase|TreeViewRow|SignalView|ShaperTestView
---@param name string
---@param class `T`
---@return T
---@overload fun(name: string, class: "GraphicsObject"): GraphicsObject
---@overload fun(name: string, class: "UIObject"): UIObject
---@overload fun(name: string, class: "UILayoutGrid"): UILayoutGrid
---@overload fun(name: string, class: "Drawable"): Drawable
---@overload fun(name: string, class: "Button"): Button
---@overload fun(name: string, class: "TitleButton"): TitleButton
---@overload fun(name: string, class: "PoolTitleButton"): PoolTitleButton
---@overload fun(name: string, class: nil): Object
function ItemCollect:FindRecursive(name, class) end
---@overload fun(property_name: "Size", property_value: Graphics.FixedSize)
---@overload fun(property_name: "SizePolicy", property_value: LayoutSizePolicy)
---@overload fun(property_name: "MinSize", property_value: Graphics.SizeDescriptor)
---@overload fun(property_name: "RealSize", property_value: integer)
---@overload fun(property_name: "Size", property_value: Graphics.FixedSize)
---@overload fun(property_name: "MinSize", property_value: Graphics.SizeDescriptor)
---@overload fun(property_name: "SizePolicy", property_value: LayoutSizePolicy)
---@overload fun(property_name: "RealSize", property_value: integer)
function ItemCollect:SetChildren(property_name, property_value) end
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "Mode", property_value: GridModeAgenda|BlinkingButtonMode|ShowfileSelectorMode|DatumMode|CalculatorMode)
---@overload fun(property_name: "Focus", property_value: FocusPriority)
---@overload fun(property_name: "Settings", property_value: CloningWindowSettings|ShowCreatorSettings|PSRPatchSheetSettings)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "UserRights", property_value: UserRights)
---@overload fun(property_name: "TargetSound", property_value: Sound)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "InternalRole", property_value: Roles)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "MouseButtonType", property_value: MouseButtonTypes)
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Appearance", property_value: Appearance)
---@overload fun(property_name: "Direction", property_value: ToolbarScrollType|AutoLayoutScrollType)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "ChangeText", property_value: fun(newTextStr: string) : boolean)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "KeyCode", property_value: KeyboardCodes)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "FocusSearchPolicy", property_value: FocusSearchPolicy)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "EncoderType", property_value: EncoderType)
---@overload fun(property_name: "EncoderRing", property_value: EncoderRing)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "Changed", property_value: fun(str: string, value: integer))
---@overload fun(property_name: "Set", property_value: fun(str: string, value: integer) : boolean)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "ChangeActive", property_value: fun(childName: string) : boolean)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "EncoderFunction", property_value: TimecodeEncoderFunction|EncoderFunction|PhaserEncoderFunction)
---@overload fun(property_name: "UIToControl", property_value: SplitterH_LeftRight|SplitterV_TopBottom)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "SizePolicy", property_value: LayoutSizePolicy)
---@overload fun(property_name: "Size", property_value: Graphics.FixedSize)
---@overload fun(property_name: "BackOffset", property_value: ItemGroupPosition)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "ResizeMove", property_value: fun(str: string, AbsX: integer, AbsY: integer))
---@overload fun(property_name: "CharInput", property_value: fun(str: string, utf32Char: integer))
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "Drive", property_value: Drive)
---@overload fun(property_name: "TabChanged", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "ValueRole", property_value: ValueRole)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "Band", property_value: SoundValues)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "PolicyOnEnter", property_value: PolicyOnEnter)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "Property", property_value: EncoderGroupType)
---@overload fun(property_name: "Icons", property_value: Texture[])
---@overload fun(property_name: "IconsGrid", property_value: Gma3UI.IconsGrid)
---@overload fun(property_name: "IconsGridAnchors", property_value: Gma3UI.IconsGridAnchors[])
---@overload fun(property_name: "SetType", property_value: PropertyRadioButtonListSetType)
---@overload fun(property_name: "ExecProxy", property_value: Proxy)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "EnabledItems", property_value: PropertyRadioButtonListEnabledItems)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "Clear", property_value: fun(dummyString: string) : boolean)
---@overload fun(property_name: "SetPrompt", property_value: fun(prompt: string) : boolean)
---@overload fun(property_name: "Source", property_value: TimeCodeSource)
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "HotKey", property_value: HotKey)
---@overload fun(property_name: "RunningPlaybacks", property_value: integer[])
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "ValueAlignmentH"|"AlignmentH"|"IconAlignmentH"|"IconAlignmentH"|"TextAlignmentH"|"LogoIconAlignmentH"|"KeyboardIconAlignmentH", property_value: AlignmentH)
---@overload fun(property_name: "ValueAlignmentV"|"AlignmentV"|"IconAlignmentV"|"IconAlignmentV"|"TextAlignmentV"|"LogoIconAlignmentV"|"KeyboardIconAlignmentV", property_value: AlignmentV)
---@overload fun(property_name: "Appearance", property_value: Appearance)
---@overload fun(property_name: "Direction", property_value: AutoLayoutScrollType)
---@overload fun(property_name: "Mode", property_value: BlinkingButtonMode)
---@overload fun(property_name: "Mode", property_value: CalculatorMode)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "TriggerIndirectInitLevel"|"BlockLevel", property_value: ChangeLevel)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "ScrollBuddy"|"CloneDestinationGrid"|"CloneSourceGrid", property_value: CloneGrid)
---@overload fun(property_name: "Settings", property_value: CloningWindowSettings)
---@overload fun(property_name: "HighlightedColor"|"IconColor"|"SelectionColor"|"ColorLineNumberBackground"|"ColorLineNumberNormal"|"ProgIndicatorBackColor"|"ColorLineNumberSelected"|"ColorSelectedLineRect"|"OnColor"|"SelectedBackColor"|"KnobColorFlashedUp"|"OffColor"|"AlwaysOnColor"|"DisabledColor"|"HeadlineColor"|"SelectedIconColor"|"KnobColor"|"IndicatorBackColor"|"KnobColorFlashedDown"|"SlotColor"|"UpperColor"|"PreviewMixInColor"|"LowerColor"|"OnColor"|"SelectedBackColor"|"OffColor"|"TextShadowColor"|"AlwaysOnColor"|"SelectedTextColor"|"DisabledColor"|"EditMixInColor"|"EmptyBackColor"|"BorderColor"|"EditMixInNotOwnerColor"|"EmptyTextColor"|"IndicatorColor"|"MixInBackColor"|"RotateIconColor"|"DbgValueBackColor"|"DbgValueTextColor"|"ResizeLineColor"|"PreviewMixInColor"|"DefaultCellAltBackColor"|"EditMixInColor"|"DelimiterColor"|"BackColorFlashedDown"|"FixedBackColor"|"EditMixInNotOwnerColor"|"ActiveDelimiterColor"|"FixedTextColor"|"BackColor2"|"HeaderBackColor"|"IndicatorBack"|"HeaderAltBackColor"|"BackColorFlashedUp"|"ReadOnlyBackColor"|"HeaderTextColor"|"BlockerColor"|"SelectedBackColor"|"SelectedTextColor"|"NoCellBackColor"|"NonEmptyIndicatorColor"|"ReadOnlyAltBackColor"|"ReadOnlyTextColor"|"DefaultValueColor"|"DisabledColor"|"OnColor"|"FilterActiveColor"|"IndicatorIconBackColor"|"OffColor"|"GridColor"|"OverridesIndicatorBackColor"|"XYZTextColor"|"ValueTextColor"|"ChildFreeIconColor"|"ValueActiveTextColor"|"PoolColor"|"HasChildrenIconColor"|"SelectedTextColor"|"SelectionColor"|"HasSelectedChildrenIconColor"|"SelectedBackColor"|"FixedBackColor"|"ProgressColor"|"AdditionalInfoTextColor"|"DividerColor"|"BlinkBackColor"|"ProgIndicatorBackColor"|"SelectionColor"|"MessageColor"|"LevelColor"|"PeakColor"|"PoolColor"|"ScrollCellFrameColor"|"SelectedRowBorder"|"LevelColor"|"TriggerColor"|"KnobColor"|"NumberColor"|"UpperColor"|"MinorNumberColor"|"LowerColor"|"LassoColor"|"FaderLocked"|"GridColor"|"OverridesIndicatorBackColor"|"LowerPressedColor"|"SampleColor"|"UpperSampleColor"|"MatricksAreaActiveBackColor"|"RecipeEditColor"|"GridColor"|"TimeCursorColor"|"IconColor"|"IconHoverColor"|"SelectedIconColor"|"DeselectedIconColor"|"SensorColor"|"GridColor1"|"WarningColor"|"GridColor2"|"UpperColor"|"PeekColor"|"SignalColor"|"LowerColor"|"PoolColor"|"ActiveBackColor"|"ActiveTextColor"|"EditMixInBackColor"|"ActiveIconColor"|"EditMixInNotOwnerBackColor"|"BackColor"|"SelectedIconColor"|"TextColor"|"SelectedOptionTextColor"|"SelectedOptionBackColor", property_value: Color)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "DMXMode"|"DmxMode", property_value: DMXMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "Mode", property_value: DatumMode)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "Drive", property_value: Drive)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FixtureFID"|"FixtureCID", property_value: EmptyAsZeroFID)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "EncoderFunction", property_value: EncoderFunction)
---@overload fun(property_name: "Property", property_value: EncoderGroupType)
---@overload fun(property_name: "EncoderRing", property_value: EncoderRing)
---@overload fun(property_name: "EncoderType", property_value: EncoderType)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "Focus", property_value: FocusPriority)
---@overload fun(property_name: "FocusSearchPolicy", property_value: FocusSearchPolicy)
---@overload fun(property_name: "Font"|"LowDpiFont"|"TcFont", property_value: Font)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "IconsGrid", property_value: Gma3UI.IconsGrid)
---@overload fun(property_name: "IconsGridAnchors", property_value: Gma3UI.IconsGridAnchors[])
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "Size", property_value: Graphics.FixedSize)
---@overload fun(property_name: "X"|"TextOffsetH"|"Y"|"W"|"MinSize"|"H"|"IconOffsetV"|"TextOffsetV"|"IconOffsetH"|"ScrollBarHeight", property_value: Graphics.SizeDescriptor)
---@overload fun(property_name: "MaxSize"|"MinSize", property_value: Graphics.SizeDimension)
---@overload fun(property_name: "FixedHeaders"|"NormalHeaders"|"FixedCells"|"NormalCells", property_value: Graphics.UIGrid.GridArea)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "Mode", property_value: GridModeAgenda)
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "HotKey", property_value: HotKey)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "ArrayIndex"|"ArrayIndex", property_value: Index)
---@overload fun(property_name: "BackOffset", property_value: ItemGroupPosition)
---@overload fun(property_name: "KeyCode", property_value: KeyboardCodes)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "SizePolicy", property_value: LayoutSizePolicy)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "Target"|"Target", property_value: Mesh)
---@overload fun(property_name: "EscModalResult"|"CloseAction", property_value: ModalResult)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "MouseButtonType", property_value: MouseButtonTypes)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "EditTarget"|"Target"|"Target"|"Target"|"ExternScrollPos"|"AppearanceTarget"|"Target"|"Target"|"Target"|"CurrentUpdateObject"|"Target"|"MainBuddy"|"ScrollTarget"|"ScribbleTarget"|"WorkingDestination"|"EditTarget"|"Target"|"Target"|"Target"|"Target"|"Target"|"Target"|"Target"|"TargetObject"|"HistoryProvider"|"TextViewProvider"|"Context"|"Target"|"TargetObject"|"Target"|"EditTarget"|"Target"|"Target"|"Target"|"TargetObject"|"SelectedRow"|"Target"|"Target"|"ScrollTarget"|"Target", property_value: Object)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Settings", property_value: PSRPatchSheetSettings)
---@overload fun(property_name: "EncoderFunction", property_value: PhaserEncoderFunction)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "PolicyOnEnter", property_value: PolicyOnEnter)
---@overload fun(property_name: "PoolSettings"|"PoolSettings", property_value: PoolSettings)
---@overload fun(property_name: "SizeY"|"SizeY"|"SizeX"|"SizeX", property_value: PoolSizeFactor)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "EnabledItems", property_value: PropertyRadioButtonListEnabledItems)
---@overload fun(property_name: "SetType", property_value: PropertyRadioButtonListSetType)
---@overload fun(property_name: "ExecProxy", property_value: Proxy)
---@overload fun(property_name: "RowReductionPolicy"|"ColReductionPolicy", property_value: ReductionPolicy)
---@overload fun(property_name: "ViewW"|"ViewH", property_value: RequestedSize)
---@overload fun(property_name: "InternalRole", property_value: Roles)
---@overload fun(property_name: "ItemPlacementTypeV"|"ItemPlacementTypeH", property_value: ScrollItemPlacementType)
---@overload fun(property_name: "ScrollEntity"|"ScrollEntity", property_value: ScrollParamEntity)
---@overload fun(property_name: "Direction"|"Type"|"Direction"|"AutoNextCellDirection"|"ScrollType"|"Type"|"Direction"|"Type", property_value: ScrollType)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "Settings", property_value: ShowCreatorSettings)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "Mode", property_value: ShowfileSelectorMode)
---@overload fun(property_name: "TargetSound", property_value: Sound)
---@overload fun(property_name: "Band", property_value: SoundValues)
---@overload fun(property_name: "SpecialExecIndex"|"SpecialExecIndex"|"SpecialExecIndex", property_value: SpecialExecutor)
---@overload fun(property_name: "UIToControl", property_value: SplitterH_LeftRight)
---@overload fun(property_name: "UIToControl", property_value: SplitterV_TopBottom)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "DeselectedIcon"|"Icon"|"KnobTexture"|"TriggerTexture"|"SelectionFrame"|"Lasso"|"LockTexture"|"TitleButtonIcon"|"PinnedIcon"|"GearTexture"|"CursorTexture"|"OverridesIndicator"|"SelectionBackgroundTexture"|"TextureNormal"|"TextureHover"|"ProgIndicator"|"IndicatorBackTexture"|"SampleTexture"|"IndicatorTexture"|"SelectionTexture"|"ExpandedTexture"|"ContractedTexture"|"DelimiterTexture"|"ExpandedIcon"|"Icon"|"CollapsedIcon"|"KnobTexture"|"SelectedIcon"|"BrushTexture"|"SelectionTexture"|"SlotTexture"|"DeselectedIcon"|"UpperTexture"|"SelectionFrame"|"SensorTexture"|"LowerTexture"|"UpperTexture"|"IconActive"|"SelectionTexture"|"OnOffTexture"|"LowerTexture"|"BlockerTexture"|"IconInactive"|"LogoIcon"|"SignalTexture"|"Indicator"|"BorderTexture"|"ExpandedIcon"|"TextureHorizontal"|"HeadLineTexture"|"IndicatorBack"|"Texture"|"CollapsedIcon"|"IndicatorFrame"|"TitleButtonIcon"|"TextureHorizontalHover"|"TextureVertical"|"TextureVerticalHover"|"ProgIndicator"|"CursorTexture"|"SelectedIcon"|"CountDownIcon"|"ArrowRight"|"ArrowLeft"|"SelectionFrame"|"DeselectedIcon"|"OnOffTexture"|"SelectedIcon"|"StopwatchIcon"|"SortAsc"|"IndicatorIcon"|"SelectionBackgroundTexture"|"SortDesc", property_value: Texture)
---@overload fun(property_name: "Icons", property_value: Texture[])
---@overload fun(property_name: "Source", property_value: TimeCodeSource)
---@overload fun(property_name: "Position"|"Duration", property_value: TimePropertyValue)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "EncoderFunction", property_value: TimecodeEncoderFunction)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "Direction", property_value: ToolbarScrollType)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "LabelLinkHandle"|"Target"|"LinkedObject"|"TargetObject", property_value: UIObject)
---@overload fun(property_name: "UserRights", property_value: UserRights)
---@overload fun(property_name: "ValueRole", property_value: ValueRole)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "Settings"|"WindowSettings"|"SubWindowSettings"|"WindowSettings"|"WindowSettings"|"WindowSettings", property_value: WindowSettings)
---@overload fun(property_name: "TextVertical"|"DependsOnLinkedObject"|"ShowFileSegmentDmxProtocols"|"AutoNextCell"|"TextAutoAdjust"|"TextUniform"|"SelectionOnFocusOnly"|"TargetIsAppearance"|"Local"|"ShowNumber"|"DirectCommand"|"AvoidScroll"|"DirectQuotation"|"InteractWithCommandline"|"ShowKeyboardButton"|"Rounded"|"Visible"|"TargetIsScribble"|"Secret"|"IndicatorBarEnabled"|"CanCoExistWithModal"|"CanBeEmbedded"|"SetPropertyOnlyOnTextChange"|"ShowLeftIcon"|"UserVisible"|"CalledFromCmdline"|"ShowRightIcon"|"Enabled"|"EditTitlebar"|"ShowAdditionalInfo"|"Interactive"|"SearchFocusTestParent"|"ShowLeftScribble"|"Transparent"|"ShowRightScribble"|"BlockClickThru"|"AllowBlocks"|"UserInteracted"|"IsMidiOut"|"ForceSmallMode"|"SkipTextIfIconExists"|"HasHover"|"State"|"ShowVisibleDay"|"ItemIndividualCorners"|"Separator"|"HasPressedAnimation"|"AutoCloseOnInput"|"ContentDriven"|"ContentWidth"|"WantsModal"|"ReadOnly"|"ContentHeight"|"AutoClose"|"ShowLineNumbers"|"ForceContentMin"|"ShowWhiteSpace"|"WantsNumericRedirect"|"AutoCloseOnOverlay"|"HighlightCurrentLine"|"CloseOnEscape"|"NewlineWithSpaces"|"IndirectEdit"|"ForceCursor"|"ScrollChangesSelection"|"IncludeTarget"|"FilterByName"|"InitialSaveEditTarget"|"EditTargetHasChanged"|"IgnoreBackdropPadding"|"ReactToPreview"|"FilterByManufacturer"|"MixInBackColorFromParent"|"PanScrollArea"|"StayAlwaysVisible"|"FilterByName"|"VisualisableScrollV"|"SmallResizeArea"|"PanScroll"|"ReactToEdit"|"IgnoreRequestedSize"|"ScrollCellAutomatic"|"RelativeToDisplay"|"FilterByMode"|"ForceEncoderBar"|"ScrollCellAutomaticWithOffset"|"FilterByDescription"|"SuppressOverlayAutoClose"|"FilterByUsedOnly"|"EnterToExecute"|"ResetChildrenSize"|"IsClosing"|"AdjustInitialPosition"|"TextShadow"|"IsMainBuddy"|"UpdateSettingsVisibility"|"UseSimplifiedResize"|"InitialSaveEditTarget"|"BigMode"|"DriveReset"|"EditTargetHasChanged"|"AutoCreateFromProperties"|"OverrideKeybSC"|"UseEditorTarget"|"ReactToPreview"|"SuppressModeSwitch"|"ForceHideCategories"|"ReactToEdit"|"ScreenEncoder"|"UseDynamicIndicatorColor"|"OnlyVisible"|"IsWorldCoordinateSystemActive"|"HasFocus"|"ResetIfUntargeted"|"TryFitIntoSecondary"|"IsCameraFocusOnSelectedItem"|"HideFocusFrame"|"EditAllowedDelete"|"Inverted"|"StealFocusAfterSelect"|"Content"|"VisibleOnlyInAlpha"|"CmdlineInteraction"|"TryAvoidZeroes"|"TitleButtonBool"|"VisibleOnlyInBeta"|"TargetCmdlineInteraction"|"TryFitMainIfContentDriven"|"DrawShortcutInfo"|"VisibleOnlyInRelease"|"EditAllowedAdd"|"SeparatorSupport"|"ClickNearest"|"CreateAndEdit"|"ModifyTextureLayout"|"AutoClose"|"VisibleInAlpha"|"AddTargets"|"ProvideEmpty"|"Features"|"VisibleInBeta"|"ObserveSelectionChange"|"MixPercentAndHexDecModesAllowed"|"FeatureGroups"|"VisibleInRelease"|"AllChannelSets"|"FeatureGroupsOnly"|"ShowFullSettings"|"WeakAlternationInHeader"|"Toggle"|"ForceFocusOnChange"|"WeakAlternationInData"|"DrawInbetweenValues"|"ShowLabel"|"ShowCSHelp"|"ValueAutoAdjust"|"ShowValue"|"VisualisableScrollH"|"DataAsIs"|"AutoHide"|"WorkWithGrid"|"IsScribbleNew"|"IndirectEdit"|"IsAppearanceNew"|"DirectProperty"|"SearchFocusTestParent"|"DefaultAction"|"CharAction"|"Undo"|"ChangeDestination"|"HiglightActiveCue"|"ValueTextShadow"|"WorkWithGrid"|"IgnoreActiveForEnums"|"DimmerCueOnly"|"Auto"|"ShowOldVersions"|"UseCommandlineClick"|"SetIconAsActiveInactive"|"ExclusivePropertyChange"|"NoEmptyNames"|"EditNewObject"|"UseTabRegistry"|"UseGridColor"|"PositionBeneathFinger"|"MixInBackColorFromParentRecursive"|"AutoTexture"|"DefaultAction"|"TrackEdit"|"ExpandContent"|"DefaultMarginOnBorders"|"TrackWorld"|"EncoderUseDisplay"|"UseDefaultValue"|"SmallMode"|"UseComposedText"|"ShowSelectionCount"|"ShowFileSegmentLocalSettings"|"ForceFastFade"|"ShowAdditionalInfo"|"AutoScrollToEnd"|"AutoEnabled"|"TextChangeOnEnter"|"CloseProhibited"|"NoEmptyNames"|"ShowFileSegmentOutputStations"|"AllowAddContent"|"AllowAddNewline"|"ShowUnpatchedOnly"|"ReactToRecipeEdit"|"DisplayLevel"|"ScrollOpposite"|"AllowMergeChildren"|"ShowManualCueSelection"|"AllowedInvisible"|"AllowEdit"|"ContentChanged"|"ForceCursor"|"PrintCurrentValue"|"CanProvideUiGridSelection"|"ReactToRecipeEdit"|"LongPressVK"|"AllowFilterContent"|"DirectQuotation"|"AutoCloseAllowed"|"PrintMaxValue"|"FilterBlockUIEnabled"|"GapsForExpanded"|"UseUserProfileSettings"|"ScrollOutEnabled"|"CloseOnClick"|"VScrollOnHeader"|"PrimaryHasFocus"|"ConvertCursorToTabAtBoundaries"|"IsInExport"|"DrawContent"|"BackgroundButtonStyle"|"ContentStyle"|"ShowTcSlotAndTcMode"|"KeyRepeatEnabled"|"ShowFileSegmentShowData"|"ReadOnly"|"IgnoreIconForTextAlign", property_value: YesNo|boolean)
---@overload fun(property_name: "DrawGradient"|"AutoSetWindowSettings"|"AllIndexesCollected"|"IsScribbleAvailable"|"IsAppearanceAvailable"|"FadeEncoder"|"UseSpecialTimezone"|"CheckForScreenEncoders"|"IsNoteAvailable"|"ChangeDestination"|"Expanded"|"IsPlaying"|"AllowSorting"|"ScribbleIsEmpty"|"IsCloneDestination"|"Blink", property_value: boolean)
---@overload fun(property_name: "ChangeActive", property_value: fun(childName: string) : boolean)
---@overload fun(property_name: "OnTitleClick"|"CallP1"|"Solve"|"StoreP2"|"Close"|"CallP2"|"StoreP1"|"Update"|"OnTitleClick"|"CloseConfirm"|"StoreP3"|"OnTitleClick"|"CloseCancel"|"CallP3"|"StoreP4"|"CallP4", property_value: fun(dummyStr: string) : boolean)
---@overload fun(property_name: "OnPatchToClicked"|"OnUniverseUpClicked"|"OnUnpatchClicked"|"OnUniverseDownClicked", property_value: fun(dummyStr: string, button: MouseButtonTypes, X: integer, Y: integer) : boolean)
---@overload fun(property_name: "OnAddressSelected"|"OnBreakPatched"|"OnDBObjectSelected"|"OnBreakSelected", property_value: fun(dummyStr: string, column: integer, row: integer) : boolean)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "Clear", property_value: fun(dummyString: string) : boolean)
---@overload fun(property_name: "HideMessage"|"ShowMessage", property_value: fun(message: string) : boolean)
---@overload fun(property_name: "ChangeText", property_value: fun(newTextStr: string) : boolean)
---@overload fun(property_name: "SetPrompt", property_value: fun(prompt: string) : boolean)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "StatusChanged"|"TooltipChanged"|"OnCreateNewAppearance"|"MoveStart"|"ScrolledToEndV"|"ResizeEnd"|"PathChanged"|"OnUserProfileChanged"|"FilterChanged"|"ResizeStart"|"Execute"|"Execute"|"LassoFinished"|"DescriptionChanged"|"TextChanged"|"OnScreenPushed"|"ScribbleTargetChanged"|"OnWrongChar"|"OnCreateNewAppearance"|"Scrolled"|"OnCreateNewScribble"|"AppearanceTargetChanged"|"MoveStart"|"ResizeStart"|"OnListRefDone"|"ResizeEnd"|"UrlChanged"|"ProgressChanged", property_value: fun(str: string))
---@overload fun(property_name: "TimecodeAddEvent"|"TimecodeAddMultiEvents"|"OnFixtureSourceChanged"|"TimecodeAddTimeRange"|"TimecodeAddTimeMarker"|"SetUrlA"|"GoBack"|"OnCreateNewAppearance"|"GoFwd"|"CheckAutoClose"|"OnNavigate"|"Reload"|"RequestMemUsage"|"OnCheckSubPoolSelector"|"SetDateToday"|"OnInput"|"ApplyScribble"|"SetTimeNow"|"OnState"|"OnSelectDataPool"|"RevertScribble"|"OnCommand"|"OnCreateNewScribble"|"DeleteFilterItem"|"OnTitle"|"OnCollectAllIndexes"|"AddFilterItem"|"ResetMouse"|"SetToTop"|"DeleteClicked"|"ScrollPageDown"|"Play"|"OnFocusLost"|"TBDeleteAll"|"Undo"|"Pause"|"TBLoadDefaults"|"Redo"|"Stop"|"ClearScribble"|"ClearSelection"|"SetText"|"OnApplyColorToCurves"|"InsertText"|"ClearText"|"DeleteOld"|"OnToolOperate"|"SelectAllRows"|"SaveEditTarget"|"ClearFilter"|"ScrollAction"|"RevertEditTarget"|"OnClearCmdline"|"MoveStart"|"ToggleListRef"|"ExpandAll"|"ResizeEnd"|"SetCursorToEnd"|"ScrollToEnd"|"OnSelectedTreeItem"|"SaveToDefault"|"OnScrolledTreeItem"|"LoadFromDefault"|"KeyPress"|"SelectedFixture"|"SaveEditTarget"|"ResizeStart"|"ResizeStart"|"MoveStart"|"SelectedManufacturer"|"Context"|"ResizeEnd"|"RememberSelection"|"RevertEditTarget"|"MapClicked"|"InitGrids"|"Context"|"UpdateEncoderBar"|"TabChanged"|"OnSpecialButtonClicked"|"OnExpandAll"|"EnumClicked"|"OnCollapseAll"|"OnExpandSelected"|"Search"|"OnClearSelection"|"AutoScroll"|"OnStageChanged"|"SelectAll"|"SelectNothing"|"OnDataPoolChanged"|"OnSetSelectorVisibility"|"SwitchExpansion"|"OnCollapseAll"|"OnZoomToFit"|"OnSetRecalcCenterOfGravity"|"FunctionSelectorChanged"|"EncoderReadoutSelectorChanged"|"OnEditCurrentLayout"|"SetPath"|"DeleteSelectedFiles"|"SetFilter"|"GoUp"|"SelectFirstFile"|"ScrollToFirstFile"|"OnPatchToNextFree"|"OnSwipeMenu"|"ProgressChanged"|"OnMoveToUniverse"|"SGResizeStart"|"SGResizeEnd"|"OpenAtFilter"|"OnSwipeMenu"|"ToggleAtFilter"|"OnPatchToClicked"|"OnShowUnpatchedClicked"|"SGResizeStart"|"SGResizeEnd"|"MeasureColor"|"SetPlus"|"DarkCalibrate"|"SetMinus"|"FindDevice"|"ShowAnimation"|"ResetView"|"ZoomIn"|"ZoomOut"|"ChangedActiveTab"|"TimecodePause"|"TimecodeBackward"|"TimecodeRecord"|"TimecodeForward"|"TimecodeStop"|"OpenVK"|"TimecodePlay"|"SelectAll"|"TimecodePrevMarker"|"TimecodeNextMarker"|"DeSelect"|"OnFunction"|"SelectionCopy"|"SetCursorToEnd"|"SelectionCut"|"SelectionPaste", property_value: fun(str: string) : boolean)
---@overload fun(property_name: "ResizeMove", property_value: fun(str: string, AbsX: integer, AbsY: integer))
---@overload fun(property_name: "MouseUp"|"Clicked"|"MouseDown"|"DoubleClicked"|"MouseDownHold", property_value: fun(str: string, Button: MouseButtonTypes, X: integer, Y: integer))
---@overload fun(property_name: "ResizeMove"|"ResizeMove"|"Move"|"Move", property_value: fun(str: string, DeltaX: integer, DeltaY: integer))
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "MouseOverHold"|"MouseEnter"|"MouseUpLeft"|"MouseUpRight"|"ClickedLeft"|"ClickedRight"|"MouseDownLeft"|"MouseDownRight"|"MouseLeave", property_value: fun(str: string, X: integer, Y: integer))
---@overload fun(property_name: "MoveEnd"|"OnVisible"|"ResizeEnd"|"MoveEnd", property_value: fun(str: string, bool: boolean))
---@overload fun(property_name: "MoveEnd"|"ResizeEnd", property_value: fun(str: string, bool: boolean) : boolean)
---@overload fun(property_name: "ResizeStart"|"OnBeforeEdit"|"OnAfterEdit"|"OnSelectionAfterCmd"|"SelectionChanged"|"UndoRedoChanged", property_value: fun(str: string, int1: integer, int2: integer))
---@overload fun(property_name: "ResizeStart"|"SGResizeMove"|"ResizeMove"|"Move"|"SGResizeMove"|"SelectCell"|"SelectRange"|"Resize"|"ResizeMove"|"CallSubMenu"|"Move", property_value: fun(str: string, int1: integer, int2: integer) : boolean)
---@overload fun(property_name: "TabChanged", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean))
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "TabClickedOnCurrent"|"OnSelectedItem", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean))
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "FactoryDefaults"|"RotateToCircleCenter"|"Rotate90ToLine"|"ResetUnusedAxis"|"OnClick"|"ReloadRenderQuality"|"ResetRotation"|"Oops"|"ReloadCamera"|"ResetPosition"|"OnShow3dSettings"|"Show3DSettings"|"ResetCamera"|"CenterPosition"|"AnalyzeMeshPool"|"ArrangePosition"|"SelectionToGrid"|"OnClick"|"ActionSetPriority"|"HardkeyMouseUp"|"ReloadCamera"|"HardkeyMouseDown"|"OnClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer) : boolean)
---@overload fun(property_name: "GestureClick"|"GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer))
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "OnCellMouseDoubleClicked"|"OnCellMouseDown"|"OnCellMouseDownHold"|"OnCellMouseUp"|"OnCellMouseClicked", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer, int5: integer))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "OnSelectedColumn"|"OnSelectedRow"|"MemUsageUpdated"|"OnTargetChanged"|"OnTargetChanged"|"OnSelectedItem", property_value: fun(str: string, int: integer))
---@overload fun(property_name: "ReTriggerInit"|"ChangeTarget"|"SetFPSLimit"|"OnChar"|"ReTriggerInit"|"AddSelectedFixtures"|"ClearGrid"|"GridMoveUp"|"GridMoveDown"|"GridCut"|"ChangeTarget"|"GridCopy"|"GridPaste"|"GridAdd"|"GridDelete"|"SelectRow"|"GridFillUp"|"JumpToNextLine"|"AddRow"|"SelectionChanged"|"GridUnify"|"JumpToPreviousLine"|"AddMissingLines"|"ScrollToRow"|"SelectColumn"|"SortByColumn"|"AddSelectedLines"|"OnChar"|"ScrollVertical"|"ScrollHorizontal", property_value: fun(str: string, int: integer) : boolean)
---@overload fun(property_name: "KeyDown"|"KeyUp", property_value: fun(str: string, keyCode: VirtualKeyCode, bool1: boolean, bool2: boolean, bool3: boolean))
---@overload fun(property_name: "Seek"|"ForceScale", property_value: fun(str: string, num: number) : boolean)
---@overload fun(property_name: "FocusLost"|"FocusGet", property_value: fun(str: string, obj1: Object, obj2: Object))
---@overload fun(property_name: "OnSetEditTarget"|"OnLoad"|"OnSetEditTarget"|"LinkedObjectChanged"|"OnSetEditTarget", property_value: fun(str: string, obj: Object))
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "TouchUpdate"|"TouchStart"|"TouchEnd", property_value: fun(str: string, pointID: integer, X: integer, Y: integer))
---@overload fun(property_name: "OnUpdateTitle"|"OnUpdateTitle", property_value: fun(str: string, str: string))
---@overload fun(property_name: "CharInput", property_value: fun(str: string, utf32Char: integer))
---@overload fun(property_name: "Changed", property_value: fun(str: string, value: integer))
---@overload fun(property_name: "Set", property_value: fun(str: string, value: integer) : boolean)
---@overload fun(property_name: "OpenSequenceFilter"|"FlipLeftRight"|"OpenGroupFilter"|"DoReset"|"OpenPresetFilter"|"SetText"|"ObtainCurrentCue"|"InitFirst"|"InitTargetList"|"AddText"|"DoClone"|"OpenWorldFilter"|"InsertText"|"OpenLayoutFilter"|"SelectFirst"|"ChangeCloningViewMode"|"AllItemsToAll"|"AllItemsToNone", property_value: fun(text: string) : boolean)
---@overload fun(property_name: "RasterHeight"|"SelectedColumn"|"RasterWidth"|"Distance"|"Hour"|"ItemSize"|"Minute"|"VisibleItemCount"|"FrameWidth"|"AutoFitColumn"|"Second"|"SlotIndex"|"GridVersion"|"Day"|"MaxTextLength"|"Priority"|"Year"|"Direction"|"Selector"|"AutoCloseValue"|"MaxIndicatorSize"|"UiGroupId"|"UndoCount"|"RedoCount"|"PatchOffset"|"FilterMask"|"VisibleFixturesCount"|"SubDestination"|"HeadLineDimension"|"ButtonDimension"|"SlotDimension"|"ColorIndicatorHeight"|"MaxValue"|"MinValue"|"MinCellSize"|"LineHeightAdd"|"IgnoreChildren"|"BigModeColumns"|"LineSpacing"|"TitleButtonUInt64"|"BigModeRows"|"MaxValue"|"DelimiterSize"|"ActiveSource"|"TitleButtonInt64"|"TitleButtonPopup"|"GridDelta"|"RealSize"|"LabelAreaHeight"|"ExecFrom"|"ForceIntensity"|"FixtureCount"|"ExecBarToDraw"|"FirstRow"|"DefaultMargin"|"LastRow"|"Columns"|"ExecutorIndex"|"Rows"|"BreakIdx"|"CellWidth"|"CellHeight"|"PatchOffset"|"ExecRowCount"|"ExecutorIndex"|"BlockWidth"|"ExecColCount"|"BlockHeight"|"ExecutorIndex"|"RasterHeight"|"FrameThickness"|"RasterWidth"|"ScrollCellFrameThickness"|"SpecialExecOffset"|"LevelDistance"|"IncrementFactor"|"ColumnResizeMaxDeviation"|"Mask"|"LevelLimit"|"Mask"|"Page"|"LevelLimit"|"Border"|"ShowFileSegmentsMask"|"State"|"OptionHeight"|"SelectedRow", property_value: integer)
---@overload fun(property_name: "RunningPlaybacks", property_value: integer[])
---@overload fun(property_name: "Value"|"EncoderResolution"|"IconScale"|"RatioAll"|"CurrentFps"|"Progress"|"ScaleAll"|"ItemPlacementOffsetFactorV"|"ItemPlacementOffsetFactorH", property_value: number)
---@overload fun(property_name: "ReferencedTitleButton"|"ItemType"|"Cursor"|"DirectPrefix"|"TargetPath"|"InitialTab"|"InitialSubTab"|"System"|"ItemFilter"|"DefaultTitle"|"EditEncoderBar"|"Content"|"ControlEncoderBar"|"FixtureName"|"Property"|"EditEncoderBar"|"ControlEncoderBar"|"ForcedInitialTab"|"BuddyGroupId"|"Filter"|"Property"|"System"|"SignalValue"|"SignalValueHold"|"PrivacyPolicyUrl"|"FilterComposed"|"Property"|"TrademarksUrl"|"Value"|"System"|"Value"|"ReleaseNotesUrl"|"AppearanceSourceClassName"|"Destination"|"TargetPropertyName"|"TextLeftCorner"|"EmptyName"|"System"|"InsertType"|"LedToken"|"ActiveChild"|"Property"|"System"|"CurrentSelectedShowFile"|"Property"|"Property"|"FuzzyFilter"|"FuzzyFilterExcludeEnd"|"EditEncoderBar"|"BaseFilter"|"ImportOptions"|"WarningTooltip"|"Value"|"SelectedFile"|"SwipeMenu"|"StrContext"|"BarText"|"AuxProperty"|"Property"|"AdditionalInfo"|"VKTitleHint"|"DummyComposedText"|"Property"|"SwipeMenu"|"VKPluginName"|"Destination"|"Prompt"|"Filter"|"EmptyText"|"Message"|"Property"|"FixtureToMeasure"|"DirectPrefix"|"Text"|"DataType"|"SelectionType"|"ToolTip"|"CellType"|"HelpTopic"|"SettingsType", property_value: string)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "OptionAreaMargin"|"ContentAreaMargin"|"LabelAreaMargins"|"ValueAreaMargins"|"Margin"|"Anchors"|"Padding", property_value: {left: integer, right: integer, top: integer, bottom: integer})
---@overload fun(property_name: "AbsRect"|"AbsClientRect"|"WindowRect", property_value: {left: number, right: number, top: number, bottom: number})
function ItemCollect:SetChildrenRecursive(property_name, property_value) end