---@meta

---@class Item: GraphicsObject Represents a single item (a row or a column) of a grid configuration
---@field SizePolicy LayoutSizePolicy
---@field Size Graphics.FixedSize
---@field MinSize Graphics.SizeDescriptor minimum size that is requested for this item (row or column). if <= 0 - not used
---@field RealSize integer real size in pixels
local Item = {
    SizePolicy="Stretch",
    Size="1",
    MinSize="0"
}
---@return "Item"
function Item:GetClass() end
---@return "GraphicsObject"
function Item:GetChildClass() end
---@generic T : Item
---@param class `T`
---@return boolean
function Item:IsClass(class) end
---@return ItemCollect
function Item:Parent() end
---@return 19
function Item:PropertyCount() end
---@overload fun(idx: 0): "IgnoreNetwork"
---@overload fun(idx: 1): "StructureLocked"
---@overload fun(idx: 2): "SystemLocked"
---@overload fun(idx: 3): "Lock"
---@overload fun(idx: 4): "Index"
---@overload fun(idx: 5): "Count"
---@overload fun(idx: 6): "No"
---@overload fun(idx: 7): "Name"
---@overload fun(idx: 8): "Note"
---@overload fun(idx: 9): "UserExpanded"
---@overload fun(idx: 10): "FaderEnabled"
---@overload fun(idx: 11): "Owned"
---@overload fun(idx: 12): "Hidden"
---@overload fun(idx: 13): "DependencyExport"
---@overload fun(idx: 14): "MemoryFootprint"
---@overload fun(idx: 15): "SizePolicy"
---@overload fun(idx: 16): "Size"
---@overload fun(idx: 17): "MinSize"
---@overload fun(idx: 18): "RealSize"
function Item:PropertyName(idx) end
---@overload fun(idx: 0|1|2): {ExportIgnore: True, EnumCollection: YesNo, ReadOnly: False, ImportIgnore: False}
---@overload fun(idx: 3|12): {ExportIgnore: False, EnumCollection: YesNo, ReadOnly: False, ImportIgnore: False}
---@overload fun(idx: 4|5|6|18): {ExportIgnore: True, ReadOnly: False, ImportIgnore: False}
---@overload fun(idx: 7|8|13|16|17): {ExportIgnore: False, ReadOnly: False, ImportIgnore: False}
---@overload fun(idx: 9): {ExportIgnore: False, EnumCollection: YesNo, ReadOnly: True, ImportIgnore: True}
---@overload fun(idx: 10|11): {ExportIgnore: True, EnumCollection: YesNo, ReadOnly: True, ImportIgnore: True}
---@overload fun(idx: 14): {ExportIgnore: False, ReadOnly: True, ImportIgnore: True}
---@overload fun(idx: 15): {ExportIgnore: False, EnumCollection: LayoutSizePolicy, ReadOnly: False, ImportIgnore: False}
function Item:PropertyInfo(idx) end
---@overload fun(idx: 0|1|2|3|4|5|6|9): "UInt32"
---@overload fun(idx: 7|8|13): "String"
---@overload fun(idx: 10|11): "Bool"
---@overload fun(idx: 12): "UInt64"
---@overload fun(idx: 14): "Int64"
---@overload fun(idx: 15): "UInt8"
---@overload fun(idx: 16): "Custom"
---@overload fun(idx: 17): "Size"
---@overload fun(idx: 18): "Int16"
function Item:PropertyType(idx) end
---@overload fun(name: "Size", role: nil): Graphics.FixedSize
---@overload fun(name: "MinSize", role: nil): Graphics.SizeDescriptor
---@overload fun(name: "SizePolicy", role: nil): LayoutSizePolicy
---@overload fun(name: "IgnoreNetwork"|"StructureLocked"|"SystemLocked"|"Lock"|"UserExpanded"|"FaderEnabled"|"Owned"|"Hidden", role: nil): YesNo|boolean
---@overload fun(name: "Index"|"Count"|"No"|"MemoryFootprint"|"RealSize", role: nil): integer
---@overload fun(name: "Name"|"Note"|"DependencyExport", role: nil): string
---@overload fun(name: "IgnoreNetwork"|"StructureLocked"|"SystemLocked"|"Lock"|"Index"|"Count"|"No"|"Name"|"Note"|"UserExpanded"|"FaderEnabled"|"Owned"|"Hidden"|"DependencyExport"|"MemoryFootprint"|"SizePolicy"|"Size"|"MinSize"|"RealSize", role: Enums.Roles): string
---@overload fun(name: integer, role: nil): GraphicsObject
function Item:Get(name, role) end
---@generic T : ContentSheetGridScroller|MeshLineEdit|DMXSheet|MeshMaterialGrid|FixtureSheet
---@param index integer
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(index: integer, class: "GraphicsObject", undo: Undo?): GraphicsObject
---@overload fun(index: integer, class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(index: integer, class: nil, undo: Undo?): GraphicsObject
function Item:Create(index, class, undo) end
---@generic T : ContentSheetGridScroller|MeshLineEdit|DMXSheet|MeshMaterialGrid|FixtureSheet
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(class: "GraphicsObject", undo: Undo?, count: integer?): GraphicsObject
---@overload fun(class: "NoteTextEdit", undo: Undo?, count: integer?): NoteTextEdit
---@overload fun(class: nil, undo: Undo?, count: integer?): GraphicsObject
function Item:Append(class, undo, count) end
---@generic T : ContentSheetGridScroller|MeshLineEdit|DMXSheet|MeshMaterialGrid|FixtureSheet
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "GraphicsObject", undo: Undo?): GraphicsObject
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: nil, undo: Undo?): GraphicsObject
function Item:Acquire(class, undo) end
---@generic T : ContentSheetGridScroller|MeshLineEdit|DMXSheet|MeshMaterialGrid|FixtureSheet
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "GraphicsObject", undo: Undo?): GraphicsObject
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: nil, undo: Undo?): GraphicsObject
---@deprecated use "Acquire" instead
function Item:Aquire(class, undo) end
---@generic T : ContentSheetGridScroller|MeshLineEdit|DMXSheet|MeshMaterialGrid|FixtureSheet
---@param index integer
---@param class `T`
---@param undo Undo?
---@param count integer?
---@return T
---@overload fun(index: integer, class: "GraphicsObject", undo: Undo?, count: integer?): GraphicsObject
---@overload fun(index: integer, class: "NoteTextEdit", undo: Undo?, count: integer?): NoteTextEdit
---@overload fun(index: integer, class: nil, undo: Undo?, count: integer?): GraphicsObject
function Item:Insert(index, class, undo, count) end
---@generic T : ContentSheetGridScroller|MeshLineEdit|DMXSheet|MeshMaterialGrid|FixtureSheet
---@param class `T`
---@param undo Undo?
---@return T
---@overload fun(class: "GraphicsObject", undo: Undo?): GraphicsObject
---@overload fun(class: "NoteTextEdit", undo: Undo?): NoteTextEdit
---@overload fun(class: nil, undo: Undo?): GraphicsObject
function Item:Find(class, undo) end
---@generic T : SampleTableView|Toolbar|UiFader|NotificationTitle|ProgressBar|DCRemoteInfo|UIGridCellBase|ScrollBar|UIGridFilterBlock|ScrollContainer|NotificationsWrapper|NotificationsGridScroller|Dialog|AutoLayout|SplitView|ScrollContainerPageBase|FrameBufferObject|Navigator|TitleBar|DialogFrame|PropertyBox|Overlay|TextEdit|ObjectProperties|VirtualKeyboard|Bar|GlWindowBase|UiMessageCenter|CustomMasterLayoutGrid|TagButtonList|PhaserUICenter|CloningDialog|AllExecDisplay|DialogTrackpad|PoolLayoutGrid|ScribbleEditContent|MainDialogSubMenuContent|ExecutorSection|MainDialogFunctionButtons|AgendaMonthsGrid|GridContentFilterEditor|SpecialWindowContent|UiScreen|BladeView|MainDialogContent|MatricksContainer|ThemeMergeToolBar|CmdDlgFunctionButtonsBase|GenericAssignmentSelector|PlaybackControlContent|AppearanceEditContent|ShaperEditorFaderGrid|EditorPropertyButtons|TagsEditContent|ReferencesContainer|PlaybackControlModularContent|NormedGrid|CommandWingBarContainer|InfoNotesWrapper|AtFilterDialog|UIPhaserTimeLineGrid|SpecialExecSection|AllPoolLayoutGrid|BaseClock|TouchMonitor|AgendaDaysGrid|TreeViewFrame|PhaserLayoutGrid|EncoderBarSlot|Splitter|LinearResizer|UIObjectFake|PropertyControl|UIGridConfigButton|ShowVKButton|ScrollBarButton|MovableButton|LogoButton|UIGridButton|DeleteWindowButton|IndicatorButton|WarningInfoButton|EjectButton|DimmerWheelButton|CloseButton|SoundPoolTitleButton|FilterPoolTitleButton|TimecodePoolTitleButton|TimerPoolTitleButton|VideoPoolTitleButton|PluginPoolTitleButton|GelPoolTitleButton|TimecodeSlotPoolTitleButton|SequencePoolTitleButton|MacroPoolTitleButton|AllPoolTitleButton|ShowMoreButton|MouseButton|MessageCenterButton|TreeExpandButton|AgendaDayButton|ProgressButton|TagButton|MessageCenterInfoButton|DriveStatusButton|SelectButton|RevertButton|PlaceHolderBase|LineEdit|ColorView|NotificationIcon|SensorView|DialogContainer|ScrollableItemList|ResizeCorner|ScribbleEditView|PropertyLabel|BandFader|MiniEncoder|ScrollBox|StatusBar|MultiScroller|NotificationText|TimecodeSlotInfo|TextView|TouchConfigurator|InfoNotesLabel|AppearancePreview|MacrolinePreview|TrackpadMouseControl|SoundBandView|MainDialogDummy|EditorSubCategoryButton|CommandLineOutput|InfoNotesLevel|AllExecContent|TreeViewRows|SoundLevelView|PerformanceView|ColorTestView|EditorCategoryButton|InfoNotesGridScroller|TouchTarget|EditorBase|BladeViewButton|OutputTest|BaseSymbol|ColorPickBase|TreeViewRow|SignalView|ShaperTestView
---@param name string
---@param class `T`
---@return T
---@overload fun(name: string, class: "GraphicsObject"): GraphicsObject
---@overload fun(name: string, class: "UIObject"): UIObject
---@overload fun(name: string, class: "UILayoutGrid"): UILayoutGrid
---@overload fun(name: string, class: "Drawable"): Drawable
---@overload fun(name: string, class: "Button"): Button
---@overload fun(name: string, class: "TitleButton"): TitleButton
---@overload fun(name: string, class: "PoolTitleButton"): PoolTitleButton
---@overload fun(name: string, class: nil): Object
function Item:FindRecursive(name, class) end
---@generic T : ItemCollect
---@param class `T`
---@return T
function Item:FindParent(class) end
---@overload fun(property_name: "Size", property_value: Graphics.FixedSize, override_change_level: ChangeLevel?)
---@overload fun(property_name: "MinSize", property_value: Graphics.SizeDescriptor, override_change_level: ChangeLevel?)
---@overload fun(property_name: "SizePolicy", property_value: LayoutSizePolicy, override_change_level: ChangeLevel?)
---@overload fun(property_name: "IgnoreNetwork"|"StructureLocked"|"SystemLocked"|"Lock"|"Hidden", property_value: YesNo|boolean, override_change_level: ChangeLevel?)
---@overload fun(property_name: "Index"|"Count"|"No"|"RealSize", property_value: integer, override_change_level: ChangeLevel?)
---@overload fun(property_name: "Name"|"Note"|"DependencyExport", property_value: string, override_change_level: ChangeLevel?)
function Item:Set(property_name, property_value, override_change_level) end
---@overload fun(property_name: "Target", property_value: Mesh)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "ObtainCurrentCue", property_value: fun(text: string) : boolean)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "Target", property_value: Mesh)
---@overload fun(property_name: "OnUniverseUpClicked"|"OnUniverseDownClicked", property_value: fun(dummyStr: string, button: MouseButtonTypes, X: integer, Y: integer) : boolean)
---@overload fun(property_name: "ObtainCurrentCue", property_value: fun(text: string) : boolean)
function Item:ObtainCurrentCue(property_name, property_value) end
---@overload fun(property_name: "Source", property_value: TimeCodeSource)
---@overload fun(property_name: "Mode", property_value: DatumMode|GridModeAgenda|ShowfileSelectorMode|BlinkingButtonMode|CalculatorMode)
---@overload fun(property_name: "RunningPlaybacks", property_value: integer[])
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "HotKey", property_value: HotKey)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "EncoderFunction", property_value: PhaserEncoderFunction|TimecodeEncoderFunction|EncoderFunction)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "Focus", property_value: FocusPriority)
---@overload fun(property_name: "Settings", property_value: PSRPatchSheetSettings|CloningWindowSettings|ShowCreatorSettings)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "UserRights", property_value: UserRights)
---@overload fun(property_name: "TargetSound", property_value: Sound)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "InternalRole", property_value: Roles)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "MouseButtonType", property_value: MouseButtonTypes)
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Appearance", property_value: Appearance)
---@overload fun(property_name: "Direction", property_value: ToolbarScrollType|AutoLayoutScrollType)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "ChangeText", property_value: fun(newTextStr: string) : boolean)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "KeyCode", property_value: KeyboardCodes)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FocusSearchPolicy", property_value: FocusSearchPolicy)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "EncoderType", property_value: EncoderType)
---@overload fun(property_name: "EncoderRing", property_value: EncoderRing)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "Changed", property_value: fun(str: string, value: integer))
---@overload fun(property_name: "Set", property_value: fun(str: string, value: integer) : boolean)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "ChangeActive", property_value: fun(childName: string) : boolean)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "UIToControl", property_value: SplitterV_TopBottom|SplitterH_LeftRight)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "BackOffset", property_value: ItemGroupPosition)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "ResizeMove", property_value: fun(str: string, AbsX: integer, AbsY: integer))
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "CharInput", property_value: fun(str: string, utf32Char: integer))
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "Drive", property_value: Drive)
---@overload fun(property_name: "TabChanged", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "ValueRole", property_value: ValueRole)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "Band", property_value: SoundValues)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "PolicyOnEnter", property_value: PolicyOnEnter)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "Property", property_value: EncoderGroupType)
---@overload fun(property_name: "Icons", property_value: Texture[])
---@overload fun(property_name: "IconsGrid", property_value: Gma3UI.IconsGrid)
---@overload fun(property_name: "IconsGridAnchors", property_value: Gma3UI.IconsGridAnchors[])
---@overload fun(property_name: "SetType", property_value: PropertyRadioButtonListSetType)
---@overload fun(property_name: "ExecProxy", property_value: Proxy)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "EnabledItems", property_value: PropertyRadioButtonListEnabledItems)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "Clear", property_value: fun(dummyString: string) : boolean)
---@overload fun(property_name: "SetPrompt", property_value: fun(prompt: string) : boolean)
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "ValueAlignmentH"|"AlignmentH"|"IconAlignmentH"|"IconAlignmentH"|"TextAlignmentH"|"LogoIconAlignmentH"|"KeyboardIconAlignmentH", property_value: AlignmentH)
---@overload fun(property_name: "ValueAlignmentV"|"AlignmentV"|"IconAlignmentV"|"TextAlignmentV"|"IconAlignmentV"|"LogoIconAlignmentV"|"KeyboardIconAlignmentV", property_value: AlignmentV)
---@overload fun(property_name: "Appearance", property_value: Appearance)
---@overload fun(property_name: "Direction", property_value: AutoLayoutScrollType)
---@overload fun(property_name: "Mode", property_value: BlinkingButtonMode)
---@overload fun(property_name: "Mode", property_value: CalculatorMode)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "TriggerIndirectInitLevel"|"BlockLevel", property_value: ChangeLevel)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "CloneDestinationGrid"|"ScrollBuddy"|"CloneSourceGrid", property_value: CloneGrid)
---@overload fun(property_name: "Settings", property_value: CloningWindowSettings)
---@overload fun(property_name: "PoolColor"|"ActiveBackColor"|"EditMixInBackColor"|"ActiveTextColor"|"EditMixInNotOwnerBackColor"|"ActiveIconColor"|"SelectedIconColor"|"BackColor"|"SelectedOptionTextColor"|"TextColor"|"SelectedOptionBackColor"|"TextShadowColor"|"MixInBackColor"|"HighlightedColor"|"IconColor"|"SelectionColor"|"ColorLineNumberBackground"|"ColorLineNumberNormal"|"ProgIndicatorBackColor"|"ColorLineNumberSelected"|"ColorSelectedLineRect"|"OnColor"|"SelectedBackColor"|"KnobColorFlashedUp"|"OffColor"|"AlwaysOnColor"|"DisabledColor"|"HeadlineColor"|"SelectedIconColor"|"KnobColor"|"IndicatorBackColor"|"KnobColorFlashedDown"|"SlotColor"|"UpperColor"|"PreviewMixInColor"|"LowerColor"|"OnColor"|"OffColor"|"SelectedBackColor"|"AlwaysOnColor"|"SelectedTextColor"|"DisabledColor"|"EditMixInColor"|"EmptyBackColor"|"BorderColor"|"EditMixInNotOwnerColor"|"EmptyTextColor"|"IndicatorColor"|"RotateIconColor"|"DbgValueBackColor"|"DbgValueTextColor"|"ResizeLineColor"|"PreviewMixInColor"|"DefaultCellAltBackColor"|"EditMixInColor"|"DelimiterColor"|"BackColorFlashedDown"|"FixedBackColor"|"EditMixInNotOwnerColor"|"ActiveDelimiterColor"|"FixedTextColor"|"BackColor2"|"HeaderBackColor"|"IndicatorBack"|"HeaderAltBackColor"|"BackColorFlashedUp"|"ReadOnlyBackColor"|"HeaderTextColor"|"BlockerColor"|"SelectedBackColor"|"SelectedTextColor"|"NoCellBackColor"|"ReadOnlyAltBackColor"|"NonEmptyIndicatorColor"|"ReadOnlyTextColor"|"DefaultValueColor"|"DisabledColor"|"OnColor"|"FilterActiveColor"|"IndicatorIconBackColor"|"OffColor"|"GridColor"|"OverridesIndicatorBackColor"|"XYZTextColor"|"ValueTextColor"|"PoolColor"|"ValueActiveTextColor"|"ChildFreeIconColor"|"HasChildrenIconColor"|"SelectedTextColor"|"SelectionColor"|"HasSelectedChildrenIconColor"|"SelectedBackColor"|"FixedBackColor"|"ProgressColor"|"AdditionalInfoTextColor"|"DividerColor"|"BlinkBackColor"|"ProgIndicatorBackColor"|"SelectionColor"|"MessageColor"|"LevelColor"|"PeakColor"|"ScrollCellFrameColor"|"PoolColor"|"SelectedRowBorder"|"LevelColor"|"TriggerColor"|"KnobColor"|"NumberColor"|"UpperColor"|"MinorNumberColor"|"LowerColor"|"LassoColor"|"FaderLocked"|"GridColor"|"OverridesIndicatorBackColor"|"LowerPressedColor"|"SampleColor"|"UpperSampleColor"|"MatricksAreaActiveBackColor"|"RecipeEditColor"|"GridColor"|"TimeCursorColor"|"IconColor"|"IconHoverColor"|"SelectedIconColor"|"DeselectedIconColor"|"SensorColor"|"GridColor1"|"WarningColor"|"GridColor2"|"UpperColor"|"PeekColor"|"SignalColor"|"LowerColor", property_value: Color)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "DMXMode"|"DmxMode", property_value: DMXMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "Mode", property_value: DatumMode)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "Drive", property_value: Drive)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FixtureFID"|"FixtureCID", property_value: EmptyAsZeroFID)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "EncoderFunction", property_value: EncoderFunction)
---@overload fun(property_name: "Property", property_value: EncoderGroupType)
---@overload fun(property_name: "EncoderRing", property_value: EncoderRing)
---@overload fun(property_name: "EncoderType", property_value: EncoderType)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "Focus", property_value: FocusPriority)
---@overload fun(property_name: "FocusSearchPolicy", property_value: FocusSearchPolicy)
---@overload fun(property_name: "LowDpiFont"|"Font"|"TcFont", property_value: Font)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "IconsGrid", property_value: Gma3UI.IconsGrid)
---@overload fun(property_name: "IconsGridAnchors", property_value: Gma3UI.IconsGridAnchors[])
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "X"|"TextOffsetH"|"Y"|"W"|"H"|"TextOffsetV"|"IconOffsetV"|"IconOffsetH"|"ScrollBarHeight", property_value: Graphics.SizeDescriptor)
---@overload fun(property_name: "MaxSize"|"MinSize", property_value: Graphics.SizeDimension)
---@overload fun(property_name: "FixedHeaders"|"NormalHeaders"|"FixedCells"|"NormalCells", property_value: Graphics.UIGrid.GridArea)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "Mode", property_value: GridModeAgenda)
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "HotKey", property_value: HotKey)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "ArrayIndex"|"ArrayIndex", property_value: Index)
---@overload fun(property_name: "BackOffset", property_value: ItemGroupPosition)
---@overload fun(property_name: "KeyCode", property_value: KeyboardCodes)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "Target"|"Target", property_value: Mesh)
---@overload fun(property_name: "EscModalResult"|"CloseAction", property_value: ModalResult)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "MouseButtonType", property_value: MouseButtonTypes)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "Target"|"Target"|"TargetObject"|"SelectedRow"|"Target"|"Target"|"ScrollTarget"|"Target"|"EditTarget"|"Target"|"Target"|"Target"|"ExternScrollPos"|"AppearanceTarget"|"Target"|"Target"|"Target"|"CurrentUpdateObject"|"MainBuddy"|"Target"|"ScrollTarget"|"ScribbleTarget"|"WorkingDestination"|"EditTarget"|"Target"|"Target"|"Target"|"Target"|"Target"|"Target"|"Target"|"TargetObject"|"HistoryProvider"|"TextViewProvider"|"Context"|"Target"|"TargetObject"|"Target"|"EditTarget"|"Target", property_value: Object)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Settings", property_value: PSRPatchSheetSettings)
---@overload fun(property_name: "EncoderFunction", property_value: PhaserEncoderFunction)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "PolicyOnEnter", property_value: PolicyOnEnter)
---@overload fun(property_name: "PoolSettings"|"PoolSettings", property_value: PoolSettings)
---@overload fun(property_name: "SizeY"|"SizeX"|"SizeX"|"SizeY", property_value: PoolSizeFactor)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "EnabledItems", property_value: PropertyRadioButtonListEnabledItems)
---@overload fun(property_name: "SetType", property_value: PropertyRadioButtonListSetType)
---@overload fun(property_name: "ExecProxy", property_value: Proxy)
---@overload fun(property_name: "RowReductionPolicy"|"ColReductionPolicy", property_value: ReductionPolicy)
---@overload fun(property_name: "ViewW"|"ViewH", property_value: RequestedSize)
---@overload fun(property_name: "InternalRole", property_value: Roles)
---@overload fun(property_name: "ItemPlacementTypeV"|"ItemPlacementTypeH", property_value: ScrollItemPlacementType)
---@overload fun(property_name: "ScrollEntity"|"ScrollEntity", property_value: ScrollParamEntity)
---@overload fun(property_name: "Direction"|"Type"|"Direction"|"ScrollType"|"AutoNextCellDirection"|"Type"|"Direction"|"Type", property_value: ScrollType)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "Settings", property_value: ShowCreatorSettings)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "Mode", property_value: ShowfileSelectorMode)
---@overload fun(property_name: "TargetSound", property_value: Sound)
---@overload fun(property_name: "Band", property_value: SoundValues)
---@overload fun(property_name: "SpecialExecIndex"|"SpecialExecIndex"|"SpecialExecIndex", property_value: SpecialExecutor)
---@overload fun(property_name: "UIToControl", property_value: SplitterH_LeftRight)
---@overload fun(property_name: "UIToControl", property_value: SplitterV_TopBottom)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "IndicatorFrame"|"CursorTexture"|"TextureVertical"|"BorderTexture"|"TextureVerticalHover"|"ArrowRight"|"SelectedIcon"|"CountDownIcon"|"ArrowLeft"|"CollapsedIcon"|"SelectionFrame"|"DeselectedIcon"|"OnOffTexture"|"StopwatchIcon"|"SelectedIcon"|"HeadLineTexture"|"IndicatorIcon"|"SortAsc"|"SelectionBackgroundTexture"|"SortDesc"|"TitleButtonIcon"|"DeselectedIcon"|"Icon"|"KnobTexture"|"TriggerTexture"|"SignalTexture"|"SelectionFrame"|"Lasso"|"LockTexture"|"TitleButtonIcon"|"PinnedIcon"|"GearTexture"|"CursorTexture"|"SelectionBackgroundTexture"|"OverridesIndicator"|"Indicator"|"TextureNormal"|"TextureHover"|"ProgIndicator"|"IndicatorBackTexture"|"ProgIndicator"|"SampleTexture"|"IndicatorTexture"|"SelectionTexture"|"ExpandedTexture"|"ContractedTexture"|"DelimiterTexture"|"ExpandedIcon"|"Icon"|"CollapsedIcon"|"KnobTexture"|"SelectedIcon"|"BrushTexture"|"SelectionTexture"|"SlotTexture"|"ExpandedIcon"|"TextureHorizontal"|"DeselectedIcon"|"UpperTexture"|"SelectionFrame"|"SensorTexture"|"LowerTexture"|"UpperTexture"|"IconActive"|"SelectionTexture"|"OnOffTexture"|"LowerTexture"|"BlockerTexture"|"IconInactive"|"IndicatorBack"|"LogoIcon"|"TextureHorizontalHover"|"Texture", property_value: Texture)
---@overload fun(property_name: "Icons", property_value: Texture[])
---@overload fun(property_name: "Source", property_value: TimeCodeSource)
---@overload fun(property_name: "Position"|"Duration", property_value: TimePropertyValue)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "EncoderFunction", property_value: TimecodeEncoderFunction)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "Direction", property_value: ToolbarScrollType)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "Target"|"LabelLinkHandle"|"LinkedObject"|"TargetObject", property_value: UIObject)
---@overload fun(property_name: "UserRights", property_value: UserRights)
---@overload fun(property_name: "ValueRole", property_value: ValueRole)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "Settings"|"WindowSettings"|"SubWindowSettings"|"WindowSettings"|"WindowSettings"|"WindowSettings", property_value: WindowSettings)
---@overload fun(property_name: "DrawContent"|"ShowTcSlotAndTcMode"|"BackgroundButtonStyle"|"ContentStyle"|"ShowFileSegmentShowData"|"ReadOnly"|"ShowFileSegmentLocalSettings"|"ShowFileSegmentOutputStations"|"IgnoreIconForTextAlign"|"KeyRepeatEnabled"|"TextVertical"|"AutoNextCell"|"ShowFileSegmentDmxProtocols"|"DependsOnLinkedObject"|"TextAutoAdjust"|"TextUniform"|"SelectionOnFocusOnly"|"TargetIsAppearance"|"Local"|"DirectCommand"|"ShowNumber"|"DirectQuotation"|"AvoidScroll"|"InteractWithCommandline"|"ShowKeyboardButton"|"Rounded"|"Visible"|"TargetIsScribble"|"Secret"|"IndicatorBarEnabled"|"CanCoExistWithModal"|"CanBeEmbedded"|"SetPropertyOnlyOnTextChange"|"ShowLeftIcon"|"UserVisible"|"CalledFromCmdline"|"ShowRightIcon"|"Enabled"|"EditTitlebar"|"ShowAdditionalInfo"|"Interactive"|"SearchFocusTestParent"|"ShowLeftScribble"|"Transparent"|"ShowRightScribble"|"BlockClickThru"|"AllowBlocks"|"UserInteracted"|"IsMidiOut"|"ForceSmallMode"|"SkipTextIfIconExists"|"HasHover"|"State"|"ShowVisibleDay"|"ItemIndividualCorners"|"Separator"|"HasPressedAnimation"|"AutoCloseOnInput"|"ContentDriven"|"ContentWidth"|"WantsModal"|"ReadOnly"|"ShowLineNumbers"|"AutoClose"|"ContentHeight"|"ShowWhiteSpace"|"ForceContentMin"|"WantsNumericRedirect"|"AutoCloseOnOverlay"|"HighlightCurrentLine"|"CloseOnEscape"|"NewlineWithSpaces"|"IndirectEdit"|"ForceCursor"|"ScrollChangesSelection"|"IncludeTarget"|"FilterByName"|"InitialSaveEditTarget"|"EditTargetHasChanged"|"IgnoreBackdropPadding"|"MixInBackColorFromParent"|"FilterByManufacturer"|"ReactToPreview"|"StayAlwaysVisible"|"FilterByName"|"VisualisableScrollV"|"ReactToEdit"|"IgnoreRequestedSize"|"ScrollCellAutomatic"|"RelativeToDisplay"|"FilterByMode"|"ForceEncoderBar"|"ScrollCellAutomaticWithOffset"|"FilterByDescription"|"VisualisableScrollH"|"SuppressOverlayAutoClose"|"FilterByUsedOnly"|"EnterToExecute"|"ResetChildrenSize"|"IsClosing"|"AdjustInitialPosition"|"TextShadow"|"IsMainBuddy"|"UpdateSettingsVisibility"|"UseSimplifiedResize"|"InitialSaveEditTarget"|"BigMode"|"DriveReset"|"EditTargetHasChanged"|"AutoCreateFromProperties"|"OverrideKeybSC"|"UseEditorTarget"|"ReactToPreview"|"SuppressModeSwitch"|"ForceHideCategories"|"ReactToEdit"|"ScreenEncoder"|"UseDynamicIndicatorColor"|"OnlyVisible"|"IsWorldCoordinateSystemActive"|"HasFocus"|"ResetIfUntargeted"|"TryFitIntoSecondary"|"IsCameraFocusOnSelectedItem"|"HideFocusFrame"|"EditAllowedDelete"|"Inverted"|"Content"|"StealFocusAfterSelect"|"VisibleOnlyInAlpha"|"CmdlineInteraction"|"TryAvoidZeroes"|"TitleButtonBool"|"VisibleOnlyInBeta"|"TargetCmdlineInteraction"|"TryFitMainIfContentDriven"|"DrawShortcutInfo"|"VisibleOnlyInRelease"|"EditAllowedAdd"|"SeparatorSupport"|"ClickNearest"|"CreateAndEdit"|"ModifyTextureLayout"|"SmallResizeArea"|"AddTargets"|"VisibleInAlpha"|"AutoClose"|"ProvideEmpty"|"VisibleInBeta"|"ObserveSelectionChange"|"MixPercentAndHexDecModesAllowed"|"Features"|"VisibleInRelease"|"AllChannelSets"|"FeatureGroups"|"FeatureGroupsOnly"|"PanScrollArea"|"ShowFullSettings"|"WeakAlternationInHeader"|"Toggle"|"ForceFocusOnChange"|"PanScroll"|"WeakAlternationInData"|"DrawInbetweenValues"|"ShowLabel"|"ShowCSHelp"|"ValueAutoAdjust"|"ShowValue"|"DataAsIs"|"AutoHide"|"WorkWithGrid"|"IsScribbleNew"|"IndirectEdit"|"IsAppearanceNew"|"DirectProperty"|"SearchFocusTestParent"|"DefaultAction"|"CharAction"|"Undo"|"ChangeDestination"|"HiglightActiveCue"|"ValueTextShadow"|"WorkWithGrid"|"IgnoreActiveForEnums"|"DimmerCueOnly"|"Auto"|"ShowOldVersions"|"UseCommandlineClick"|"SetIconAsActiveInactive"|"ExclusivePropertyChange"|"NoEmptyNames"|"EditNewObject"|"UseTabRegistry"|"UseGridColor"|"PositionBeneathFinger"|"MixInBackColorFromParentRecursive"|"AutoTexture"|"DefaultAction"|"TrackEdit"|"ExpandContent"|"DefaultMarginOnBorders"|"TrackWorld"|"EncoderUseDisplay"|"UseDefaultValue"|"SmallMode"|"UseComposedText"|"ShowSelectionCount"|"ForceFastFade"|"ShowAdditionalInfo"|"AutoScrollToEnd"|"AutoEnabled"|"TextChangeOnEnter"|"CloseProhibited"|"NoEmptyNames"|"AllowAddContent"|"AllowAddNewline"|"ShowUnpatchedOnly"|"ReactToRecipeEdit"|"DisplayLevel"|"ScrollOpposite"|"AllowMergeChildren"|"ShowManualCueSelection"|"AllowedInvisible"|"AllowEdit"|"ContentChanged"|"ForceCursor"|"PrintCurrentValue"|"CanProvideUiGridSelection"|"ReactToRecipeEdit"|"LongPressVK"|"AllowFilterContent"|"DirectQuotation"|"AutoCloseAllowed"|"PrintMaxValue"|"FilterBlockUIEnabled"|"GapsForExpanded"|"UseUserProfileSettings"|"ScrollOutEnabled"|"CloseOnClick"|"VScrollOnHeader"|"PrimaryHasFocus"|"ConvertCursorToTabAtBoundaries"|"IsInExport", property_value: YesNo|boolean)
---@overload fun(property_name: "DrawGradient"|"AllIndexesCollected"|"AutoSetWindowSettings"|"IsScribbleAvailable"|"IsCloneDestination"|"IsAppearanceAvailable"|"FadeEncoder"|"UseSpecialTimezone"|"CheckForScreenEncoders"|"IsNoteAvailable"|"ChangeDestination"|"Expanded"|"IsPlaying"|"AllowSorting"|"Blink"|"ScribbleIsEmpty", property_value: boolean)
---@overload fun(property_name: "ChangeActive", property_value: fun(childName: string) : boolean)
---@overload fun(property_name: "Solve"|"CallP1"|"OnTitleClick"|"StoreP2"|"Close"|"CallP2"|"StoreP1"|"OnTitleClick"|"CloseConfirm"|"StoreP3"|"OnTitleClick"|"CloseCancel"|"Update"|"CallP3"|"StoreP4"|"CallP4", property_value: fun(dummyStr: string) : boolean)
---@overload fun(property_name: "OnUniverseUpClicked"|"OnUnpatchClicked"|"OnPatchToClicked"|"OnUniverseDownClicked", property_value: fun(dummyStr: string, button: MouseButtonTypes, X: integer, Y: integer) : boolean)
---@overload fun(property_name: "OnBreakSelected"|"OnBreakPatched"|"OnDBObjectSelected"|"OnAddressSelected", property_value: fun(dummyStr: string, column: integer, row: integer) : boolean)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "Clear", property_value: fun(dummyString: string) : boolean)
---@overload fun(property_name: "ShowMessage"|"HideMessage", property_value: fun(message: string) : boolean)
---@overload fun(property_name: "ChangeText", property_value: fun(newTextStr: string) : boolean)
---@overload fun(property_name: "SetPrompt", property_value: fun(prompt: string) : boolean)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "MoveStart"|"ResizeStart"|"OnListRefDone"|"ResizeEnd"|"UrlChanged"|"ProgressChanged"|"Scrolled"|"StatusChanged"|"TooltipChanged"|"OnCreateNewAppearance"|"MoveStart"|"ScrolledToEndV"|"ResizeEnd"|"PathChanged"|"OnUserProfileChanged"|"FilterChanged"|"Execute"|"ResizeStart"|"Execute"|"LassoFinished"|"DescriptionChanged"|"TextChanged"|"OnScreenPushed"|"ScribbleTargetChanged"|"OnWrongChar"|"OnCreateNewAppearance"|"OnCreateNewScribble"|"AppearanceTargetChanged", property_value: fun(str: string))
---@overload fun(property_name: "TimecodeForward"|"TimecodeStop"|"OpenVK"|"TimecodePlay"|"SelectAll"|"TimecodePrevMarker"|"OnFunction"|"TimecodeNextMarker"|"DeSelect"|"SelectionCopy"|"SetCursorToEnd"|"SelectionCut"|"SelectionPaste"|"TimecodeAddEvent"|"TimecodeAddMultiEvents"|"OnFixtureSourceChanged"|"TimecodeAddTimeRange"|"TimecodeAddTimeMarker"|"SetUrlA"|"GoBack"|"OnCreateNewAppearance"|"GoFwd"|"CheckAutoClose"|"Reload"|"OnNavigate"|"RequestMemUsage"|"OnCheckSubPoolSelector"|"SetDateToday"|"OnInput"|"ApplyScribble"|"SetTimeNow"|"OnState"|"OnSelectDataPool"|"RevertScribble"|"OnCommand"|"OnCreateNewScribble"|"DeleteFilterItem"|"OnTitle"|"OnCollectAllIndexes"|"AddFilterItem"|"ResetMouse"|"SetToTop"|"DeleteClicked"|"ScrollPageDown"|"Play"|"OnFocusLost"|"TBDeleteAll"|"Undo"|"Pause"|"TBLoadDefaults"|"Redo"|"Stop"|"ClearScribble"|"ClearSelection"|"SetText"|"OnApplyColorToCurves"|"InsertText"|"ClearText"|"DeleteOld"|"OnToolOperate"|"SelectAllRows"|"SaveEditTarget"|"ClearFilter"|"ScrollAction"|"RevertEditTarget"|"OnClearCmdline"|"MoveStart"|"ToggleListRef"|"ExpandAll"|"ResizeEnd"|"ScrollToEnd"|"SetCursorToEnd"|"OnSelectedTreeItem"|"SaveToDefault"|"OnScrolledTreeItem"|"LoadFromDefault"|"KeyPress"|"SelectedFixture"|"SaveEditTarget"|"ResizeStart"|"ResizeStart"|"MoveStart"|"Context"|"SelectedManufacturer"|"ResizeEnd"|"RememberSelection"|"RevertEditTarget"|"MapClicked"|"InitGrids"|"Context"|"UpdateEncoderBar"|"TabChanged"|"OnSpecialButtonClicked"|"OnExpandAll"|"EnumClicked"|"OnCollapseAll"|"OnExpandSelected"|"Search"|"OnClearSelection"|"OnStageChanged"|"SelectAll"|"SelectNothing"|"OnDataPoolChanged"|"OnSetSelectorVisibility"|"SwitchExpansion"|"OnCollapseAll"|"OnZoomToFit"|"OnSetRecalcCenterOfGravity"|"FunctionSelectorChanged"|"EncoderReadoutSelectorChanged"|"OnEditCurrentLayout"|"SetPath"|"DeleteSelectedFiles"|"SetFilter"|"GoUp"|"SelectFirstFile"|"ScrollToFirstFile"|"OnPatchToNextFree"|"OnSwipeMenu"|"ProgressChanged"|"OnMoveToUniverse"|"AutoScroll"|"SGResizeStart"|"SGResizeEnd"|"OpenAtFilter"|"OnSwipeMenu"|"ToggleAtFilter"|"OnPatchToClicked"|"OnShowUnpatchedClicked"|"SGResizeStart"|"SGResizeEnd"|"MeasureColor"|"SetPlus"|"DarkCalibrate"|"SetMinus"|"FindDevice"|"ShowAnimation"|"ResetView"|"ZoomIn"|"ZoomOut"|"ChangedActiveTab"|"TimecodePause"|"TimecodeBackward"|"TimecodeRecord", property_value: fun(str: string) : boolean)
---@overload fun(property_name: "ResizeMove", property_value: fun(str: string, AbsX: integer, AbsY: integer))
---@overload fun(property_name: "MouseUp"|"Clicked"|"MouseDown"|"DoubleClicked"|"MouseDownHold", property_value: fun(str: string, Button: MouseButtonTypes, X: integer, Y: integer))
---@overload fun(property_name: "ResizeMove"|"ResizeMove"|"Move"|"Move", property_value: fun(str: string, DeltaX: integer, DeltaY: integer))
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "MouseOverHold"|"MouseEnter"|"MouseUpLeft"|"MouseUpRight"|"ClickedLeft"|"ClickedRight"|"MouseDownLeft"|"MouseDownRight"|"MouseLeave", property_value: fun(str: string, X: integer, Y: integer))
---@overload fun(property_name: "MoveEnd"|"MoveEnd"|"OnVisible"|"ResizeEnd", property_value: fun(str: string, bool: boolean))
---@overload fun(property_name: "MoveEnd"|"ResizeEnd", property_value: fun(str: string, bool: boolean) : boolean)
---@overload fun(property_name: "ResizeStart"|"OnBeforeEdit"|"OnAfterEdit"|"OnSelectionAfterCmd"|"SelectionChanged"|"UndoRedoChanged", property_value: fun(str: string, int1: integer, int2: integer))
---@overload fun(property_name: "SGResizeMove"|"ResizeStart"|"ResizeMove"|"Move"|"SGResizeMove"|"SelectCell"|"Resize"|"ResizeMove"|"SelectRange"|"CallSubMenu"|"Move", property_value: fun(str: string, int1: integer, int2: integer) : boolean)
---@overload fun(property_name: "TabChanged", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean))
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "TabClickedOnCurrent"|"OnSelectedItem", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean))
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "OnClick"|"ActionSetPriority"|"HardkeyMouseUp"|"ReloadCamera"|"HardkeyMouseDown"|"OnClick"|"FactoryDefaults"|"RotateToCircleCenter"|"Rotate90ToLine"|"ResetUnusedAxis"|"OnClick"|"ReloadRenderQuality"|"ResetRotation"|"Oops"|"ReloadCamera"|"ResetPosition"|"OnShow3dSettings"|"Show3DSettings"|"ResetCamera"|"CenterPosition"|"AnalyzeMeshPool"|"ArrangePosition"|"SelectionToGrid", property_value: fun(str: string, int1: integer, int2: integer, int3: integer) : boolean)
---@overload fun(property_name: "GestureClick"|"GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer))
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "OnCellMouseDoubleClicked"|"OnCellMouseDown"|"OnCellMouseDownHold"|"OnCellMouseUp"|"OnCellMouseClicked", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer, int5: integer))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "OnSelectedColumn"|"OnSelectedRow"|"MemUsageUpdated"|"OnTargetChanged"|"OnTargetChanged"|"OnSelectedItem", property_value: fun(str: string, int: integer))
---@overload fun(property_name: "SortByColumn"|"AddSelectedLines"|"OnChar"|"ScrollVertical"|"ScrollHorizontal"|"ReTriggerInit"|"ChangeTarget"|"SetFPSLimit"|"OnChar"|"ReTriggerInit"|"AddSelectedFixtures"|"ScrollToRow"|"ClearGrid"|"GridMoveUp"|"GridMoveDown"|"GridCut"|"ChangeTarget"|"GridCopy"|"GridPaste"|"GridAdd"|"GridDelete"|"SelectRow"|"GridFillUp"|"JumpToNextLine"|"AddRow"|"SelectionChanged"|"GridUnify"|"JumpToPreviousLine"|"AddMissingLines"|"SelectColumn", property_value: fun(str: string, int: integer) : boolean)
---@overload fun(property_name: "KeyDown"|"KeyUp", property_value: fun(str: string, keyCode: VirtualKeyCode, bool1: boolean, bool2: boolean, bool3: boolean))
---@overload fun(property_name: "ForceScale"|"Seek", property_value: fun(str: string, num: number) : boolean)
---@overload fun(property_name: "FocusLost"|"FocusGet", property_value: fun(str: string, obj1: Object, obj2: Object))
---@overload fun(property_name: "OnSetEditTarget"|"OnSetEditTarget"|"OnSetEditTarget"|"LinkedObjectChanged"|"OnLoad", property_value: fun(str: string, obj: Object))
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "TouchUpdate"|"TouchStart"|"TouchEnd", property_value: fun(str: string, pointID: integer, X: integer, Y: integer))
---@overload fun(property_name: "OnUpdateTitle"|"OnUpdateTitle", property_value: fun(str: string, str: string))
---@overload fun(property_name: "CharInput", property_value: fun(str: string, utf32Char: integer))
---@overload fun(property_name: "Changed", property_value: fun(str: string, value: integer))
---@overload fun(property_name: "Set", property_value: fun(str: string, value: integer) : boolean)
---@overload fun(property_name: "OpenSequenceFilter"|"FlipLeftRight"|"OpenGroupFilter"|"OpenPresetFilter"|"DoReset"|"SetText"|"ObtainCurrentCue"|"InitFirst"|"InitTargetList"|"AddText"|"DoClone"|"OpenWorldFilter"|"InsertText"|"OpenLayoutFilter"|"SelectFirst"|"ChangeCloningViewMode"|"AllItemsToAll"|"AllItemsToNone", property_value: fun(text: string) : boolean)
---@overload fun(property_name: "OptionHeight"|"ShowFileSegmentsMask"|"State"|"SelectedRow"|"SelectedColumn"|"RasterHeight"|"RasterWidth"|"Distance"|"Hour"|"ItemSize"|"Minute"|"VisibleItemCount"|"FrameWidth"|"AutoFitColumn"|"Second"|"SlotIndex"|"Day"|"GridVersion"|"MaxTextLength"|"Priority"|"Year"|"Direction"|"Selector"|"AutoCloseValue"|"MaxIndicatorSize"|"UiGroupId"|"UndoCount"|"RedoCount"|"PatchOffset"|"FilterMask"|"VisibleFixturesCount"|"SubDestination"|"HeadLineDimension"|"ButtonDimension"|"SlotDimension"|"ColorIndicatorHeight"|"MaxValue"|"MinValue"|"MinCellSize"|"LineHeightAdd"|"IgnoreChildren"|"BigModeColumns"|"LineSpacing"|"TitleButtonUInt64"|"BigModeRows"|"MaxValue"|"DelimiterSize"|"ActiveSource"|"TitleButtonInt64"|"TitleButtonPopup"|"GridDelta"|"LabelAreaHeight"|"ExecFrom"|"ForceIntensity"|"FixtureCount"|"ExecBarToDraw"|"FirstRow"|"DefaultMargin"|"LastRow"|"ExecutorIndex"|"Columns"|"Rows"|"BreakIdx"|"CellWidth"|"CellHeight"|"PatchOffset"|"ExecRowCount"|"ExecutorIndex"|"BlockWidth"|"ExecColCount"|"BlockHeight"|"ExecutorIndex"|"RasterHeight"|"FrameThickness"|"RasterWidth"|"ScrollCellFrameThickness"|"SpecialExecOffset"|"LevelDistance"|"IncrementFactor"|"ColumnResizeMaxDeviation"|"Mask"|"LevelLimit"|"Mask"|"Page"|"LevelLimit"|"Border", property_value: integer)
---@overload fun(property_name: "RunningPlaybacks", property_value: integer[])
---@overload fun(property_name: "Value"|"EncoderResolution"|"IconScale"|"CurrentFps"|"Progress"|"ItemPlacementOffsetFactorH"|"ScaleAll"|"RatioAll"|"ItemPlacementOffsetFactorV", property_value: number)
---@overload fun(property_name: "DataType"|"SelectionType"|"CellType"|"ToolTip"|"HelpTopic"|"SettingsType"|"ReferencedTitleButton"|"ItemType"|"TargetPath"|"DirectPrefix"|"Cursor"|"InitialTab"|"InitialSubTab"|"System"|"ItemFilter"|"DefaultTitle"|"EditEncoderBar"|"Content"|"ControlEncoderBar"|"FixtureName"|"Property"|"EditEncoderBar"|"ControlEncoderBar"|"ForcedInitialTab"|"BuddyGroupId"|"Filter"|"Property"|"System"|"SignalValue"|"SignalValueHold"|"PrivacyPolicyUrl"|"FilterComposed"|"Property"|"TrademarksUrl"|"Value"|"System"|"Value"|"ReleaseNotesUrl"|"AppearanceSourceClassName"|"Destination"|"TargetPropertyName"|"TextLeftCorner"|"EmptyName"|"System"|"InsertType"|"LedToken"|"ActiveChild"|"Property"|"System"|"CurrentSelectedShowFile"|"Property"|"Property"|"FuzzyFilter"|"FuzzyFilterExcludeEnd"|"EditEncoderBar"|"BaseFilter"|"ImportOptions"|"WarningTooltip"|"Value"|"SelectedFile"|"SwipeMenu"|"StrContext"|"BarText"|"AuxProperty"|"Property"|"AdditionalInfo"|"VKTitleHint"|"DummyComposedText"|"Property"|"SwipeMenu"|"VKPluginName"|"Destination"|"Prompt"|"Filter"|"EmptyText"|"Message"|"Property"|"FixtureToMeasure"|"DirectPrefix"|"Text", property_value: string)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "OptionAreaMargin"|"Margin"|"ContentAreaMargin"|"LabelAreaMargins"|"ValueAreaMargins"|"Anchors"|"Padding", property_value: {left: integer, right: integer, top: integer, bottom: integer})
---@overload fun(property_name: "WindowRect"|"AbsRect"|"AbsClientRect", property_value: {left: number, right: number, top: number, bottom: number})
function Item:SetPrompt(property_name, property_value) end
---@overload fun(property_name: "SideSize", property_value: ALSideSizeSpecial)
---@overload fun(property_name: "AlignmentH"|"TextAlignmentH"|"IconAlignmentH"|"ValueAlignmentH"|"LogoIconAlignmentH"|"IconAlignmentH"|"KeyboardIconAlignmentH", property_value: AlignmentH)
---@overload fun(property_name: "AlignmentV"|"TextAlignmentV"|"IconAlignmentV"|"ValueAlignmentV"|"LogoIconAlignmentV"|"IconAlignmentV"|"KeyboardIconAlignmentV", property_value: AlignmentV)
---@overload fun(property_name: "Appearance", property_value: Appearance)
---@overload fun(property_name: "Direction", property_value: AutoLayoutScrollType)
---@overload fun(property_name: "Mode", property_value: BlinkingButtonMode)
---@overload fun(property_name: "Mode", property_value: CalculatorMode)
---@overload fun(property_name: "GroupedCellsCount", property_value: CellGrouping)
---@overload fun(property_name: "TriggerIndirectInitLevel"|"BlockLevel", property_value: ChangeLevel)
---@overload fun(property_name: "ChildrenFillPolicy", property_value: ChildrenFillPolicy)
---@overload fun(property_name: "FixtureClass", property_value: Class)
---@overload fun(property_name: "ScrollBuddy"|"CloneSourceGrid"|"CloneDestinationGrid", property_value: CloneGrid)
---@overload fun(property_name: "Settings", property_value: CloningWindowSettings)
---@overload fun(property_name: "BackColor"|"TextColor"|"TextShadowColor"|"MixInBackColor"|"HighlightedColor"|"GridColor"|"SampleColor"|"UpperSampleColor"|"HeadlineColor"|"KnobColor"|"KnobColorFlashedUp"|"KnobColorFlashedDown"|"SlotColor"|"UpperColor"|"LowerColor"|"OnColor"|"OffColor"|"AlwaysOnColor"|"DisabledColor"|"BorderColor"|"IndicatorColor"|"ProgressColor"|"UpperColor"|"LowerColor"|"DefaultCellAltBackColor"|"FixedBackColor"|"FixedTextColor"|"HeaderBackColor"|"HeaderAltBackColor"|"HeaderTextColor"|"SelectedBackColor"|"SelectedTextColor"|"NoCellBackColor"|"ReadOnlyBackColor"|"ReadOnlyAltBackColor"|"ReadOnlyTextColor"|"DefaultValueColor"|"DisabledColor"|"FilterActiveColor"|"IndicatorBackColor"|"ScrollCellFrameColor"|"SelectedRowBorder"|"LassoColor"|"ResizeLineColor"|"TimeCursorColor"|"GridColor"|"IndicatorIconBackColor"|"PreviewMixInColor"|"EditMixInColor"|"EditMixInNotOwnerColor"|"SelectionColor"|"ColorLineNumberBackground"|"ColorLineNumberNormal"|"ColorLineNumberSelected"|"ColorSelectedLineRect"|"PreviewMixInColor"|"EditMixInColor"|"EditMixInNotOwnerColor"|"PoolColor"|"PoolColor"|"DelimiterColor"|"ActiveDelimiterColor"|"BlockerColor"|"PoolColor"|"IconColor"|"IconHoverColor"|"ActiveBackColor"|"ActiveTextColor"|"ActiveIconColor"|"ValueTextColor"|"ValueActiveTextColor"|"NonEmptyIndicatorColor"|"RotateIconColor"|"DbgValueBackColor"|"DbgValueTextColor"|"SelectedIconColor"|"SelectedIconColor"|"DeselectedIconColor"|"SelectedBackColor"|"SelectedTextColor"|"EmptyBackColor"|"EmptyTextColor"|"SelectedIconColor"|"ProgIndicatorBackColor"|"SelectedOptionTextColor"|"SelectedOptionBackColor"|"OnColor"|"OffColor"|"AlwaysOnColor"|"DisabledColor"|"OverridesIndicatorBackColor"|"XYZTextColor"|"MatricksAreaActiveBackColor"|"ProgIndicatorBackColor"|"OverridesIndicatorBackColor"|"RecipeEditColor"|"ChildFreeIconColor"|"HasChildrenIconColor"|"HasSelectedChildrenIconColor"|"OnColor"|"OffColor"|"NumberColor"|"MinorNumberColor"|"EditMixInBackColor"|"EditMixInNotOwnerBackColor"|"BlinkBackColor"|"SelectionColor"|"MessageColor"|"IconColor"|"SensorColor"|"WarningColor"|"PeekColor"|"SelectedBackColor"|"SelectedTextColor"|"SelectedBackColor"|"AdditionalInfoTextColor"|"DividerColor"|"KnobColor"|"UpperColor"|"LowerColor"|"FaderLocked"|"LowerPressedColor"|"BackColor2"|"IndicatorBack"|"BackColorFlashedUp"|"BackColorFlashedDown"|"SelectionColor"|"FixedBackColor"|"LevelColor"|"TriggerColor"|"LevelColor"|"PeakColor"|"GridColor"|"GridColor1"|"GridColor2"|"SignalColor", property_value: Color)
---@overload fun(property_name: "ColorEncoderFunction", property_value: ColorEncoderFunction)
---@overload fun(property_name: "ShownCue", property_value: Cue)
---@overload fun(property_name: "CueDst", property_value: CueCopyDst)
---@overload fun(property_name: "CueDstOp", property_value: CueCopyDstMode)
---@overload fun(property_name: "CueSrc", property_value: CueCopySrc)
---@overload fun(property_name: "CueOnly", property_value: CueOnly)
---@overload fun(property_name: "CueOperationMode", property_value: CueOperationMode)
---@overload fun(property_name: "DMXMode"|"DmxMode", property_value: DMXMode)
---@overload fun(property_name: "SelectedAddr", property_value: DMXPropertyAddress)
---@overload fun(property_name: "Mode", property_value: DatumMode)
---@overload fun(property_name: "EditTools", property_value: DmxCurveEditTool)
---@overload fun(property_name: "Drive", property_value: Drive)
---@overload fun(property_name: "PresetPoolType", property_value: DynamicPresetPool)
---@overload fun(property_name: "FixtureQuantity", property_value: EmptyAsZero)
---@overload fun(property_name: "FixtureFID"|"FixtureCID", property_value: EmptyAsZeroFID)
---@overload fun(property_name: "Context", property_value: EncoderBarContext)
---@overload fun(property_name: "EncoderFunction", property_value: EncoderFunction)
---@overload fun(property_name: "Property", property_value: EncoderGroupType)
---@overload fun(property_name: "EncoderRing", property_value: EncoderRing)
---@overload fun(property_name: "EncoderType", property_value: EncoderType)
---@overload fun(property_name: "FixedColumns", property_value: FixedColumns)
---@overload fun(property_name: "FixtureLayer", property_value: FixtureLayer)
---@overload fun(property_name: "Focus", property_value: FocusPriority)
---@overload fun(property_name: "FocusSearchPolicy", property_value: FocusSearchPolicy)
---@overload fun(property_name: "Font"|"LowDpiFont"|"TcFont", property_value: Font)
---@overload fun(property_name: "FunctionMode", property_value: FunctionMode)
---@overload fun(property_name: "IconsGrid", property_value: Gma3UI.IconsGrid)
---@overload fun(property_name: "IconsGridAnchors", property_value: Gma3UI.IconsGridAnchors[])
---@overload fun(property_name: "ActiveController", property_value: Gma3UI.WindowFixturetypeVisualizer.ActiveController)
---@overload fun(property_name: "X"|"Y"|"W"|"H"|"IconOffsetH"|"IconOffsetV"|"TextOffsetH"|"TextOffsetV"|"ScrollBarHeight", property_value: Graphics.SizeDescriptor)
---@overload fun(property_name: "MinSize"|"MaxSize", property_value: Graphics.SizeDimension)
---@overload fun(property_name: "FixedHeaders"|"FixedCells"|"NormalHeaders"|"NormalCells", property_value: Graphics.UIGrid.GridArea)
---@overload fun(property_name: "ContentFilter", property_value: GridContentFilter)
---@overload fun(property_name: "Mode", property_value: GridModeAgenda)
---@overload fun(property_name: "ExternalSettings", property_value: GridSettings)
---@overload fun(property_name: "HotKey", property_value: HotKey)
---@overload fun(property_name: "FixtureIDType", property_value: IDs)
---@overload fun(property_name: "ImageSource", property_value: ImageSource)
---@overload fun(property_name: "ArrayIndex"|"ArrayIndex", property_value: Index)
---@overload fun(property_name: "BackOffset", property_value: ItemGroupPosition)
---@overload fun(property_name: "KeyCode", property_value: KeyboardCodes)
---@overload fun(property_name: "Layout", property_value: Layout)
---@overload fun(property_name: "MeasurementStatus", property_value: MeasurementStatus)
---@overload fun(property_name: "Target"|"Target", property_value: Mesh)
---@overload fun(property_name: "CloseAction"|"EscModalResult", property_value: ModalResult)
---@overload fun(property_name: "Month", property_value: Month)
---@overload fun(property_name: "MouseButtonType", property_value: MouseButtonTypes)
---@overload fun(property_name: "MoveValueToPart", property_value: MoveValueToPart)
---@overload fun(property_name: "Target"|"ScrollTarget"|"TargetObject"|"TargetObject"|"Target"|"MainBuddy"|"WorkingDestination"|"Context"|"Target"|"SelectedRow"|"EditTarget"|"EditTarget"|"EditTarget"|"CurrentUpdateObject"|"Target"|"Target"|"ScrollTarget"|"Target"|"ScribbleTarget"|"Target"|"AppearanceTarget"|"Target"|"Target"|"Target"|"Target"|"Target"|"Target"|"HistoryProvider"|"Target"|"Target"|"TargetObject"|"Target"|"Target"|"Target"|"Target"|"Target"|"ExternScrollPos"|"TextViewProvider"|"Target"|"Target", property_value: Object)
---@overload fun(property_name: "SelectedElements", property_value: Object[])
---@overload fun(property_name: "Settings", property_value: PSRPatchSheetSettings)
---@overload fun(property_name: "EncoderFunction", property_value: PhaserEncoderFunction)
---@overload fun(property_name: "PlaybackWindowSettings", property_value: PlaybackWindowSettings)
---@overload fun(property_name: "PolicyOnEnter", property_value: PolicyOnEnter)
---@overload fun(property_name: "PoolSettings"|"PoolSettings", property_value: PoolSettings)
---@overload fun(property_name: "SizeX"|"SizeY"|"SizeX"|"SizeY", property_value: PoolSizeFactor)
---@overload fun(property_name: "PoolType", property_value: Pooltype)
---@overload fun(property_name: "EnabledItems", property_value: PropertyRadioButtonListEnabledItems)
---@overload fun(property_name: "SetType", property_value: PropertyRadioButtonListSetType)
---@overload fun(property_name: "ExecProxy", property_value: Proxy)
---@overload fun(property_name: "RowReductionPolicy"|"ColReductionPolicy", property_value: ReductionPolicy)
---@overload fun(property_name: "ViewW"|"ViewH", property_value: RequestedSize)
---@overload fun(property_name: "InternalRole", property_value: Roles)
---@overload fun(property_name: "ItemPlacementTypeV"|"ItemPlacementTypeH", property_value: ScrollItemPlacementType)
---@overload fun(property_name: "ScrollEntity"|"ScrollEntity", property_value: ScrollParamEntity)
---@overload fun(property_name: "ScrollType"|"AutoNextCellDirection"|"Type"|"Type"|"Direction"|"Direction"|"Type"|"Direction", property_value: ScrollType)
---@overload fun(property_name: "Target", property_value: Sequence)
---@overload fun(property_name: "SetupType", property_value: SetupType)
---@overload fun(property_name: "Settings", property_value: ShowCreatorSettings)
---@overload fun(property_name: "ShowCreatorType", property_value: ShowCreatorType)
---@overload fun(property_name: "Mode", property_value: ShowfileSelectorMode)
---@overload fun(property_name: "TargetSound", property_value: Sound)
---@overload fun(property_name: "Band", property_value: SoundValues)
---@overload fun(property_name: "SpecialExecIndex"|"SpecialExecIndex"|"SpecialExecIndex", property_value: SpecialExecutor)
---@overload fun(property_name: "UIToControl", property_value: SplitterH_LeftRight)
---@overload fun(property_name: "UIToControl", property_value: SplitterV_TopBottom)
---@overload fun(property_name: "CueStoreOp", property_value: StoreMode)
---@overload fun(property_name: "Texture"|"SampleTexture"|"KnobTexture"|"SlotTexture"|"UpperTexture"|"LowerTexture"|"OnOffTexture"|"BorderTexture"|"HeadLineTexture"|"UpperTexture"|"LowerTexture"|"Indicator"|"IndicatorBack"|"IndicatorFrame"|"Lasso"|"SortAsc"|"SortDesc"|"SelectionFrame"|"LockTexture"|"GearTexture"|"SelectionFrame"|"IndicatorIcon"|"ExpandedIcon"|"CollapsedIcon"|"CursorTexture"|"SelectionBackgroundTexture"|"TitleButtonIcon"|"DelimiterTexture"|"SelectionFrame"|"BlockerTexture"|"TitleButtonIcon"|"ExpandedTexture"|"ContractedTexture"|"TextureNormal"|"TextureHover"|"TextureHorizontal"|"TextureHorizontalHover"|"TextureVertical"|"TextureVerticalHover"|"Icon"|"IconActive"|"IconInactive"|"SelectedIcon"|"DeselectedIcon"|"SelectedIcon"|"DeselectedIcon"|"PinnedIcon"|"SelectedIcon"|"DeselectedIcon"|"ProgIndicator"|"ProgIndicator"|"OverridesIndicator"|"LogoIcon"|"ExpandedIcon"|"CollapsedIcon"|"OnOffTexture"|"CountDownIcon"|"StopwatchIcon"|"CursorTexture"|"ArrowRight"|"ArrowLeft"|"SelectionBackgroundTexture"|"Icon"|"SensorTexture"|"BrushTexture"|"KnobTexture"|"IndicatorBackTexture"|"IndicatorTexture"|"TriggerTexture"|"SelectionTexture"|"SignalTexture"|"SelectionTexture"|"SelectionTexture", property_value: Texture)
---@overload fun(property_name: "Icons", property_value: Texture[])
---@overload fun(property_name: "Source", property_value: TimeCodeSource)
---@overload fun(property_name: "Duration"|"Position", property_value: TimePropertyValue)
---@overload fun(property_name: "CurrentTimeView", property_value: TimeView)
---@overload fun(property_name: "EncoderFunction", property_value: TimecodeEncoderFunction)
---@overload fun(property_name: "Grid", property_value: TimecodeGrid)
---@overload fun(property_name: "Direction", property_value: ToolbarScrollType)
---@overload fun(property_name: "TrackingShield", property_value: TrackingShieldPopup)
---@overload fun(property_name: "LabelLinkHandle"|"Target"|"TargetObject"|"LinkedObject", property_value: UIObject)
---@overload fun(property_name: "UserRights", property_value: UserRights)
---@overload fun(property_name: "ValueRole", property_value: ValueRole)
---@overload fun(property_name: "WindowAppearance", property_value: WindowAppearance)
---@overload fun(property_name: "WindowScrollPositions", property_value: WindowScrollPositions)
---@overload fun(property_name: "WindowSettings"|"WindowSettings"|"SubWindowSettings"|"WindowSettings"|"WindowSettings"|"Settings", property_value: WindowSettings)
---@overload fun(property_name: "TextVertical"|"TextAutoAdjust"|"TextUniform"|"Visible"|"CanCoExistWithModal"|"UserVisible"|"Enabled"|"Interactive"|"Transparent"|"BlockClickThru"|"UserInteracted"|"HasHover"|"Separator"|"HasPressedAnimation"|"ContentDriven"|"ContentWidth"|"ContentHeight"|"ForceContentMin"|"WantsNumericRedirect"|"IgnoreBackdropPadding"|"MixInBackColorFromParent"|"IgnoreRequestedSize"|"ForceEncoderBar"|"SuppressOverlayAutoClose"|"IsClosing"|"TextShadow"|"HasFocus"|"HideFocusFrame"|"VisibleOnlyInAlpha"|"VisibleOnlyInBeta"|"VisibleOnlyInRelease"|"ClickNearest"|"VisibleInAlpha"|"VisibleInBeta"|"VisibleInRelease"|"PrintCurrentValue"|"PrintMaxValue"|"UseDynamicIndicatorColor"|"ResetIfUntargeted"|"DrawInbetweenValues"|"WeakAlternationInHeader"|"WeakAlternationInData"|"ScrollOpposite"|"ExpandContent"|"DefaultMarginOnBorders"|"MixInBackColorFromParentRecursive"|"EncoderUseDisplay"|"AutoScrollToEnd"|"AllowAddContent"|"AllowAddNewline"|"AllowMergeChildren"|"AllowEdit"|"CanProvideUiGridSelection"|"AllowFilterContent"|"FilterBlockUIEnabled"|"GapsForExpanded"|"UseUserProfileSettings"|"ScrollOutEnabled"|"VScrollOnHeader"|"ConvertCursorToTabAtBoundaries"|"AutoNextCell"|"SelectionOnFocusOnly"|"ScrollCellAutomatic"|"ScrollCellAutomaticWithOffset"|"StealFocusAfterSelect"|"CmdlineInteraction"|"TargetCmdlineInteraction"|"EditAllowedAdd"|"EditAllowedDelete"|"CreateAndEdit"|"AddTargets"|"ObserveSelectionChange"|"HiglightActiveCue"|"OnlyVisible"|"Inverted"|"Content"|"TryAvoidZeroes"|"TryFitMainIfContentDriven"|"TryFitIntoSecondary"|"SeparatorSupport"|"ModifyTextureLayout"|"Local"|"IsWorldCoordinateSystemActive"|"IsCameraFocusOnSelectedItem"|"SearchFocusTestParent"|"SearchFocusTestParent"|"WantsModal"|"AutoClose"|"AutoCloseOnOverlay"|"CloseOnEscape"|"StayAlwaysVisible"|"RelativeToDisplay"|"AdjustInitialPosition"|"IsMainBuddy"|"UseSimplifiedResize"|"DriveReset"|"OverrideKeybSC"|"ReactToPreview"|"ReactToEdit"|"ExclusivePropertyChange"|"PositionBeneathFinger"|"IsScribbleNew"|"IsAppearanceNew"|"SuppressModeSwitch"|"ScreenEncoder"|"TitleButtonBool"|"MixPercentAndHexDecModesAllowed"|"AllChannelSets"|"DimmerCueOnly"|"FilterByManufacturer"|"FilterByName"|"FilterByMode"|"FilterByDescription"|"FilterByUsedOnly"|"FilterByName"|"IsMidiOut"|"State"|"AutoCloseOnInput"|"ShowUnpatchedOnly"|"EditTitlebar"|"InitialSaveEditTarget"|"EditTargetHasChanged"|"CanBeEmbedded"|"CalledFromCmdline"|"UpdateSettingsVisibility"|"InitialSaveEditTarget"|"EditTargetHasChanged"|"ShowFullSettings"|"CloseProhibited"|"PrimaryHasFocus"|"IsInExport"|"ShowFileSegmentShowData"|"ShowFileSegmentLocalSettings"|"ShowFileSegmentOutputStations"|"ShowFileSegmentDmxProtocols"|"ReadOnly"|"ShowLineNumbers"|"ShowWhiteSpace"|"HighlightCurrentLine"|"NewlineWithSpaces"|"ForceCursor"|"VisualisableScrollV"|"VisualisableScrollH"|"EnterToExecute"|"DependsOnLinkedObject"|"ReactToPreview"|"ReactToEdit"|"SmallResizeArea"|"ShowManualCueSelection"|"ContentChanged"|"NoEmptyNames"|"ReactToRecipeEdit"|"TargetIsScribble"|"AutoClose"|"ProvideEmpty"|"TargetIsAppearance"|"BigMode"|"AutoCreateFromProperties"|"UseEditorTarget"|"ForceHideCategories"|"Features"|"FeatureGroups"|"FeatureGroupsOnly"|"NoEmptyNames"|"ForceSmallMode"|"ShowVisibleDay"|"Auto"|"IgnoreIconForTextAlign"|"ShowLabel"|"ShowValue"|"DataAsIs"|"AutoHide"|"IndirectEdit"|"ValueAutoAdjust"|"DirectProperty"|"DefaultAction"|"CharAction"|"Undo"|"ValueTextShadow"|"IgnoreActiveForEnums"|"SetIconAsActiveInactive"|"EditNewObject"|"UseGridColor"|"DrawContent"|"BackgroundButtonStyle"|"ContentStyle"|"AutoTexture"|"DirectCommand"|"DirectQuotation"|"InteractWithCommandline"|"ShowOldVersions"|"UseDefaultValue"|"ForceFastFade"|"SmallMode"|"ReactToRecipeEdit"|"DrawShortcutInfo"|"Toggle"|"ShowCSHelp"|"DefaultAction"|"AutoEnabled"|"WorkWithGrid"|"ChangeDestination"|"WorkWithGrid"|"UseComposedText"|"TrackEdit"|"TrackWorld"|"ShowSelectionCount"|"ShowAdditionalInfo"|"DisplayLevel"|"AllowedInvisible"|"TextChangeOnEnter"|"ForceCursor"|"LongPressVK"|"ReadOnly"|"KeyRepeatEnabled"|"ShowKeyboardButton"|"Secret"|"SetPropertyOnlyOnTextChange"|"ForceFocusOnChange"|"AvoidScroll"|"Rounded"|"IndicatorBarEnabled"|"ShowLeftIcon"|"ShowNumber"|"ShowRightIcon"|"ShowAdditionalInfo"|"ShowLeftScribble"|"ShowRightScribble"|"AllowBlocks"|"SkipTextIfIconExists"|"ItemIndividualCorners"|"IndirectEdit"|"ScrollChangesSelection"|"UseTabRegistry"|"IncludeTarget"|"DirectQuotation"|"CloseOnClick"|"UseCommandlineClick"|"AutoCloseAllowed"|"PanScrollArea"|"PanScroll"|"ResetChildrenSize"|"ShowTcSlotAndTcMode", property_value: YesNo|boolean)
---@overload fun(property_name: "DrawGradient"|"AllowSorting"|"IsCloneDestination"|"AutoSetWindowSettings"|"IsScribbleAvailable"|"IsAppearanceAvailable"|"IsNoteAvailable"|"ScribbleIsEmpty"|"ChangeDestination"|"AllIndexesCollected"|"FadeEncoder"|"UseSpecialTimezone"|"IsPlaying"|"CheckForScreenEncoders"|"Expanded"|"Blink", property_value: boolean)
---@overload fun(property_name: "ChangeActive", property_value: fun(childName: string) : boolean)
---@overload fun(property_name: "Update"|"Close"|"CloseConfirm"|"CloseCancel"|"OnTitleClick"|"StoreP1"|"CallP1"|"StoreP2"|"CallP2"|"StoreP3"|"CallP3"|"StoreP4"|"CallP4"|"Solve"|"OnTitleClick"|"OnTitleClick", property_value: fun(dummyStr: string) : boolean)
---@overload fun(property_name: "OnUniverseUpClicked"|"OnUniverseDownClicked"|"OnUnpatchClicked"|"OnPatchToClicked", property_value: fun(dummyStr: string, button: MouseButtonTypes, X: integer, Y: integer) : boolean)
---@overload fun(property_name: "OnBreakSelected"|"OnBreakPatched"|"OnAddressSelected"|"OnDBObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer) : boolean)
---@overload fun(property_name: "OnObjectSelected", property_value: fun(dummyStr: string, column: integer, row: integer, int: integer) : boolean)
---@overload fun(property_name: "Clear", property_value: fun(dummyString: string) : boolean)
---@overload fun(property_name: "ShowMessage"|"HideMessage", property_value: fun(message: string) : boolean)
---@overload fun(property_name: "ChangeText", property_value: fun(newTextStr: string) : boolean)
---@overload fun(property_name: "SetPrompt", property_value: fun(prompt: string) : boolean)
---@overload fun(property_name: "FilterRows", property_value: fun(str1: string, str2: string) : boolean)
---@overload fun(property_name: "DescriptionChanged"|"OnCreateNewAppearance"|"OnScreenPushed"|"LassoFinished"|"PathChanged"|"UrlChanged"|"ProgressChanged"|"StatusChanged"|"TooltipChanged"|"OnUserProfileChanged"|"FilterChanged"|"Execute"|"ScrolledToEndV"|"OnListRefDone"|"Scrolled"|"ResizeStart"|"ResizeEnd"|"ResizeStart"|"ResizeEnd"|"AppearanceTargetChanged"|"ScribbleTargetChanged"|"MoveStart"|"MoveStart"|"Execute"|"TextChanged"|"OnWrongChar"|"OnCreateNewScribble"|"OnCreateNewAppearance", property_value: fun(str: string))
---@overload fun(property_name: "ClearSelection"|"SelectAllRows"|"ClearFilter"|"ExpandAll"|"ScrollToEnd"|"ResetView"|"ZoomIn"|"ZoomOut"|"TimecodeBackward"|"TimecodeRecord"|"TimecodeForward"|"TimecodeStop"|"TimecodePause"|"TimecodePlay"|"TimecodePrevMarker"|"TimecodeNextMarker"|"SelectionCopy"|"SelectionCut"|"SelectionPaste"|"TimecodeAddEvent"|"TimecodeAddMultiEvents"|"TimecodeAddTimeRange"|"TimecodeAddTimeMarker"|"SetPath"|"SetFilter"|"GoUp"|"SelectFirstFile"|"ScrollToFirstFile"|"DeleteSelectedFiles"|"ResizeStart"|"ResizeEnd"|"ScrollAction"|"SetUrlA"|"GoBack"|"GoFwd"|"Reload"|"RequestMemUsage"|"Search"|"OnZoomToFit"|"OnSetRecalcCenterOfGravity"|"OnNavigate"|"SaveToDefault"|"LoadFromDefault"|"MoveStart"|"ResizeEnd"|"TabChanged"|"EnumClicked"|"OnPatchToNextFree"|"OnMoveToUniverse"|"OnSpecialButtonClicked"|"SelectedManufacturer"|"SelectedFixture"|"RememberSelection"|"InitGrids"|"SetDateToday"|"SetTimeNow"|"OnInput"|"OnState"|"OnCommand"|"OnTitle"|"OnFocusLost"|"OnPatchToClicked"|"OnShowUnpatchedClicked"|"DeleteClicked"|"TBDeleteAll"|"TBLoadDefaults"|"ChangedActiveTab"|"SaveEditTarget"|"RevertEditTarget"|"MeasureColor"|"DarkCalibrate"|"FindDevice"|"OnClearCmdline"|"Context"|"SaveEditTarget"|"RevertEditTarget"|"SGResizeStart"|"SGResizeEnd"|"CheckAutoClose"|"OnCheckSubPoolSelector"|"OnSelectDataPool"|"OnCollectAllIndexes"|"OnFixtureSourceChanged"|"OnSelectedTreeItem"|"OnScrolledTreeItem"|"Undo"|"Redo"|"SetText"|"InsertText"|"ClearText"|"SetCursorToEnd"|"KeyPress"|"FunctionSelectorChanged"|"EncoderReadoutSelectorChanged"|"ResizeStart"|"MoveStart"|"Context"|"UpdateEncoderBar"|"DeleteOld"|"OnToolOperate"|"SGResizeStart"|"SGResizeEnd"|"OnEditCurrentLayout"|"OpenAtFilter"|"OnSwipeMenu"|"SetToTop"|"ScrollPageDown"|"ApplyScribble"|"RevertScribble"|"OnCreateNewScribble"|"DeleteFilterItem"|"AddFilterItem"|"OnDataPoolChanged"|"OnStageChanged"|"OnSetSelectorVisibility"|"OnCreateNewAppearance"|"ToggleListRef"|"SelectAll"|"SelectNothing"|"SwitchExpansion"|"OnCollapseAll"|"OnSwipeMenu"|"MapClicked"|"OnExpandAll"|"OnCollapseAll"|"OnExpandSelected"|"OnClearSelection"|"ToggleAtFilter"|"Play"|"Pause"|"Stop"|"ShowAnimation"|"ResetMouse"|"OpenVK"|"SelectAll"|"DeSelect"|"SetCursorToEnd"|"ProgressChanged"|"ClearScribble"|"OnApplyColorToCurves"|"SetPlus"|"SetMinus"|"AutoScroll"|"OnFunction", property_value: fun(str: string) : boolean)
---@overload fun(property_name: "ResizeMove", property_value: fun(str: string, AbsX: integer, AbsY: integer))
---@overload fun(property_name: "Clicked"|"DoubleClicked"|"MouseUp"|"MouseDown"|"MouseDownHold", property_value: fun(str: string, Button: MouseButtonTypes, X: integer, Y: integer))
---@overload fun(property_name: "ResizeMove"|"ResizeMove"|"Move"|"Move", property_value: fun(str: string, DeltaX: integer, DeltaY: integer))
---@overload fun(property_name: "OnAssignTarget", property_value: fun(str: string, Target: Object, TargetPropertyName: string, rowId: integer) : boolean)
---@overload fun(property_name: "ClickedLeft"|"ClickedRight"|"MouseEnter"|"MouseLeave"|"MouseOverHold"|"MouseUpLeft"|"MouseUpRight"|"MouseDownLeft"|"MouseDownRight", property_value: fun(str: string, X: integer, Y: integer))
---@overload fun(property_name: "OnVisible"|"MoveEnd"|"MoveEnd"|"ResizeEnd", property_value: fun(str: string, bool: boolean))
---@overload fun(property_name: "ResizeEnd"|"MoveEnd", property_value: fun(str: string, bool: boolean) : boolean)
---@overload fun(property_name: "OnBeforeEdit"|"OnAfterEdit"|"OnSelectionAfterCmd"|"UndoRedoChanged"|"SelectionChanged"|"ResizeStart", property_value: fun(str: string, int1: integer, int2: integer))
---@overload fun(property_name: "SelectCell"|"ResizeMove"|"Move"|"ResizeStart"|"Resize"|"SGResizeMove"|"ResizeMove"|"Move"|"SGResizeMove"|"SelectRange"|"CallSubMenu", property_value: fun(str: string, int1: integer, int2: integer) : boolean)
---@overload fun(property_name: "TabChanged", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean))
---@overload fun(property_name: "GroupChangedTab", property_value: fun(str: string, int1: integer, int2: integer, bool1: boolean, bool2: boolean) : boolean)
---@overload fun(property_name: "OnSelectedItem"|"TabClickedOnCurrent", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean))
---@overload fun(property_name: "GroupClickedTab", property_value: fun(str: string, int1: integer, int2: integer, bool: boolean) : boolean)
---@overload fun(property_name: "ReloadCamera"|"ResetCamera"|"AnalyzeMeshPool"|"SelectionToGrid"|"ActionSetPriority"|"ReloadRenderQuality"|"ReloadCamera"|"HardkeyMouseUp"|"HardkeyMouseDown"|"OnShow3dSettings"|"OnClick"|"FactoryDefaults"|"RotateToCircleCenter"|"Rotate90ToLine"|"ResetUnusedAxis"|"ResetRotation"|"ResetPosition"|"Show3DSettings"|"CenterPosition"|"ArrangePosition"|"Oops"|"OnClick"|"OnClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer) : boolean)
---@overload fun(property_name: "GestureClick"|"GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer))
---@overload fun(property_name: "GestureClick", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer) : boolean)
---@overload fun(property_name: "OnCellMouseDown"|"OnCellMouseDownHold"|"OnCellMouseUp"|"OnCellMouseClicked"|"OnCellMouseDoubleClicked", property_value: fun(str: string, int1: integer, int2: integer, int3: integer, int4: integer, int5: integer))
---@overload fun(property_name: "SelectAbsoluteAddress", property_value: fun(str: string, int: AbsoluteAddress) : boolean)
---@overload fun(property_name: "OnSelectedColumn"|"OnSelectedRow"|"OnTargetChanged"|"MemUsageUpdated"|"OnTargetChanged"|"OnSelectedItem", property_value: fun(str: string, int: integer))
---@overload fun(property_name: "SelectRow"|"AddRow"|"SelectColumn"|"SortByColumn"|"ScrollVertical"|"ScrollHorizontal"|"ChangeTarget"|"SelectionChanged"|"ScrollToRow"|"ReTriggerInit"|"ReTriggerInit"|"AddSelectedFixtures"|"ClearGrid"|"GridMoveUp"|"GridMoveDown"|"GridCopy"|"GridPaste"|"GridAdd"|"GridDelete"|"GridCut"|"GridFillUp"|"GridUnify"|"SetFPSLimit"|"JumpToNextLine"|"JumpToPreviousLine"|"AddMissingLines"|"AddSelectedLines"|"ChangeTarget"|"OnChar"|"OnChar", property_value: fun(str: string, int: integer) : boolean)
---@overload fun(property_name: "KeyDown"|"KeyUp", property_value: fun(str: string, keyCode: VirtualKeyCode, bool1: boolean, bool2: boolean, bool3: boolean))
---@overload fun(property_name: "ForceScale"|"Seek", property_value: fun(str: string, num: number) : boolean)
---@overload fun(property_name: "FocusGet"|"FocusLost", property_value: fun(str: string, obj1: Object, obj2: Object))
---@overload fun(property_name: "OnLoad"|"OnSetEditTarget"|"OnSetEditTarget"|"OnSetEditTarget"|"LinkedObjectChanged", property_value: fun(str: string, obj: Object))
---@overload fun(property_name: "OnFocusGet", property_value: fun(str: string, obj: Object) : boolean)
---@overload fun(property_name: "OnAssignTargetSelected", property_value: fun(str: string, obj: Object, str: string, int: integer))
---@overload fun(property_name: "TouchStart"|"TouchUpdate"|"TouchEnd", property_value: fun(str: string, pointID: integer, X: integer, Y: integer))
---@overload fun(property_name: "OnUpdateTitle"|"OnUpdateTitle", property_value: fun(str: string, str: string))
---@overload fun(property_name: "CharInput", property_value: fun(str: string, utf32Char: integer))
---@overload fun(property_name: "Changed", property_value: fun(str: string, value: integer))
---@overload fun(property_name: "Set", property_value: fun(str: string, value: integer) : boolean)
---@overload fun(property_name: "DoReset"|"InitFirst"|"ChangeCloningViewMode"|"DoClone"|"OpenSequenceFilter"|"OpenGroupFilter"|"OpenPresetFilter"|"OpenWorldFilter"|"OpenLayoutFilter"|"AllItemsToAll"|"AllItemsToNone"|"InitTargetList"|"FlipLeftRight"|"SetText"|"AddText"|"InsertText"|"SelectFirst"|"ObtainCurrentCue", property_value: fun(text: string) : boolean)
---@overload fun(property_name: "FrameWidth"|"AutoCloseValue"|"UiGroupId"|"ForceIntensity"|"Page"|"HeadLineDimension"|"ButtonDimension"|"SlotDimension"|"ColorIndicatorHeight"|"MaxValue"|"MinValue"|"ExecutorIndex"|"MaxIndicatorSize"|"DefaultMargin"|"Columns"|"Rows"|"CellWidth"|"CellHeight"|"BlockWidth"|"BlockHeight"|"FrameThickness"|"ScrollCellFrameThickness"|"LevelDistance"|"ColumnResizeMaxDeviation"|"LevelLimit"|"SelectedRow"|"SelectedColumn"|"AutoFitColumn"|"GridVersion"|"IgnoreChildren"|"MinCellSize"|"LevelLimit"|"GridDelta"|"Priority"|"RasterHeight"|"RasterWidth"|"TitleButtonInt64"|"TitleButtonUInt64"|"TitleButtonPopup"|"BreakIdx"|"FixtureCount"|"PatchOffset"|"PatchOffset"|"FilterMask"|"VisibleFixturesCount"|"Hour"|"Minute"|"Second"|"Day"|"Year"|"Selector"|"SubDestination"|"ShowFileSegmentsMask"|"UndoCount"|"RedoCount"|"ExecFrom"|"ExecRowCount"|"ExecColCount"|"DelimiterSize"|"ActiveSource"|"BigModeColumns"|"BigModeRows"|"RasterHeight"|"RasterWidth"|"ExecBarToDraw"|"FirstRow"|"LastRow"|"LineHeightAdd"|"LineSpacing"|"State"|"LabelAreaHeight"|"SpecialExecOffset"|"Direction"|"Mask"|"OptionHeight"|"Mask"|"IncrementFactor"|"ExecutorIndex"|"SlotIndex"|"MaxTextLength"|"Distance"|"ItemSize"|"VisibleItemCount"|"MaxValue"|"ExecutorIndex"|"Border", property_value: integer)
---@overload fun(property_name: "RunningPlaybacks", property_value: integer[])
---@overload fun(property_name: "Progress"|"ItemPlacementOffsetFactorV"|"ItemPlacementOffsetFactorH"|"CurrentFps"|"ScaleAll"|"RatioAll"|"IconScale"|"EncoderResolution"|"Value", property_value: number)
---@overload fun(property_name: "Text"|"ToolTip"|"HelpTopic"|"SignalValue"|"SignalValueHold"|"AppearanceSourceClassName"|"Property"|"System"|"Value"|"BarText"|"DataType"|"SelectionType"|"CellType"|"SettingsType"|"InsertType"|"FuzzyFilter"|"FuzzyFilterExcludeEnd"|"BaseFilter"|"SelectedFile"|"CurrentSelectedShowFile"|"ReleaseNotesUrl"|"TrademarksUrl"|"PrivacyPolicyUrl"|"EditEncoderBar"|"ControlEncoderBar"|"BuddyGroupId"|"Value"|"StrContext"|"FixtureName"|"FilterComposed"|"Filter"|"DefaultTitle"|"FixtureToMeasure"|"InitialTab"|"InitialSubTab"|"Destination"|"ForcedInitialTab"|"Destination"|"Content"|"Property"|"EditEncoderBar"|"ControlEncoderBar"|"SwipeMenu"|"TargetPropertyName"|"EmptyName"|"SwipeMenu"|"Property"|"TargetPath"|"ReferencedTitleButton"|"Property"|"System"|"Value"|"AuxProperty"|"DirectPrefix"|"TextLeftCorner"|"LedToken"|"ImportOptions"|"DummyComposedText"|"AdditionalInfo"|"WarningTooltip"|"Property"|"VKPluginName"|"VKTitleHint"|"Prompt"|"Filter"|"EmptyText"|"Message"|"System"|"ActiveChild"|"ItemType"|"ItemFilter"|"Property"|"Property"|"DirectPrefix"|"EditEncoderBar"|"Property"|"Property"|"System"|"Cursor"|"System", property_value: string)
---@overload fun(property_name: "DependentBuddies", property_value: string[])
---@overload fun(property_name: "AllTitlebuttons", property_value: table<string, TitlebuttonControl[]>)
---@overload fun(property_name: "AdditionalArgs", property_value: table<string, string>)
---@overload fun(property_name: "Padding"|"Anchors"|"Margin"|"ContentAreaMargin"|"LabelAreaMargins"|"ValueAreaMargins"|"OptionAreaMargin", property_value: {left: integer, right: integer, top: integer, bottom: integer})
---@overload fun(property_name: "AbsRect"|"AbsClientRect"|"WindowRect", property_value: {left: number, right: number, top: number, bottom: number})
function Item:SetChildrenRecursive(property_name, property_value) end